### ISSUE TITLE
Leading negative sign followed by a bracket causes "Missing number, treated as zero" error

### ISSUE THREAD

**Issue by loopspace** [latex3/latex3#1001]
(Apologies if this has already been fixed or noted.)

An expression of the form `-(1+1)` causes the error `Missing number, treated as zero.` when used in an `int` expression (such as `\int_eval` or `\int_set`):

```
\documentclass{article}

\ExplSyntaxOn

\int_set:Nn \l_tmpa_int {0-(1+1)} % No error
\int_set:Nn \l_tmpa_int {-1+1} % No error
\int_set:Nn \l_tmpa_int {-(1+1)} % ! Missing number, treated as zero.

\ExplSyntaxOff

\begin{document}
\end{document}
```

**Comment by blefloch** [comment]
This is a well-known eTeX problem: `\the\numexpr -(1+1)\relax` produces the same error.  Reading (for instance) `pdftex.web`, it looks like the following chunk of code needs to be changed a bit, adding a test for `other_token+"+"` (which can then be removed and ignored) and `other_token+"-"`.  I don't see how to easily keep track of that sign in `@<Push the expression...@>=` and `@<Pop the expression...@>=`.
```
@ @<Scan a factor...@>=
@<Get the next non-blank non-call token@>;
if cur_tok=other_token+"(" then
  @<Push the expression stack and |goto restart|@>;
back_input;
if o=int_val then scan_int
else if o=dimen_val then scan_normal_dimen
else if o=glue_val then scan_normal_glue
else scan_mu_glue;
f:=cur_val
```
One needs to be careful about precedence of various operations, for instance one cannot just treat the unary minus/plus as binding tighter than everything else, otherwise `1/-(2)/3` would be parsed as `1/-(2/3)`.

**Comment by blefloch** [comment]
This is documented in l3int, actually, so I'll close here.  If someone cares enough they should raise it with the (inexistent?) pdfTeX maintainers.
