### ISSUE TITLE
`\l_file_search_pre_path_seq` variant of `\l_file_search_path_seq`

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#1019]
The fact that `\l_file_search_path_seq` (as well as `\input@path`) is used only after `kpse` has failed is not always a good thing.

## The problem
Assuming the `Directory` folder exists next to the following main document.
We create 2 files inside this folder, but the second one is **unreachable due to name collision**.

```
\documentclass{article}
\begin{filecontents}{Directory/a very weird file name.tex}
A very weird file content
\end{filecontents}
\begin{filecontents}{Directory/variations.tex}
variations
\end{filecontents}
\ExplSyntaxOn
\seq_put_right:Nn \l_file_search_path_seq { Directory }
\ExplSyntaxOff
\begin{document}
A very weird file content = \input{a very weird file name}

variations = \input{variations}
\end{document}
```

## Expected
Both files should be reachable.
The file name `variations` should not be forbidden.

## Alternate solutions

Fully qualifying the file name negates the eventual benefits of `\input@path`.

Renaming the file is absolutely inacceptable mainly for 2 reasons

1. the user must be free to name and organize its files according to its own convenience and must not be constrained by any implementation detail.
2. Upgrading a TeX distribution may break a document due to name collisions which is veeeery difficult to debug when not an expert.

## Suggestion

`\l_file_search_pre_path_seq` should be implemented as well such that for

```
\ExplSyntaxOn
\seq_put_right:N \l_file_search_pre_path_seq { foo }
\seq_put_right:N \l_file_search_path_seq { bar }
\input {whatever}
\ExplSyntaxOff
```
kpse will look for "foo/whatever.tex", "whatever.tex", "bar/whatever.tex" in that very order.

**Comment by blefloch** [comment]
I think it is a good idea.  The main question is what name would be reasonable for this variable.

**Comment by josephwright** [comment]
I guess I'm missing some central here: where's the issue? It's well-established that `TEXINPUT`, etc., is the preferred way to find files, and as such each file should have a separate name. The path approach is for _e.g._ `figures/foo` on a per-document level, and it works well already: the re-implemenation in `expl3` should already offer the same ideas as `\input@path`.

**Comment by blefloch** [comment]
The problem comes when your figure is called `plain`, or some other pretty reasonable name that just happens to collide with an unrelated system file.  Then kpsewhich will find the unrelated system file in preference to your own file if you own file is in a subdirectory (according to this report, but I haven't double checked).

**Comment by jlaurens** [comment]
Another potential problem with a MikTeX bare TeX installation. This has not been tested though.

create document 1 to import `./Directory/variations.tex` with the help of `\l_file_search_path_seq`:

```
\documentclass{article}
\begin{filecontents}{Directory/variations.tex}
SUCCESS
\end{filecontents}
\ExplSyntaxOn
\seq_put_right:Nn \l_file_search_path_seq { Directory }
\ExplSyntaxOff
\begin{document}
variations = \input{variations}
\end{document}
```
`kpsewhich` expectedly finds `variations.tex` as `./Directory/variations.tex`.

Then create document 2:
```
\documentclass{article}
\RequirePackage{variations} // ⟵ Unexpected side effects
\begin{document}
Nothing
\end{document}
```
MikTeX automatically downloads `variations.sty` which happens to also install a `variations.tex` support file.
Now `kpsewhich` finds `variations.tex` as `.../tex/generic/variations/variations.tex` and **document 1 gets broken**.

Creating a new TeX document can silently break already existing sources.

**Comment by jlaurens** [comment]
`\l_file_doc_search_path_seq` seems a good starting point as these files are related to the document domain.

**Comment by u-fischer** [comment]
> I guess I'm missing some central here: where's the issue?

@josephwright well the issue is that all the document level path setting commands  are used after kpsewhich. That is not restricted to expl3. This here e.g.

~~~~
\documentclass{article}
\usepackage{graphicx}
\graphicspath{{chapters/}}
\begin{document}
\includegraphics{example-image}
\includegraphics{./example-image}
\includegraphics{chapters/example-image}
\includegraphics{sub}
\end{document}
~~~~

will input 

```
<c:/texlive/2021/texmf-dist/tex/latex/mwe/example-image.pdf> 
<./chapters//./example-image.pdf>
<./chapters/example-image.pdf>
<./chapters/sub.pdf>
```

Imho that is something people are often not really aware of. 

But I don't think that the suggested new command can solve this. We can't put the local pathes in front everywhere, that would slow down file search imho. And if it should be optional one would need an user interface to choose. And if the user has to handle this anyway, it seems easier to tell them to use `./file` for local files.

**Comment by jlaurens** [comment]
@u-fischer 
Very good point.

If my understanding of Kpathsea is correct,  this `./` trick should **always** be used despite it is not user friendly, not only for the above mentioned name collision problem, but also to speed up file search.

So no real need for another command. Nevertheless, this `./` trick should seriously be documented at different appropriate places.
