### ISSUE TITLE
`⟨property list⟩` vs `⟨property var⟩`

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#1032]
The documentation seems to use indifferently `⟨property list⟩` and `⟨property var⟩`. If they mean the same thing, it is worth to use a single name.

**Comment by FrankMittelbach** [comment]
I guess it should be `property list` if taking about the concept. The situation with variables is a bit inconsistent, We call integer variables `<integer>`  and seq variable a `<sequence>`,  but with comma lists we say `<clist var>` (do be able to distinguish it from `<comma list>` meaning the object "in flight"). So we could standardize on `<prop var>`  to mimic that or on `<property list>`because they always only exist related to a data structure (at least so far). 

The documentation probably reads better if we always call it a `<property list>` or if we want to have "var" then `<prop var>`but not the mix that Denis noticed.

**Comment by muzimuzhi** [comment]
How about `<plist var>`?

**Comment by FrankMittelbach** [comment]
it is not a "list" really, at least for me list implies some order and they don't have that.

**Comment by car222222** [comment]
@FrankMittelbach I think that this (ordered, or not) distinction has been long lost in our use of terminology.  

We called these things "property lists" long ago. 

And we often use a clist for things that are not, by their nature, ordered in any sense.
