### ISSUE TITLE
FR: \prop_set_from_value:Nn = \tl_set:Nn

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#1047]
Sometimes, it is necessary to treat complex data types as if they were just raw token lists. For example, in next pattern, we catch some changes in a property list inside a group and propagate them outside the group.
```
\documentclass{article}
\begin{document}
\ExplSyntaxOn
\prop_put:Nnn \l_tmpa_prop { KEY1 } { VALUE1 }
\group_begin:
\prop_put:Nnn \l_tmpa_prop { KEY2 } { VALUE2 }
\exp_args:NNNV
\group_end:
\tl_set:Nn \l_tmpa_prop \l_tmpa_prop
\prop_map_inline:Nn \l_tmpa_prop {
#1: #2\\
}
\ExplSyntaxOff
\end{document}
```
After the group, the property list contains 2 key-value pairs.
That use of `\tl_set:Nn` seems weird because we apply a function of the `tl` module to a variable of type `prop`, but it really makes sense because we want some macro value to live past the group end.
If we had a `\prop_set_from_value:Nn` to provide the functionality of `\tl_set:Nn`, things would be more clear. Of course, `\seq_set_from_value:Nn`, `\clist_set_from_value:Nn` and variants would make sense as well. Moreover, `\prop_concat_from_value:Nnn` and variants may help, but would not be as straightforward.

**Comment by josephwright** [comment]
Looks like https://github.com/latex3/latex3/issues/332 to me. Note that you are relying on internals here, and we are currently discussing revising these!

**Comment by blefloch** [comment]
The issue is somewhat different: #332 was about going all the way to a file, which raised the thorny issue of catcodes.  Here it's more related to manipulating n-type prop/seq etc.  In principle it would be nice if the `V` argument type would automatically take care of detecting prop/seq etc and correctly unpacking them if needed, but I don't think that it is possible without slowing down all uses of `V`.  Perhaps a name like `\prop_to_prop:N` (expandable) and `\prop_set_from_prop:Nn`?

In my alternative implementation (still ongoing) of props as doubly-linked lists, `\prop_to_prop:N` could be simply `\exp_not:f`, which remains rather simple, but is slightly more elaborate than the `o`-type expansion that is currently enough.

**Comment by jlaurens** [comment]
About the name ˋ\prop_set_from_prop:Nn`. The `n` argument specification is very special in the sense that it must be properly formated according to the underlying implementation of the data type. This is not what occurs generally with other functions where `n` arguments are fed with whatever the user wants. To emphasize this difference, a new `i` specification could cover that special situation:
`\<data type>_set_from_internal:Ni`

**Comment by FrankMittelbach** [comment]
I'm not convinced. There should not be public functions that expect an argument that requires data in a format that exposes the internals of a data type. That would mean it is ok to construct whatever goes in there manually and that means the internal form is no longer internal.

**Comment by blefloch** [comment]
No, it doesn't make the form less internal and constructible by hand.  We can very well document that these functions receive only the result of f-expanding a prop and nothing else.

This issue is not listing another benefit of being able to manipulate n-type props etc, which is to allow for nested data structures, like a prop whose entries are sequences or props, etc.  Even something as simple as a sequence of floating points most sensibly implemented by storing the internal fp inside the sequence, rather than converting back and forth between the internal form (for calculations) and the decimal representation.  I think there is a long-standing issue about such nesting, but I couldn't find it.

**Comment by jlaurens** [comment]
Coming back to my laptop where backticks are backticks, contrary to my smartphone...

I am still in favor of a new "i" parameter specification. I don't know the difficulties of implementation but from a client POV that makes sense for different reasons, mainly because it circumvent the usage.

1) instead of documenting each function containing "internal" in its name like `\<data>_set_from_internal:Nn`, we can document once for all an "I" argument specifier, probably in a dedicated section.
2) `\cs_new:Nn` and friends should not be allowed to create functions containing "I" in the signature,
3) Generating variants is allowed for "n" arguments. In that case, expansion makes no sense, and o, f, e x variants should not be used. For the V variant `\<data>_set_from_internal:NV` is equivalent to `\<data>_set_eq:NN` and `\<data>_set_from_internal:Nv` is equivalent to `\<data>_set_eq:Nc`. Finally, no variant is useful for an "I" argument.
4) Whereas an "n" argument is used as it is, how an "I" argument is really used is undefined. This is not the problem of the end user, it only concerns the programmer. Today, an "I" argument is used as it is, but nothing prevents something different in the future. For example, some complex data type may implement a private state that should not be copied, or may reorganize the internals for better efficiency before copy...

Finally, a new "I" specifier is just another "odd specifier" like T, F, p, w, D.
