### ISSUE TITLE
Feature request: \prg_gset_conditional:...

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#1079]
When not at the top level, redefining globally a set of conditionals is possible with `\prg_new_conditional:...` but it must follow some \cs_undefine:N commands which is rather heavy. `\prg_gset_conditional:...` would be more practical.

**Comment by josephwright** [comment]
On reflection, we think that actually the `set` function has no obvious use cases. So we are minded to deprecate that one - unless you can suggest a strong use case that shows it's needed.

**Comment by josephwright** [comment]
I think we need to tidy up our own code here ... :)

**Comment by Loara** [comment]
> On reflection, we think that actually the `set` function has no obvious use cases. So we are minded to deprecate that one - unless you can suggest a strong use case that shows it's needed.

I prefer `\cs_(g)set` would work like `\int_(g)set`: if the contol sequence is already defined then overwrites its body (locally or globally), otherwise an error is issued. In other words a LaTeX3 equivalent of `\renewcommand`.

In this way we can have also local and global functions other than local/global variables, and in order to increase performance also constant functions that once they're created you shouldn't modify them.

A nonconstant function would be useful every time you need a function to be used as a pointer to other functions. Now you can do this with a token list variable but in this way you don't have any argument boundary check.

**Comment by josephwright** [comment]
I'm reminded that we looked again and decided we would do this: I'll take it

**Comment by josephwright** [comment]
@Loara  The fact that `cs` do not use the same approach as variables is by-design. There are various places we need tight loops, and the hit from requiring a `new`/`set` approach would be unacceptable in performance terms. It's also the case that there are very few places you need to keep re-defining a function compared with setting a variable. So the danger of save-stack build-up is very low.

I'm not really sure what you mean about constants: at the engine level, there's no difference between a 'constant' and a 'variable' macro - it's a language convention at the `expl3` level.

**Comment by Loara** [comment]
Macro `\cs_set` can be useful like any local variable. I have never used any local variable in my code but I think if someone needed a local variable for the same reason he would need to define a function only inside a group. Making `\cs_set` deprecated will force the user to pollute the global scope with useless functions.

For the part of constants: It was only a tip about a  possible performance rise for functions which body won't change, but since I don't now how the newest compilerss work I don't now if it's worth to be implemented.

**Comment by josephwright** [comment]
@Loara  The scoping rules for TeX mean it is much better to declare all names in global scope: we do that even for local variables for good reason.

I think you are maybe confused about how TeX handles macros and registers: there are no constants at an engine level, only by convention at the macro level. So there is no performance implication of naming as a constant.
