### ISSUE TITLE
Unlike `\tl_case:Nn`, `\str_case:Nn` fails to match identical token lists

### ISSUE THREAD

**Issue by Witiko** [latex3/latex3#1097]
### Minimal working example

``` tex
\documentclass{minimal}
\begin{document}
\ExplSyntaxOn

\tl_const:Nn
  \c_text_tl
  { text }

\tl_case:NnF
  \c_text_tl
  {
    \c_text_tl { Matched }
  }
  {
    Not~matched
  }

\par

\str_case:NnF
  \c_text_tl
  {
    \c_text_tl { Matched }
  }
  {
    Not~matched
  }

\ExplSyntaxOff
\end{document}
```

### What is the expected output?

Matched  
Matched

### What is the actual output?

Matched
Not matched

**Comment by PhelypeOleinik** [comment]
That's the expected behaviour.  The syntax of `\str_case:nn(TF)` is:
```latex
\str_case:Nn <test string var>
  {
    { <string case 1> } { <code case 1> }
    { <string case 2> } { <code case 2> }
    ...
  }
```
while the syntax of `\tl_case:Nn(TF)` is:
```latex
\tl_case:Nn <test tl var>
  {
    <token list variable case 1> { <code case 1> }
    <token list variable case 2> { <code case 2> }
    ...
  }
```

Note that in the tl case, the reference variable is tested against a `token list variable`, while in the str case it is tested against a `string` (as opposed to a `string variable`).  This means that in `\str_case:nn`, each of the test cases is not expanded before comparison.

In the second case you want `\str_case_e:nn(TF)`:
```latex
\str_case_e:nnF { \c_text_tl }
  {
    { \c_text_tl } { Matched }
  }
  { Not~matched }
```

**Comment by Witiko** [comment]
@PhelypeOleinik Thank you. This was not at all clear to me from reading the documentation, although I attribute that to my weary mind at 3AM rather than the text of the documentation. Still, it may be worth putting an explicit warning to the documentation that `\tl_case:Nn` and `\str_case:Nn` have different expectations of the second parameter. Many `l3str` and `l3tl` functions are symmetric, which invites people like me to use them interchangeably.

**Comment by PhelypeOleinik** [comment]
No worries!  At 3 AM my brain is likely in a worse state :)

interface3 tries to be as concise as possible, and this means leaving some things implied, like the distinction between `<string var>` and `{ <string> }`.

> Many (most?) `l3str` and `l3tl` functions are (should be?) symmetric

Yes, most are symmetric (some identical, even), but there are exceptions.  The difference between them in this case is because both functions aim to be expandable, and while it is possible to compare two `<string>` expandably, it is not possible to compare two `<token list>`, only two `<tl var>`, thus the difference.  Then, since `n` arguments should not be expanded, `\str_case:nn` compares the two strings using `\str_compare:nnTF` (`\str_case_e:nn` uses `\str_compare:eeTF`).  But a note in the documentation of `\str_case:nn` pointing to `\str_case_e:nn` wouldn't hurt.
