### ISSUE TITLE
Strange results with `\IfFileExists`

### ISSUE THREAD

**Issue by niruvt** [latex3/latex3#1132]
Consider the following code:

### abcd.tex

```latex
\documentclass{article}
\def\print{\IfFileExists{abcd.log}{true}{false}}

\begin{document}
\print
\end{document}
```

On the first run this should return false, but it doesn't.

Now suppose I have another (uncompiled) `pqrs.tex` in the same folder and I use `pqrs.log` in the above code instead of `abcd.log`, the test works correctly. Why?

**Comment by niruvt** [comment]
Related discussion: https://tex.stackexchange.com/a/576082/174620

**Comment by u-fischer** [comment]
Why should it return false? The log is there when you start the compilation.

**Comment by eg9** [comment]
The `.log` file exists as soon as TeX inputs a file with a “good” name, either from the command line or before any typesetting takes place. Otherwise TeX assigns `texput` to `\jobname` and opens `texput.log`.

So if you do `pdflatex abcd` (from a terminal or via a front-end), the `abcd.log` file is immediately created.

**Comment by niruvt** [comment]
Ah, okay, thanks for the clarification, I was under misconception. Closing.
