### ISSUE TITLE
Add \cs_if_defined:NTF ?

### ISSUE THREAD

**Issue by lvjr** [latex3/latex3#1150]
From the documentation, I see `\cs_if_exist:NTF` doesn't treat `\relax` as an existing command, which makes it different from `\ifdefined` in eTeX (i.e. `\if_cs_exist:N` in expl3). Is it possible to add `\cs_if_defined:NTF` command?

**Comment by josephwright** [comment]
What's the use case here? We deliberately treated `\relax` differently.

**Comment by lvjr** [comment]
See https://github.com/lvjr/tabularray/issues/328

**Comment by FrankMittelbach** [comment]
There is a huge amount of code out there that  attempts to use `\expandafter\ifx\csname ...\endcsname\relax`and whenever something was touched via `\csname` itchanges from "fully undefined" to be equal to `\relax`.  Therefore the convention is that a command equal to `\relax` is is considered to be not in existence and can be freely defined, hence the definition as it is. True, this is not correct for the primitive `\relax` itself (which I would say should never be redefined, because that will in nearly call cases break badly even if restored later. There is much too much low-evel code that relies on `\relax` having its primitive meaning.)

**Comment by muzimuzhi** [comment]
> What's the use case here? We deliberately treated `\relax` differently.

Necessary or not, sometimes authors do want to distinguish undefined from defined to `\relax`. Even latex2e uses `\ifcsname` and `\ifdefined` in several places.

As an intermediate stage, perhaps `l3kernel` could provide user versions of `\tex_ifcsname:D` and `\tex_ifdefined:D` first. Probably `\if_cs:w` and `\token_if_defined:N` (well, the second is not so "intermediate").

**Comment by PhelypeOleinik** [comment]
> perhaps `l3kernel` could provide user versions of `\tex_ifcsname:D`

That already exists as `\if_cs_exist:w`.

`\tex_ifdefined:D` would probably be called `\if_defined:N` (primitive conditionals are called `\if_...`)

**Comment by muzimuzhi** [comment]
Ah thanks! Indeed both `\tex_ifcsname:D` and `\tex_ifdefined:D` already have user versions:
https://github.com/latex3/latex3/blob/b693d92d5819e5fe17bf5b19a2bf5c351bd437e3/l3kernel/l3basics.dtx#L1400-L1401

I'll open a PR to add a TeXhackers note having `\ifdefined` and `\ifcsname` mentioned, so these two user functions will be a bit easier to find by searching for the corresponding primitive names.
