### ISSUE TITLE
Documentation: some precisions about "slower processing"

### ISSUE THREAD

**Issue by jlaurens** [latex3/latex3#1340]
In section 5.5, the `\exp_args:Nnc` documentation reads `These functions need slower processing.`

1. Does it mean "These functions are slower." ?
2. slower than what exactly ?
3. Does it refer to the end of section 5.3?

The end of section 5.3 is rather complicated to catch.
Here are comment and remarks.

1. The "two flavors" information is ambiguous and not very interesting without more details
2. Does "Arguments that might need expansion" mean "anything but a raw string" ?
3. What is an "Arguments that consists of single tokens N, c, V, or v"?  something like`NNcVVVv` ?
4. How can argument type ordering systematically influence function optimization ?
5. Is this paragraph general or is it restricted to the documented functions?

**Comment by josephwright** [comment]
This is referring to what is in the grand scheme of things a tiny optimisation: hand-tuned versus auto-generated commands. I think we are best just dropping this in the docs: other views?

**Comment by FrankMittelbach** [comment]
On 5.5: `These functions need slower processing.`

I would just drop it, because it doesn't help at this point. If you have `\foo:nn` and you need variants that expand both arguments, then this takes more time than having `\bar:Nn` or `\baz::NN` that need variants. But if you base function is `\foo:nn` and not `\foo:NN` there is nothing you can do about that.

On end of section 5.3

1. I would change that to something like  "... because the speed of internal functions that pre-expand the arguments of a base function depend on *what* needs doing with each argument and *where* this happens in the list of arguments:
2. @josephwright : maybe the other way around:   "Argument of the base function for which pre-expansion by a variant is not expected should come last (rationale: the pre-expansion code then doesn't have to handle them at all)". @jlaurens as to what it means it means using variants that have anything other than `N` or `n`for this argument is not expected
3. @josephwright : I know what it is meant but I think it is indeed a bit difficult to understand. I would probably split in two bullets and add a rationale.
4. @jlaurens because preexpansion is done expandably and with a macro language like TeX you then basically copy token and reprocess them over and over again, so an `nc` is slower than `cn` etc
5. This paragraph is about how a programmer though think of ordering his/her base function arguments if speed is a consideration (and certain variants are expected

@josephwright I see no reason to drop this, on the contrary (but I think a slightly bit more rationale/explanation how base function argument ordering can affect speed of processing would help --- at the moment it is more or less just a "do it that way")

**Comment by josephwright** [comment]
I've re-worked that list: see latest check-in

**Comment by muzimuzhi** [comment]
The new description (https://github.com/latex3/latex3/commit/66d321db10ce36446e1c2778c16fc9262ac0043b) seems too general. Handling unchanged `n`-type argument (before changed arguments) is slower than handling unchanged `N`-type. The latter needs only an `\exp_after:wN`, but the former has to use `\tex_expanded:D { ... \exp_not:n {#n} ...}`.

Also "should come last" seems too strong, after all kinds of `\exp_args:N<arg-spec>` are provided by `l3kernel` directly.
https://github.com/latex3/latex3/blob/863443a75fad05a39fbab933323af3cc1bd76ee4/l3kernel/l3expan.dtx#L316-L326

**Comment by josephwright** [comment]
> Also "should come last" seems too strong, after all kinds of `\exp_args:N<arg-spec>` are provided by `l3kernel` directly.

The text is specifically about the cases where optimisation is really crucial, for which I think this remains true.

**Comment by josephwright** [comment]
> The new description ([66d321d](https://github.com/latex3/latex3/commit/66d321db10ce36446e1c2778c16fc9262ac0043b)) seems too general. Handling unchanged `n`-type argument (before changed arguments) is slower than handling unchanged `N`-type. The latter needs only an `\exp_after:wN`, but the former has to use `\tex_expanded:D { ... \exp_not:n {#n} ...}`.

I'm not sure I follow: the entire point here is to say that `N`/`n` should come after modified arguments, so the fact that `N` can be skpped over faster than `n` (exactly mech varies) isn't relevant.

**Comment by FrankMittelbach** [comment]
> How about something like
> 
>     * modified arguments should come as early as possible and `c`-type should come first;
> 
>     * when needed, unchanged `N`-type args can appear before modified ones, with a small performance hit;
> 
>     * if really needed unchanged `n`-type args can appear before modified ones, with a relative larger performance hit.

But they all can come always in any order (this is about how to make them work faster), So if going in this direction, ie explaining what costs what, I wouldn't say "when needed" but just explain the costs, e.g.

  - for fastest processing any c-type arguments should come first followed by all other modified arguments;
  - unchanged N-type args that appear before modified ones have a small performance hit;
  - unchanged n-type args that appear before modified ones have a relative large performance hit.

While any order is possible (and normally not important if the functions are only called occasionally) the information above gives you some guidelines how to order the arguments of a base function to make the important variants faster.

---
Of course if you use both \foo:cn and \foo:nc then you have no chance to make it always equally fast unles you duplicate the code. -- there could be some footnote to this effect perhaps

**Comment by josephwright** [comment]
> A rule too strict is a rule more often broken, hence has less practical guidance. Following current description a optimization fanatic may wonder why `\tl_set:Nn` instead of `\tl_set:nN`, but often readability and convention win and for crucial cases `w`-type is used with delimited arguments.

The text isn't talking about base functions, rather manipulation of arguments. Also, we are talking about cases where the order is 'free': something like `\tl_set:Nn` has to have the token list first.

**Comment by josephwright** [comment]
@FrankMittelbach  I've added your text - hopefully this is clear enough

**Comment by car222222** [comment]
I tend to agree that this text is relevant to the setting up of the base function.

**Comment by josephwright** [comment]
I think we've addressed this ...
