### ISSUE TITLE
Passing \c_novalue_tl to a command, and testing for it

### ISSUE THREAD

**Issue by ysalmon** [latex3/latex3#1402]
I defined a versatile internal function, here simplified to :
```
\cs_new:Nn \example:nnnn {
  \tl_if_novalue:nTF {#1} {T} {F}
  % etc.
}
```

I have a more abstract layer of functions, of which some have to supply NoValue to ``\example`` :
```
\cs_new:Nn \second: {
  \example:nnnn {\c_novalue_tl} {things} {that} {depend}
}
```

But this does not work, as I get a F instead of a T.

More simply, ``\tl_if_novalue:nTF{\c_novalue_tl}{T}{F}`` gives an F.

I could not find a way to effectively pass the NoValue to a command, as if an optional argument in a user command had not been supplied.

The use case is typesetting an exercise sheet : questions can have a title, so the user command has a ``o`` argument ; tests cannot, so I do not want to have a ``o`` argument in the user command ; but at some point, this boils down to a generic function that typesets a Q or a T in the margin, and a title if there is one. I need my user command for tests to always give a NoValue as title to the internal function.

**Comment by muzimuzhi** [comment]
> More simply, `\tl_if_novalue:nTF{\c_novalue_tl}{T}{F}` gives an F.

You need `\exp_args:No \tl_if_novalue:nTF {\c_novalue_tl} {T} {F}`. That is, feed the one-step expansion result of `\c_novalue_tl` to `\tl_if_novalue:nTF`.

**Comment by ysalmon** [comment]
Thank you, I got to what I wanted with like ``\exp_args:No\tl_if_novalue:nF {#1} {\refstepcounter{#1}}`` and seems to work in all my cases, because expanding ``#1`` here is not a problem.

I am not closing this however, since the behaviour of expl3 seems counter-intuitive at least, and is not documented afaik.

**Comment by Skillmon** [comment]
@ysalmon the wording might be misleading a bit, but it is documented for `\tl_if_novalue:nTF`:

> Tests if the ⟨*`token list`*⟩ is exactly equal to the special `\c_novalue_tl` marker.

doesn't mean that the ⟨*`token list`*⟩ contains the `\c_novalue_tl` marker, but is equal in the sense that if you do `\tl_set:Nn \l_tmpa_tl {#1}` the result then tests true with `\tl_if_eq:NNTF` to `\c_novalue_tl`. But I agree, the wording might be improved here, though I'm not sure how exactly.

**Comment by ysalmon** [comment]
I am not sure I understand. I infer from (what I understand from) expl3 naming convention that ``\c_novalue_tl`` is a token list, and from usual conventions that it should be equal to itself, at least when compared with its dedicated operator.

I see this is some special kind of non-value, like ``NULL`` in SQL, that has to be managed with a special ``IS NULL`` operator because ``NULL = NULL`` and ``NULL <> NULL`` are both ``NULL`` and therefore are not true, but we do have ``NULL IS NULL`` to be true.

**Comment by FrankMittelbach** [comment]
I think we could make that clearer or rather easier to understand. Maybe something like

> Tests if the `<token list>` contains exctly the same tokens as stored in `\c_novalue_tl`. This means that 
`\exp_args:No \tl_if_novalue:nTF { \c_novalue_tl }` would execute the T branch but something like `\tl_if_novalue:nTF { \c_novalue_tl }` would execute the F branch  (because the content of `\c_novalue_tl` is not equal to `\c_novalue_tl`, i.e., it is not a quark).

I would really like understood why that constant is passed around as it is (i.e., what the use case is), because in my opinion it shouldn't (which also should be documented if it isn't).  

`\tl_if_novalue:nTF` is there as an interface to handle "no values" generated from document command level parsing and that makes sure that the content is passed and not the token (or it should in all cases). So if @ysalmon is definining his own high-level commands that may generate a "no value" he should perhaps ensure that `\c_novalue_tl` is expanded at that point.

**Comment by ysalmon** [comment]
A more detailed explanation of the use case is the following :
```tex
\cs_new:Nn \lowlevel_typesetting_function:nnn {
  % #1 is an optional counter to increment (question number)
  % #2 is the command to typeset the question number (or what takes its place, like the word "Solution")
  % #3 is an optional title : we will need to know if there is actually a title, hence \tl_if_novalue
  % etc.
}

\NewDocumentEnvironment{question}{o}{
\lowlevel_typesetting_function:nnn
                     {question} % counter name
                     {\whatever} % actual function typesets \arabic{question}
                     {#1} % #1 will be NoValue is user gave no title, or the title
}{}

\NewDocumentEnvironment{test}{} {
\lowlevel_typesetting_function:nnn
                    {\c_novalue_tl}  % tests are not numbered
                    {\JustPrintTestHere}
                    {\c_novalue_tl}  % tests cannot have a title, and the environment does not have an arg for it
}
{}
```

Granted, in the case of the counter name (``#1``) I could just use something else than NoValue to say if there is a counter or not ; but for the title (``#3``), I really would like to avoid a supplementary translation between the NoValue that I get from the user not giving a title in a question env to something else that I will be able to explicitly use in the test env.


-----

On a more "theoretical" / programming approach, it would be bizarre if expl3 had a value on the semantic plane (the NoValue), but not a literal constant to denote it.

In lua, iirc, arguments that are "missing" in a function call are just ``nil``, and that is the same ``nil`` value that you get when writing ``nil`` in your code.

In OCaml, an optional parameter of type ``'a`` is just syntactic sugar for an value of type ``'a option``, and it is perfectly doable, when calling an auxiliary function, to explicitly give it ``None``, and it is sometimes clearer in complex situation because it says "yes, here we do want the behaviour of no-argument-given for that parameter".

**Comment by FrankMittelbach** [comment]
> I am not sure I understand. I infer from (what I understand from) expl3 naming convention that `\c_novalue_tl` is a token list, and from usual conventions that it should be equal to itself, at least when compared with its dedicated operator.
> 
> I see this is some special kind of non-value, like `NULL` in SQL, that has to be managed with a special `IS NULL` operator because `NULL = NULL` and `NULL <> NULL` are both `NULL` and therefore are not true, but we do have `NULL IS NULL` to be true.

Token lists are neverly ever equal to themselves, that is only true for "quarks" not for general token lists or constants of token lists. The only way to define a token list to be equal to itself in TeX would be
```
\def\foo{\foo}
```
with that definition
```
\expandafter\ifx\foo \foo
```
would be true (and this is basically how quarks are defined). That makes testing quarks really fast and simple, but the problem with quarks is that if they ever escape and end up being typeset they generate an endless tight loop, because`\foo` is expanding into `\foo` expanding into ...

For the xparse interface we have therefore not used a quark to be returned as a no value indicator because it would most likely end up in one or the other situation (with badly defined `\NewDocumentCommand` that doesn't test its output for "no value" in all situations in precisely that). We use therefore quarks only if we have 100% control over where it ends up.
Instead `\c_novalue_tl` contains a string that will typeset `-No Value-` but consists of tokens that you can't accidentally generate as a user.

**Comment by FrankMittelbach** [comment]
> On a more "theoretical" / programming approach, it would be bizarre if expl3 had a value on the semantic plane (the NoValue), but not a literal constant to denote it.

as I tried to explain expl3 has a "no value" concept but you can't name the  literal and store it in a tl constant. Or rather you can (as we do) but it isn't equal to itself and you have to use the content of the constant in the code 

> In lua, iirc, arguments that are "missing" in a function call are just `nil`, and that is the same `nil` value that you get when writing `nil` in your code.

yes and so do other prog languages, but TeX doesn't have a concept of "nil" or something similar other than what I explained as being called "quarks". And since TeX doesn't haven't it, we can't make it appear in expl3 except with something like quarks and its dangers (which nil doesn't have in lua).

Thus what you need to do in your use case is something like this:
```
\NewDocumentEnvironment{test}{} {
\lowlevel_typesetting_function:ono
                    {\c_novalue_tl}  % tests are not numbered
                    {\JustPrintTestHere}
                    {\c_novalue_tl}  % tests cannot have a title, and the environment does not have an arg for it
}
{}
\cs_generate_variant:Nn \lowlevel_typesetting_function:nnn  {ono}
```
if you want to pass the content of `\c_novalue_tl` into the argument.

**Comment by davidcarlisle** [comment]
```
\NewDocumentEnvironment{question}{o}{
\lowlevel_typesetting_function:nnn
                     {question} % counter name
                     {\whatever} % actual function typesets \arabic{question}
                     {#1} 
```
I would say this is mixing levels and the cause of the problem


The document level function has optional values so it makes sense to test for `novalue` in the case the option is omitted,

The L3 level functions do not have optional arguments and so should not be testing for `novalue`

A more idiomatic use would be

```
\NewDocumentEnvironment{question}{o}{
\tl_if_novalue:nTF{#1}
{
\lowlevel_typesetting_function:nn % two arg form for default case
                     {question} % counter name
                     {\whatever} % actual function typesets \arabic{question}
}
{
\lowlevel_typesetting_function:nnn % three arg form 
                     {question} % counter name
                     {\whatever} % actual function typesets \arabic{question}
                     {#1} 
}
```

Or perhaps always call `:nnn ` but with a suitable default argument in the first branch. The point is to handle the no-argument test at the level that has optional arguments.

**Comment by ysalmon** [comment]
> I would say this is mixing levels and the cause of the problem
> 
> The document level function has optional values so it makes sense to test for `novalue` in the case the option is omitted,
> 
> The L3 level functions do not have optional arguments and so should not be testing for `novalue`

I understand the difference in levels but I find it should not entail that — on the contrary, even. At the document level, there is a parsing convenience that allow for syntactically optional arguments ; in my L3 function there are mandatory arguments for which `novalue` is a semantically admissible value — the syntactic sugar of the document level has been removed.

But I understand implementing this is trickier in tex !

> 
> A more idiomatic use would be

This is exactly the kind of things I want to avoid.

I think @FrankMittelbach's `ono` suggestion is the way to go : if I understand correctly, it performs the required expansion of `\c_novalue_tl`, which eschew the need for ``\exp_arg:No`` in the L3 function ; and there are not so many variants to generate.

Thanks everybody for the discussion. I am again leaving this open for now if you want to follow up on maybe taking parts of the ideas into the documentation.

**Comment by muzimuzhi** [comment]
> Token lists are neverly ever equal to themselves, that is only true for "quarks" not for general token lists or constants of token lists.
> _<sub>https://github.com/latex3/latex3/issues/1402#issuecomment-1873467643</sub>_

> The part about token list equality being irreflexive is a big novelty for me — if it is not mentioned in the doc, maybe it should too ; reflexivity is a very common and strong expectation for something called an equality.
> _<sub>https://github.com/latex3/latex3/issues/1402#issuecomment-1873478580</sub>_

@ysalmon Tested with `\tl_if_eq:NNTF` or the primitive `\ifx`, a token list variable _is_ always equal to itself. Thus `\tl_if_eq:NNTF \l_mymod_tl \l_mymod_tl` is always logically `true`.

What @FrankMittelbach meant in https://github.com/latex3/latex3/issues/1402#issuecomment-1873467643 is, normally, a token list variable is not equal to the _value_ of itself, hence `\exp_args:NNo \tl_if_eq:NnTF \l_mymod_tl { \l_mymod_tl }` is usually logically `false`, unless `\l_mymod_tl` is defined like a l3quark variable (`\tl_set:Nn \l_mymod_tl { \l_mymod_tl }`).

**Comment by FrankMittelbach** [comment]
> @ysalmon Tested with `\tl_if_eq:NNTF` or the primitive `\ifx`, a token list variable _is_ always equal to itself. Thus `\tl_if_eq:NNTF \l_mymod_tl \l_mymod_tl` is always logically `true`.
> 
> What @FrankMittelbach meant in [#1402 (comment)](https://github.com/latex3/latex3/issues/1402#issuecomment-1873467643) is, normally, a token list variable is not equal to the _content_ (or, value) of itself, hence `\exp_args:NNo \tl_if_eq:NnTF \l_mymod_tl { \l_mymod_tl }` is usually logically `false`, unless `\l_mymod_tl` is defined like a l3quark variable (`\tl_set:Nn \l_mymod_tl { \l_mymod_tl }`).

yes I expressed that badly saying they are never equal to themselves. As @muzimuzhi  explained they are, if tested with `\tl_if_eq:NNTF`, but this only compares the content of the two token lists. Thus it also returns true for two tls that have different names but are otherwise identical.

**Comment by josephwright** [comment]
Are we sorted here?

**Comment by ysalmon** [comment]
Maybe. I read the new version of the doc, and it does hint that there is something to be aware of.

However, even though the documentation is not a tutorial, I think it might be useful to mention FrankMittelbach's https://github.com/latex3/latex3/issues/1402#issuecomment-1873473823 suggestion for how to make things work when explicitly passing ``\c_novalue_tl`` to a function — which I really think is the normal idea to have for an L3 programmer who has no experience in pre-L3 tinkering with ``\ifx``, ``\expandafter``, ``\@ifnextchar`` and the habit, described in David Carlisle's https://github.com/latex3/latex3/issues/1402#issuecomment-1873474844, of having multiple partial commands to deal with a variable number of arguments.

As it is, the documentation uses an example which does not correspond to a practical use case : it takes some prior mastering of the concepts at hand to infer from that example what you should do in the abovementionned case. I mean : having the present discussion in mind, I understand, but one week ago that would have been a bit cryptic to me.

**Comment by muzimuzhi** [comment]
> ... how to make things work when explicitly passing `\c_novalue_tl` to a function

@ysalmon I think in most general use cases, using `\c_novalue_tl` as a marker for special value is less recommended than using the value of `\c_novalue_tl`.

That's because `\c_novalue_tl` is more likely to be the actual user input, than its value (`-`<sub>11</sub>`NoValue` `-`<sub>12</sub>), which is constructed using special catcodes of `-`.

Also in general cases checking if an `n`-type argument consists of `\c_novalue_tl` solely is a bit slow, since for example we cannot blindly `o`-expand an `n`-type argument.

```tex
\ExplSyntaxOn
\prg_new_conditional:Npnn \tl_if_single_novalue:n #1 { p , T , F , TF }
  {
    \bool_lazy_and:nnTF
      { \tl_if_single_p:n {#1} }
      { \tl_if_head_eq_meaning_p:nN {#1} \c_novalue_tl }
      \prg_return_true:
      \prg_return_false:
  }

\tl_if_single_novalue:nTF {\c_novalue_tl} {} \ERROR

\tl_if_single_novalue:nTF {}              \ERROR {}
\tl_if_single_novalue:nTF {abc}           \ERROR {}
\tl_if_single_novalue:nTF {-NoValue-}     \ERROR {}
\exp_args:No \tl_if_single_novalue:nTF {\c_novalue_tl} \ERROR {}
\ExplSyntaxOff
```

Maybe we need some place to record such explanation and recommended practices in expl3 programming.
