### ISSUE TITLE
Forms of `<fp expr>` that `\fp_compare:nTF` accepts

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/latex3#1424]
`\fp_compare:nTF` actually accepts any valid floating point expression (and executes `<true code>` if the expression evaluates to 0 or tuple), but currently only the form `<fp expr> (<relation> <fp expr>)+` is documented.

https://github.com/latex3/latex3/blob/a413a695aa8425292eecd7fc72f68c09d4a2470b/l3kernel/l3fp-logic.dtx#L115-L139

Perhaps its documentation can be relaxed?

**Comment by blefloch** [comment]
Actually your sentence seems to be not quite right: the test gives false when the expression evaluates to `0` or `-0`, and true when the expression gives anything else (including tuples).  I think it really ought to produce an error when it is not given a comparison, but at the time I didn't see how to implement that efficiently.

What do others think?

**Comment by jasperhabicht** [comment]
It should at least issue a warning or it should be documented. But actually, I would vote for an error in favor of consitency: `\int_compare:nTF` throws the short and sweet error ```I was expecting to see `<', `=', or `>'. Didn't.```.

**Comment by FrankMittelbach** [comment]
> What do others think?

I can't see how you can make it an error in an efficient way (not if you only have `#1`) and doing it with a lot of overhead doesn't seem to me a good idea. So I would vote for documentation only unless somebody sees a really fast way.

**Comment by blefloch** [comment]
I think it is possible by using the table of precedences
- 16: Function calls.
- 13/14: Binary `**` and `^` (right to left).
- 12: Unary `+`, `-`, `!` (right to left).
- 11: Juxtaposition (implicit `*`) with no parenthesis.
- 10: Binary `*` and `/`.
- 9: Binary `+` and `-`.
- 7: Comparisons.
- 6: Logical and, denoted by `&&`.
- 5: Logical or, denoted by `||`.
- 4: Ternary operator `?:`, piece `?`.
- 3: Ternary operator `?:`, piece `:`.
- 2: Commas.
- 1: Place where a comma is allowed and generates a tuple.
- 0: Start and end of the expression.
Instead of just calling the basic parsing routine that begins with a "start of expression marker" of precedence 0, hence that stops only at the end of the expression, we should be able to call a variant that begins as if there was just an `&&`, so that it will stop parsing once it hits another `&&` or lower-precedence thing.  Then produce an error if indeed the expression is not finished.

My main worry is that this change may break some code.  It would have to be possible to roll-back, or turned on only when debugging is active, maybe, for some time?

**Comment by josephwright** [comment]
Personally, I don't feel a change is a great plan: we are talking about what is documented, which is clear, and other behaviour is formally undefined. Making a change to pick up just that with the risk to other usage seems not a great idea. Perhaps in debugging mode a change would be OK: that would be a sensible balance of risk.

**Comment by josephwright** [comment]
No further input - I'm going to close.
