### ISSUE TITLE
Regression that we can't understand with writing files with aux_ dir

### ISSUE THREAD

**Issue by tobiasBora** [latex3/latex3#1570]
I hope it is the proper place to report this bug.

A user reported a bug in my library https://github.com/leo-colisson/robust-externalize/issues/46 but after trying to make it reproducible (including with a nix derivation), we are starting to wonder if the issue is not a regression in texlive 2024 since with exactly the same MWE with texlive 2023 the issue is not present.

Long story short, it seems that it is now not possible to write in a folder after setting aux_dir:
```
I can't write on file `robustExternalize/robExt-8ADBC0F9196E3986903555FECC5EFF44.deps'.
```
A MWE can be found in
https://github.com/leo-colisson/robust-externalize/issues/46#issuecomment-2122574191 
This is not so minimal yet as it uses my library but since I can''t reproduce myself as I can't install a more recent LaTeX (not packaged with nix yet) it's harder for me to obtain a better one. Hopefully it will ring a bell to someone!

**Comment by FrankMittelbach** [comment]
> I hope it is the proper place to report this bug.

Unfortunately it isn't. To which files LaTeX can write to is determined by the TeX engine. LaTeX has no control over this.

TeX has for a very long time already refused to write "dot" files, though there has been an explicit exception because the LaTeX distribution generated the file `.tex`. We have been recently asked to stop generating this  file in order to be able to tighten the rules. So perhaps the tightening als resulted in disallowing to write into "dot" directories and as far as I can see this is whqt your MWE is trying to do, i.e. write to `.aux_dir`.

So I guess you have to raise that on the TeXLive list.
