### ISSUE TITLE
environ's \NewEnviron-like interface for xparse

### ISSUE THREAD

**Issue by Evpok** [latex3/latex3#259]
It would be nice to have a environment definition similar to `\NewEnviron` that grabs the environment content. See for an example of use case http://tex.stackexchange.com/q/172398/8547.

**Comment by wspr** [comment]
I'm in two minds about this. The good thing about regular environments (obviously) is that catcodes and so on are not frozen inside environments, particularly allowing content that involves verbatim material and so on. Environ came from code in amsmath, where such things are not as important. I've been a little uneasy with the way that use of `environ` has propagated. Also, the syntax in [newenviron](https://www.ctan.org/tex-archive/macros/latex/contrib/newenviron?lang=en) is better than mine. (I *wish* more people would just approach package authors to update their code, rather than promulgate more and more package variants.)

OTOH, if we're talking about xparse (as we have in the past) as a fairly generic definer-of-LaTeX-ecosystem constructions, then incorporating this is probably a good idea. (And then I can update environ to be a thin wrapper around xparse. Actually I probably wouldn't do that `:)`)

**Comment by wspr** [comment]
Ping! We would like to revisit this.

**Comment by josephwright** [comment]
This is addressed in https://github.com/latex3/latex3/tree/xparse, and likely to get merged very shortly into the main tree (for TL'19).
