### ISSUE TITLE
l3build.lua save --all

### ISSUE THREAD

**Issue by wspr** [latex3/latex3#269]
(Non-urgent but wanted to log somewhere.)

It's not uncommon to want to save new .tlg files for all tests without one. One example is of course when writing a bunch of new tests, but another is when something changes in the code that unexpectedly and harmlessly changes the log output in a minor way. (And you delete all the .tlgs as necessary.) I think Bruno also discussed another use case that eludes me at present.

Something like `save --all` would be a good way to do this I think.

**Comment by FrankMittelbach** [comment]
Am 11.09.15 um 01:23 schrieb Will Robertson:
> It's not uncommon to want to save new .tlg files for all tests without 
> one. One example is of course when writing a bunch of new tests, but 
> another is when something changes in the code that unexpectedly and 
> harmlessly changes the log output in a minor way. (And you delete all 
> the .tlgs as necessary.) I think Bruno also discussed another use case 
> that eludes me at present.
not sure I see the big value in this. By default the hope is that one 
tlg will suffice. If this is not case then

texlua check foo

will tell you that, say, for luatex that assumption doesn't hold. In 
that case one would verify that particular diff and if necessary 
generate the additional tlg for luatex.

Only in the case several engines fail something like save --all would 
gain you  little bit of time as one would avoid resolving dependencies 
several times. However, I  do see the danger that we end up with a lot 
of spurious tlgs that are actually not different because we forgot to 
delete unnecessary tlgs.

More useful in my opinion would be something like

texlua save -e machine1,machine2,... foo

to explicitly set the engines for which you want to generate tlgs rather 
than generating all and expect people to delete some of them afterwards 
(not checked but this may already be possible (knowing Joseph))

of course one other possibility is that "save --all" will generate

  - the default tlg
  - all other machine tlgs (and drops them immediately if they are 
identical to the default one)

**Comment by josephwright** [comment]
> More useful in my opinion would be something like
> ```
> texlua save -e machine1,machine2,... foo
> ```

This already works ;-) I'm using
```
texlua build.lua save  -e pdftex,xetex,luatex,ptex,uptex m3expl001 m3expl003
```
quite a bit!

The way we could set up `save --all` is to run all of the tests then to copy all standard engine `.tlg` files and then all other `.tlg` files that are different to the standard ones. This is a bit of a pain (I'll need to look at the way `check` and `save` link together), but it is doable.

**Comment by wspr** [comment]
Some sensible thoughts. What about a simplified use case:

1. `build check`
2. Some diffs generated
3. Diffs all manually checked for being redundant changes
4. `build save --rebuild`

This would take all tests for which diffs existed and rebuild the tlg for
each (being engine-specific if necessary).

**Comment by josephwright** [comment]
We've discussed on the team list: I think overall the decision is against the idea.
