### ISSUE TITLE
Add the possibility for shell-escaping

### ISSUE THREAD

**Issue by hmenke** [latex3/latex3#288]
There is `\c_log_iow` and `\c_term_iow`.  Please add `\c_shell_iow`.

```
\tex_chardef:D \c_eighteen = 18 ~
\cs_new_eq:NN \c_shell_iow \c_eighteen
```

**Comment by josephwright** [comment]
System calls don't really belong in the file IO module: the link is historical rather than anything else. At the same time, `\write18` is about to be dropped by LuaTeX so really this is not the best long-term plan. What would certainly be sensible is to add something to the `sys` module for this type of thing. We really want a proper interface so it will need a little thought.
