### ISSUE TITLE
xparse edge case

### ISSUE THREAD

**Issue by latex3** [latex3/latex3#3]
Here's an example where an optional `o` argument followed by an optional `g` argument aren't registered correctly; things work if the `g` argument is placed on the end, but then you get possible undesirable space-not-ignoring. I can't remember the internals of xparse enough to know if something like `{mogm}` is even intended to be valid syntax, though.

<pre>
\documentclass{article}
\usepackage{xparse}
\begin{document}
\DeclareDocumentCommand\foo{mmogm}{[#1] / [#2] / [#3] / [#4] / [#5]}
(\foo{first} {2nd} {last})\par
(\foo{first} {2nd} [old] {last})\par
(\foo{first} {2nd} {new} {last})\par
(\foo{first} {2nd} [old] {new} {last})\par

\bigskip
\RenewDocumentCommand\foo{mmgom}{[#1] / [#2] / [#3] / [#4] / [#5]}
(\foo{first} {2nd} {last})\par
(\foo{first} {2nd} [old] {last})\par
(\foo{first} {2nd} {new} {last})\par
(\foo{first} {2nd} {new} [old] {last})\par
\end{document}
</pre>

(Issue by Will, written while logged into the wrong account.)

**Comment by blefloch** [comment]
I've got some code (need to write some tests before I can commit; that may have to wait).  Is the following explanation clear? (I'm adding that to `xparse`'s doc.)

> Arguments of type `g` or `G` may not be followed by `m` (or `l`),
because a braced group would then always be recognized as the
optional argument, even if there is no second braced group. Use
`m g` instead of `g m`. For the same reason, other optional
arguments (`o`, `d`, `O`, `D`, `s`, `t`, `k` or `K`) may not be
followed by a required argument (`r` or `R`) with the same first
token.

Is that the behaviour we want?  One drawback is that `d[] s r[]` is allowed, even though a command with this signature could only be used as `\foo[][]` or `\foo[]*[]` or `\foo*[]` but not `\foo[]` alone.  In other words, despite its appearance the signature forces the presence of either the optional argument or the star.  There may also be some oddities if people start trying to use spaces as delimiters, but I don't care.
