### ISSUE TITLE
Remove \scrollmode from regression-test.tex

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#305]
The `l3build` test harness runs `pdftex` (or other engines) with the flag `-interaction=batchmode`, but this is cancelled by the call to `\scrollmode` in `regression-test.tex` (generated from `l3build.dtx`).

Scroll mode has the drawback that if a testfile is missing `\END` (or other macro calling the primitive `\end`) then TeX hangs indefinitely.  At least when running the tests in a bash terminal, the standard shortcuts (`^C`, `^D`) do not kill the appropriate process and one must explicitly `pkill texlua`.

I suggest removing `\scrollmode` from `regression-test.tex`.  For an unknown-to-me reason this affects spacing when files are loaded, so many of the `l3kernel` test logs would have to change.

**Comment by FrankMittelbach** [comment]
Am 14.07.16 um 11:13 schrieb Bruno Le Floch:
> For an unknown-to-me reason this affects spacing when files are loaded,
> so many of the |l3kernel| test logs would have to change.

you mean spaces in the logs (like extra lines or after file names etc) 
or what?

**Comment by blefloch** [comment]
Yes, sorry that wasn't clear.

**Comment by blefloch** [comment]
No objection, then?  I'll change.

**Comment by FrankMittelbach** [comment]
Am 19.08.16 um 21:33 schrieb Bruno Le Floch:
> No objection, then? I'll change.

no objection, go ahead

**Comment by josephwright** [comment]
There's some odd stuff going on here with spaces. Most of that is probably OK though I'd like to understand it. However, with LuaTeX we end up messing up normalisation with this change. I'm going to see if I can pin down the cause and fix, or may revert whilst I get the issue addressed at the engine level (if necessary).

**Comment by josephwright** [comment]
I've backed out and reopened here. There are various minor oddities I'd like to understand in terms of spaces, one actual issue in terms of normalisation and a conceptual question:

- Changing the mode here removes some spaces before included files in the log (see `m3expl001` for example) and spaces within some messages (see _e.g._ `m3token004`): at the very least I'd like to know why.
- That or something similar changes how the `pdftex.map` line and the following `.aux` one wrap in LuaTeX compared to other engines, which messes up normalisation. This might be an engine issue, and I'm not sure it will be readily fixed.
-  Using `\batchmode` means we no longer get any 'live' output from TeX runs which tests are run individually rather than _en masse_. We deliberately set things up to be 'verbose' when doing one-off tests, as it helps tracking down issues. Do we want to change that? (If so there are some simplifications to be made inside `l3build` too.)

**Comment by josephwright** [comment]
@blefloch Is the solution I've ended up with OK?
