### ISSUE TITLE
Adding `\fp_step_inline:nnnn` and `\fp_step_function:nnnN`

### ISSUE THREAD

**Issue by eg9** [latex3/latex3#319]
I believe this would be a useful addition. The *caveat* would be that the number of steps might be off by one depending on rounding effects due to floating point calculations.

To be honest, I found it useful as part of a set of macros to replace/extend `\foreach` of PGF.

**Comment by blefloch** [comment]
We forgot `\fp_step_variable:nnnNn`, in analogy to `\int_step_variable:nnnNn`.  When fixing that we should check we didn't miss any other `_variable` analogue of `_inline` maps: since I never use them I may have forgotten them.

**Comment by blefloch** [comment]
We didn't miss any.  More precisely there is no `\prop_map_variable` but that would require two variables (one for the key and one for the value), which looks messy, and there is no `\ior_map_variable` or `\ior_str_map_variable` but that's probably ok since the `_function` versions also don't exist (that's simply because of expandability).
