### ISSUE TITLE
xparse d-type argument with non-character token

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#368]
```
\RequirePackage{xparse}
\DeclareDocumentCommand{\foo}{d\[\]}{\typeout{#1}}
\foo\[abc\]
```
types out `[abc`.  There is a built-in assumption somewhere that delimiters are single characters.  Probably `xparse` should complain about the attempt to use another token. See also #367.

**Comment by PhelypeOleinik** [comment]
(from here: https://tex.stackexchange.com/q/529859/134574)

Commit e25d9573 added an option to redirect of _all_ `xparse` warnings to `none`,
and then commit 01cfc47a made that option the default. As such, these don't raise
warnings anymore:
```latex
\NewDocumentCommand{\testA}{d[]r[]}{ }
\NewDocumentCommand{\testB}{d\{\}}{ }
```

The `warning` line here:
https://github.com/latex3/latex3/blob/2091d3569efd05fbdf18289f9ea10ea8cfd818a6/l3packages/xparse/xparse.dtx#L4898-L4899
should probably be removed, as declarations are only logged as `info`, so the
redirection of `info`s should be enough.

Also, since the `d\{\}` case produces wrong output, should it be an error?

**Comment by josephwright** [comment]
Yeah, probably over-zealos: I think it was originally as we did have some warnings

**Comment by PhelypeOleinik** [comment]
Yeah, the warnings were there (removed here: e48d71f0). I returned the warnings (for the record: 9dace07c).

**Comment by blefloch** [comment]
If something produces wrong output then yes it should be turned to an
error.  But maybe we can simply support the case of such delimiters?

**Comment by eg9** [comment]
> On 25 Feb 2020, at 07:18 , Bruno Le Floch <notifications@github.com> wrote:
> 
> If something produces wrong output then yes it should be turned to an
> error. But maybe we can simply support the case of such delimiters?

If it’s possible to add support, maybe we should.

On the other hand, there are already cases of misuse of the
argument types of xparse. Do we want to add to the mess?

Ciao
Enrico

**Comment by PhelypeOleinik** [comment]
> If something produces wrong output then yes it should be turned to an
> error.  But maybe we can simply support the case of such delimiters?

Agreed! I just didn't do that because I wanted more opinions... Suddenly
changing a warning into an error will make some users unhappy

Though supporting that seems rather easy (by that I mean: most of the
code already does). The definition of `\@@_grab_D_call:Nw` tests if the
open-delimiter is a character (12), and if it's not (the case of tokens
like `\{` and `\lvert`), it assumes it is a character of some other catcode
and hits the token with `\string` (to distinguish from other identical
tokens, to keep track of nested delimiters). Adding a test for a `cs`
token in that definition makes some simple cases work:
```latex
\documentclass[12pt]{standalone}
\usepackage{xparse}
\ExplSyntaxOn
\cs_gset_protected_nopar:Npn \__xparse_grab_D_call:Nw #1
  {
    \token_if_eq_catcode:NNTF + #1
      {
        \exp_after:wN \exp_after:wN \exp_after:wN
          \l__xparse_fn_tl \char_generate:nn { `#1 } { 11 }
      }
      {
        \token_if_cs:NTF #1
          {
            \l__xparse_fn_tl + % <- FIXME
          }
          {
            \exp_after:wN \l__xparse_fn_tl
            \token_to_str:N #1
          }
      }
  }
\ExplSyntaxOff
\NewDocumentCommand{\testA}{d\{\}}{ \IfNoValueTF{#1}{error}{(#1)} }
\NewDocumentCommand{\testB}{d\|\|}{ \IfNoValueTF{#1}{error}{(#1)} }
\NewDocumentCommand{\testC}{d\langle\rangle}{ \IfNoValueTF{#1}{error}{(#1)} }
\begin{document}
$ \testA\{X\} \testB\|X\| \testC\langle X\rangle $
\end{document}
```

I'd need to do further tests with that code, remove the `not-single-char`
warning, and fix the `FIXME` line so that the correct token appears in
`! Runaway argument` errors. But that seems to be the basics, so I think
it's possible to support that if we want...

What do you think?

**Comment by blefloch** [comment]
> I'd need to do further tests with that code, remove the |not-single-char|
> warning, and fix the |FIXME| line so that the correct token appears in
> |! Runaway argument| errors. But that seems to be the basics, so I think
> it's possible to support that if we want...

In your FIXME line we cannot get exactly the right token (because it
would interfere with argument grabbers), but it's probably enough to
have \csname \cs_to_str:N #1 ~ \endcsname or similar.

**Comment by PhelypeOleinik** [comment]
I opened a new branch ([`cs-delimited-args`](https://github.com/latex3/latex3/tree/cs-delimited-args))
with the implementation of this arbitrary-tokens-as-delimiters feature.

Basically, what changed:
 - I added Bruno's suggestion for the runaway message (e2a9003c);
 - In the code for peeking ahead I added a check whether the token
  defined as a delimiter is the same as the token found while scanning,
  so that different tokens with the same meaning will not be used as
  delimiter; only if the tokens are exactly the same (69e6f7ee) (this
  kind-of solves #367 too);

If someone could take a look before merging this :-)
