### ISSUE TITLE
\dim_to_decimal_in_unit:nn

### ISSUE THREAD

**Issue by amoschou** [latex3/latex3#376]
When **\dimexpr** is used many times in **dim_to_decimal_in_unit:nn**, results are not really predictable:

```
\documentclass{article}

\usepackage{xparse}

\ExplSyntaxOn
\DeclareExpandableDocumentCommand{\RoundToPt}{m}
 {
  \fp_eval:n { round ( \dim_to_decimal_in_unit:nn { #1 } { 1pt }, 0 ) }
 }
\ExplSyntaxOff

\begin{document}

\def\m{1.25}

\the\dimexpr\m\dimexpr\m\dimexpr\m\dimexpr\m\dimexpr 25pt: % 61.03516 pt
\RoundToPt{\m\dimexpr\m\dimexpr\m\dimexpr\m\dimexpr 25pt}, % 58
\RoundToPt{\m\dimexpr\m\dimexpr\m\dimexpr\m\dimexpr 25pt\relax}, % 60
\RoundToPt{\m\dimexpr\m\dimexpr\m\dimexpr\m\dimexpr 25pt\relax\relax}, % 61
\RoundToPt{(\m\dimexpr\m\dimexpr\m\dimexpr\m\dimexpr 25pt)} % 61

\end{document}
```

— Andrew

**Comment by blefloch** [comment]
We really discourage using `\dimexpr` directly because of its lack of termination.  None of the `expl3` interfaces have that problem.  Now presumably package writers have to deal with users using `\dimexpr` so I've made `\dim_to_decimal_in_unit:nn` more robust against such situations (by adding parentheses).  This is far from being a complete solution, for instance `---\dim_eval:n { \dimexpr 1pt }---` gives an error instead of `---1pt---`.

**Comment by amoschou** [comment]
Okay, thanks for that.
