### ISSUE TITLE
make l3doc available via texdoc

### ISSUE THREAD

**Issue by tweh** [latex3/latex3#384]
At the moment `texdoc l3doc` opens `expl3.pdf` but it would be nice to have the manual of the class available via this command. I’m not sure if this can be solved by the L3 team or if its a thing for the `texdoc` team. However as far as I see there is only `l3doc.dtx` but no `*.pdf` on CTAN.

I know that `l3doc` is kind of tacky and of course I can compile the manual from the `*.dtx` myself …

**Comment by FrankMittelbach** [comment]
We don't really think that l3doc is ready to be used generally (thus the USE AT YOUR OWN RISK note) but I don't think it would hurt if we distribute l3doc.pdf which I guess is a prereq for texdoc to be able to show something.

Maybe there is also a way to set up a local texdoc.cnf to display your compiled .pdf  without putting it into some special directory first but I wasn't able to figure out how so far

**Comment by tweh** [comment]
I know that the class in not officially stable or anything like that but the ones using it (and know how to use `textdoc`) are probably area of this. If there’s no possibility to publish the PDF manual as usal I’ll just stick to my compiled version saved on my desktop :-)

**Comment by wtsnjp** [comment]
@FrankMittelbach I'm afraid that we currently don't have easy way (I mean without modifying texdoc itself) to show documents which aren't con­tained in TeX Live.

Actually, I recently began to contribute to developing texdoc, and also I originally thought that present "alias" function is not very useful, so let me think about it. (but this might take some moments)

**Comment by wtsnjp** [comment]
Talking about current situation, are there any good reason not to provide compiled l3doc.pdf?

Since there are clear statement (with **bold text**) in the document

> It is much less stable than the main expl3 packages. Use at own risk!

so someone who have been able to reach l3doc.pdf probably know that the class is not ready to be used generally.

On the other hand, the worst case I can imagine is someone who haven't reached to the document will have a wrong impression that _l3doc is provided for general use and lacking document_.

**Comment by wtsnjp** [comment]
I didn't know but Texdoc *has* a way to find a local file which is not included in TeX Live. Texdoc searches local files under TEXMF trees specified in the kpathsea variable TEXDOCS.

As a conclusion, to access l3doc.pdf generated by yourself, you can put it somewhere under TEXMF/doc, where TEXMF is one of the paths included in the TEXDOCS list.

cf. TeX-Live/texdoc#17

**Comment by FrankMittelbach** [comment]
@wtsnjp thanks, that's good info and will help if one wants to make arbitrary docu available via texdoc.

 For the current issue I nevertheless see two (possible) tasks here

-  we should probably make l3doc available (as long as we  have a big warning on top of the documentation that it is unstable and may drastically change as it is really so far only internal for us - @wspr )
- I think we should consider changing the l3build's way of using the `install` target, so that it puts the documentation into the local tree in a way that it is seen by texdoc. After all, once one has installed something in the local tree via l3build it is picked up during compile so the texdoc docu should probably match, no?

**Comment by josephwright** [comment]
@FrankMittelbach The main reason `l3build` doesn't currently install documentation is that it would add to the time required: mainly, local installation is for testing 'stuff', or at least that's how I use it. Perhaps best would be a switch or variable to control this, e.g.
```
l3build install --include-documentation
```
or similar. I'll open an `l3build` issue.

**Comment by FrankMittelbach** [comment]
good point. I guess both approaches are viable depending on the situation. So perhaps a switch is best.
