### ISSUE TITLE
l3doc: distinguish page number and line number in index

### ISSUE THREAD

**Issue by Stone-Zeng** [latex3/latex3#389]
The index entries' number generated by `\cs` has the same appearance with macro code. The following picture is from `l3doc.pdf`.

![default](https://user-images.githubusercontent.com/18233088/29171950-e868645a-7e10-11e7-90fd-a503beb6cd50.PNG)

There is no way to distinguish the page number 28 of `\tl_map_inline:Nn` from the line numer 28 of `\tl_new:N`. Sometimes it's really confusing.

**Comment by FrankMittelbach** [comment]
@wspr  `\cs` and friends can't really appear within code lines so I guess all that is needed is really to ensure that they generate "usage" index entries (and those should come out in `\textit` by default (unless that got redefined and I haven't found the place in the well documented code :-). Hope you see what is going on there.

**Comment by wspr** [comment]
On top of this, I'd say usage in `\cs` should be differentiated to what is currently shown in italics with `\begin{function}`. I'm trying to work through the code here, but a lot of it isn't mine :)

**Comment by blefloch** [comment]
Thanks @wspr for getting this fixed :) I'm sorry, the mess is partly mine as I've added features without properly learning how indexing works.

**Comment by wspr** [comment]
@blefloch No apologies necessary after all the work you've put in to make this class file more useable! I'm also a little out of my depth when it comes to indexes. I really like the output that it generates.

**Comment by FrankMittelbach** [comment]
@wspr I'm not sure that there is much point in making `\cs` behave differently in function environment. After all the "main" function is identified by the argument to the environment (so that should get bold in the index (or "main") and any `\cs` inside  is likely just an ordinary reference. Of course, one could keep track what what is "main" within this environment and not generate any additional index entry to avoid having both bold and italic entries for the same page. But that is about all you can do in my opinion.

**Comment by wspr** [comment]
@FrankMittelbach — I've decided to leave it for now as it's a rabbit hole :)

Currently the function environment doesn't use "main" for the index entry, as "main" uses page number referencing. So we'd need (I think) to come up with another category like "usage-main" or similar.
