### ISSUE TITLE
xparse: provide global versions of all functions

### ISSUE THREAD

**Issue by EvanAad** [latex3/latex3#408]
With the exception of the three `\If...` predicates, the rest of the functions provided by the `xparse` package create objects (either functions or environments). When these object are created, they are local to the surrounding TeX group. For every one of these functions, please provide a version that creates the object globally.

**Comment by josephwright** [comment]
We've gone with the current situation based on experience with `\newcommand` and it's (broadly) deliberate: certainly we'd need a good case to change it (and it would then presumably be all-global). The model for creating document commands is they should not accidentally be declared inside a group!

**Comment by EvanAad** [comment]
One use case is given by [this](https://tex.stackexchange.com/q/357869/21685) tex.stackexchange question from 7 years ago.

Another use case would be as follows. When I write a LaTeX3 function that takes arguments, I name the parameters by assigning the raw parameters (`#1`, `#2`, etc.) to variables. Additionally, I always surround the entire function's body inside a `\group_begin: ... \group_end` pair, so that I can call other functions without risking them overwriting the values of the local parameters and variables of the calling function.

Now, sometimes it happens that I need to programmatically generate document-level commands that take optional arguments. Some aspects of these programmatically generated commands (e.g. the command's name) depend on external values. So I write a meta function that takes parameters, and based on the values of these parameters (after some pre-processing and calculations) outputs a corresponding `\NewDocumentCommand` command.

However, since the `\NewDocumentCommand` creates commands that are local to the surrounding TeX group, and since the body of the meta function is surrounded by `\group_begin: .. \group_end` as explained above, the command "disappears" when the meta function finishes executing.

**Comment by wspr** [comment]
Broadly speaking we discourage mixed use of xparse+expl3 (e.g., using expl3 expansion to generate xparse commands programmatically, etc.). But that’s not to say the feature set of xparse can’t be extended.

Personally I think that the generating functions being local is a feature. Your use case suggests that better ways of getting function definitions outside a group would be useful, rather than needing a global function.

**Comment by EvanAad** [comment]
@wspr In my opinion saying "we discourage mixed use of xparse+expl3" is an unfair argument. As long as `xparse` provides functionality that is hard to accomplish with `expl3`, its use can't be discouraged. This applies not only to `xparse` but to any other package that provides functionality that `expl3` does not.

**Comment by wspr** [comment]
@EvanAad — I mostly mean that *ideally* expl3 and xparse code shouldn't need to mix. Your issue indicates that xparse doesn't fit your needs, and we want to consider the broader picture before implementing small-scale fixes. E.g., it's possible that providing global versions of the commands isn't actually the best way to address the problem you're having.

**Comment by EvanAad** [comment]
I've noticed that the variable that is assigned the command with `\NewDocumentCommand` is embedded in the command's body. Consider, for instance, the following LaTeX2e manuscript:

```
\documentclass{article}
\usepackage{xparse}
\NewDocumentCommand \CommandA {} {Hello, world!}
\begin{document}
\texttt{\meaning\CommandA}
\end{document}
```
This typesets
```
\protected macro:->\__xparse_start_expandable:nNNNNn {}\CommandA
\CommandA  \CommandA code ?{}
```
Notice how the control-sequence `\CommandA`, which, from the user's perspective, serves as a variable to which the command is assigned, is embedded in the command's replacement text.

I think this might be the key to fulfilling my request.

Without delving into the `xparse` source code I venture a possibly misguided guess that it should be quite easy to change this so that instead of referring to the public variable `\CommandA`, the command's body will refer to a private variable, say `\__ComandA`.

Once this change is affected, it will become a simple matter to create a document command globally by first creating it locally with `\NewDocumentCommand`, and then copying it to the global scope with `\cs_new_eq:NN` or `\cs_gset_eq:NN`.

**Comment by EvanAad** [comment]
I've solved the problem by writing version of `\NewDocumentCommand` et al. that define the command globally. The code listing can be found [here](https://tex.stackexchange.com/a/396750/21685). I would appreciate it if you guys consider incorporating my code into the `xparse` package for the benefit of the community.

**Comment by wspr** [comment]
@EvanAad — I wanted to let you know we're now currently discussing internally the best way to extend the possibilities for xparse. We are cautious about introducing new functionality but it is clear that there is more needed for providing a richer set of tools.

**Comment by wspr** [comment]
This should also be linked to issue #9 (!) and both closed at the same time.

**Comment by josephwright** [comment]
@wspr  IS this a dupe? Close one and keep the other open?

**Comment by wspr** [comment]
Okay, I've closed the other. For completeness, there was a cross reference to #333 that is also somewhat relevant.

**Comment by mvastola** [comment]
I wanted to give this a :+1:  and offer my own use case for this. I am currently using the code from [this StackExchange answer](https://tex.stackexchange.com/questions/51733/global-renewcommand-equivalent-of-global-def) to provide the `\gnewcommand` and `\grenewcommand` macros.

```latex
% Macros to set up value accessors
\NewDocumentCommand\ValueAccessor{ s m G{} }{
  \expandafter\gnewcommand\csname The#2\endcsname{#3\IfBooleanF{#1}{\xspace}}
  \expandafter\NewDocumentCommand\csname #2\endcsname{ m }{
    \global\expandafter\grenewcommand\csname The#2\endcsname{##1\IfBooleanF{#1}{\xspace}}
  }
}

% Macros to selectively evaluate environments based on the setting of a macro
\newcommand\TheLocationUnderscored[0]{}
\newcommand\Location[1]{\renewcommand\TheLocationUnderscored[0]{#1}}
\newcommand\TheLocation[0]{\StrSubstitute{\TheLocationUnderscored}{_}{\space}\xspace}
\NewDocumentCommand\AddLocation{ s m }{
  \NewEnviron{#2}[0]{\IfStrEq{\TheLocationUnderscored}{#2}{\BODY}{}}
  \expandafter\NewDocumentCommand\csname Only#2\endcsname{ m }{\IfStrEq{\TheLocationUnderscored}{#2}{##1}{\empty}}
  \expandafter\NewDocumentCommand\csname Not#2\endcsname{ m }{\IfStrEq{\TheLocationUnderscored}{#2}{\empty}{##1}}
  \IfBooleanT{#1}{\Location{#2}}
}
```

The purpose of this code is to help me in writing a TV manual for my parents (they have Rokus and similar -- but not identical -- TV setups in different rooms in their house), so these macros allow me to do things like:

```latex
% In Preamble
\AddLocation*{Den}
\AddLocation{Kitchen}
\AddLocation{Master_Bedroom}
\AddLocation{Basement}

\ValueAccessor{RokuModelName}
\ValueAccessor{RokuModelNumber}

\begin{Den}
  \RokuModelName{Ultra}
  \RokuModelNumber{4660RW}
\end{Den}

\begin{Kitchen}
[...]
\end{Kitchen}

\begin{Master_Bedroom}
[...]
\end{Master_Bedroom}

\begin{Basement}
[...]
\end{Basement}

% In document:
\subsubsection{Headphone Jack}
\begin{flushleft}
  Plugging headphones into the \textbf{Headphone Jack} of your remote automatically enables \textbf{Private Listening Mode}. The audio output of the Roku \TheRokuModelName \TheRokuModelNumber will...
\end{flushleft}
```

Particularly in the location where I have the `\grenewcommand`, there's currently no short, simple, and clean way to escape the current scope for the purposes changing an existing global macro (which in my case is really a variable).

**Comment by blefloch** [comment]
I don't have time right now to go in the details of your code, sorry.
We are not keen on providing a separate programming language with
variables etc at the xparse level.  The preferred approach is to use the
expl3 programming language.  Specifically for your use case I would
probably use some key–value interface rather than the commands
\RokuModelName / Number and \TheRokuModelName / Number.  Probably my
code below should be implemented using a prop to store the data.  The
\ValueAccessor calls could be made unnecessary.

\documentclass{article}
\usepackage{expl3,xparse}
\ExplSyntaxOn
\cs_generate_variant:Nn \tl_if_eq:nnTF { V }
\tl_new:N \g_underscored_location_tl
\NewDocumentCommand \ValueAccessor { s m G{} } {
  \tl_new:c { g_location_#2_tl }
  \tl_gset:cn { g_location_#2_tl } { #3 \IfBooleanF{#1}{\xspace} }
  \keys_define:nn { location }
    { #2 .tl_gset:c = { g_location_#2_tl } }
}
\NewDocumentCommand \Get { m } { \tl_use:c { g_location_#1_tl } }
\NewDocumentCommand \Only { m m } {
  \tl_if_eq:VnTF \g_underscored_location_tl {#1} {#2} { } }
\NewDocumentCommand \Not { m m } {
  \tl_if_eq:VnTF \g_underscored_location_tl {#1} { } {#2} }

\NewDocumentCommand \Location { m }
  { \tl_gset:Nn \g_location_underscored_tl {#1} }
\NewDocumentCommand \AddLocation { s m m }
  {
    \IfBooleanT{#1}
      {
        \Location{#2}
        \keys_set:nn { location } {#3}
      }
  }

\ExplSyntaxOff

\begin{document}
\ValueAccessor{RokuModelName}
\ValueAccessor{RokuModelNumber}

\AddLocation*{Den}{RokuModelName = Ultra, RokuModelNumber = 4660RW}
\AddLocation{Kitchen}{RokuModelName = Mega, RokuModelNumber = 4660RV}

The audio output of the Roku \Get{RokuModelName} \Get{RokuModelNumber}
will \dots

\Only {Kitchen} {This is not shown since we selected Den as the location.}

\end{document}

**Comment by josephwright** [comment]
I think on balance we are not going to do this.
