### ISSUE TITLE
Add "does it load?" tests for all modules we distribute

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#420]
Typically our tests start logging after the package has loaded, so they don't detect bugs in loading the package itself when such bugs leave the package functional.

We should add tests for all packages.

**Comment by blefloch** [comment]
`xfrac` is tough as it requires `amstext` which we currently don't have in our support files.  Should I just add a copy of it there?

I had broken `xgalley` with my debug stuff, so these tests are useful.

**Comment by josephwright** [comment]
@blefloch  Enable tree searching for the `xfrac` set?

**Comment by blefloch** [comment]
This is mostly done, but

- `xfrac` (and probably `l3auxdata`) break the build because they need packages that are not installed in our test setup.

- `l3trial/l3check` does not load and would need quite a bit of work to be repaired

- `l3trial/l3htoks` and `l3trial/l3kernel-extras` only tests for pdftex, xetex, luatex for some reason not ptex and uptex.

- In `xfrac` and `xfont` I had to do omit `check-declarations` to make the tests pass.

**Comment by wspr** [comment]
Maybe I'm biased because I implemented it, but I think it's safer and easier maintenance to use the new `recordstatus` feature of l3build to test for correct loading.

The only caveat with `recordstatus` is that it's all-or-nothing, it can't be enabled just for a single test. That's not a problem but involves updating all tlg files in a repo.

Has anyone besides me taken a look at this?  Should I create a branch to try it out for the latex3 repository?

**Comment by wspr** [comment]
BTW thanks for the comprehensive work here Bruno! Just to clarify using `recordstatus` would be on top of your work here — I wasn't trying to say any effort wasn't well spent.

**Comment by blefloch** [comment]
I think you are right, Will.  I didn't know about `recordstatus`.

**Comment by josephwright** [comment]
This is now done.
