### ISSUE TITLE
Implement \prg_generate_conditional_variant:Nnn

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#427]
Cf internal discussion.

    \prg_generate_conditional_variant:Nnn \__my_comparison:n {V} {p, T}

would define the variants `\__my_comparison_p:V` and `\__my_comparison:VT`.  Other possible interface

    \prg_generate_conditional_variant:Nn \__my_comparison:n {V}

that generates `V` variants of any of the (`p`, `T`, `F`, `TF`) already defined.

**Comment by wspr** [comment]
+1 for the  :Nn  variant, for the reason that if you only want one or two of the variants it’s no problem using `\cs_generate_variant:Nn` anyway.

**Comment by FrankMittelbach** [comment]
Am 11.12.17 um 06:09 schrieb Will Robertson:
> +1 for the :Nn variant, for the reason that if you only want one or two 
> of the variants it’s no problem using `\cs_generate_variant:Nn` anyway.

-1 for the :Nn variant because it obfuscates what it happening. You get 
stuff defined depending on external circumstances!

By the way there is *always* no real problem in providing the variants 
individually we are a talking not about that many lines of declarations.

I'm for a straightforward declaration that by itself tells the reader 
what is happening (if we do provide one). In my opinion that also fits 
better with the base declaration where you also have to explicitly save 
which conditionals you want to see defined.

**Comment by wspr** [comment]
Fair enough. If it’s still a tie then I’m happy to go with Frank’s approach — in other words, change my +1 to a +0.75 :)

**Comment by blefloch** [comment]
I went for :Nnn, in part because that avoids detecting what's already
defined.  (But then one needs to loop through the {p,T,F,TF} list, so
it's not clearly simpler code-wise.)
