### ISSUE TITLE
\cs_if_exist:NTF and commands equal to \relax

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex3#439]
It looks as if `\cs_if_exist` evaluates to false if the command is equal to \relax (e.g. from a previous \csname/\endcsname).

Is this behaviour intended? If yes could it be better documentated? Currently the description only says "Any valid definition  evaluates as true" and imho the "valid" is a bit vage. 

~~~~
\documentclass{article}

\usepackage{expl3}
\begin{document}  
\ExplSyntaxOn

\cs_if_exist:NTF\uf_new_command: {exists}{unknown}
\par

\use:c {uf_new_command:}
\cs_if_exist:NTF\uf_new_command: {exists}{unknown}
\par

\cs_set_eq:NN   \uf_new_command:\relax
\cs_if_exist:NTF\uf_new_command: {exists}{unknown}
\par

\cs_new:Nn      \uf_new_command:{blub}
\cs_if_exist:NTF\uf_new_command: {exists}{unknown}
\par

\tl_new:N\l_uf_blub_tl
\tl_if_exist:NTF\l_uf_blub_tl {tl~exist}{tl~unknown}
\par
\tl_set_eq:NN\l_uf_blub_tl\relax
\tl_if_exist:NTF\l_uf_blub_tl {tl~exist}{tl~unknown}
\ExplSyntaxOff

\end{document}
~~~~

![relax](https://user-images.githubusercontent.com/4047173/36340656-853cf964-13e2-11e8-9cc8-8598330618d3.PNG)

**Comment by blefloch** [comment]
Thank you for the detailed report.  Indeed this is by design because control sequences may be made `\relax` accidentally and what one typically wants when testing if a tl is defined is to know whether it really has contents that one can expand.  For instance if `\l_foo_tl` is `\relax`, `\tl_put_right:Nn \l_foo_tl { ... }` turns it into `macro:->\l_foo_tl ...` so expanding `\l_foo_tl` then leads to an infinite loop.

I'll adjust the documentation shortly.
