### ISSUE TITLE
\bool_set:Nn \l_tmpa_bool { \l_tmpa_bool } creates an error

### ISSUE THREAD

**Issue by Vidabe** [latex3/latex3#461]
I`ve tried to invert a boolean using 

    \bool_set:Nn \l_tmpa_bool { ! \l_tmpa_bool }

but got an error. It seems that that `\bool_set:Nn` doesn't expect the given boolean to be inside its argument. This confuses me a bit as expressions like `\int_set:Nn \l_tmpa_int { \l_tmpa_int }` work perfectly fine.

(Using the LaTeX3 2018-04-30 version)

**Comment by eg9** [comment]
`! \l_tmpa_bool` isn't a legal boolean expression; you get one with

```latex
! \bool_if_p:N \l_tmpa_bool
```

**Comment by blefloch** [comment]
Thank you for the report.  That comes from the fact that \bool_set:Nn
uses TeX's \chardef primitive internally, and that this primitive sets
its argument to \relax **before** reading the value to which it should
be set.  So when we do \chardef\l_tmpa_bool = \bool_if_p:n { !
\l_tmpa_bool }, the boolean is already set to \relax when \bool_if_p:n
tries to compute the expression.  The solution is to expand things
before calling \chardef.  I've committed a fix and it will be in the
next expl3 release.

**Comment by wspr** [comment]
Should we have a \bool_toggle:N command?

**Comment by blefloch** [comment]
I've implemented \bool_set_inverse:N, choosing that name in imperfect
analogy with the l3keys type .bool_set_inverse:N.  The analogy is
imperfect because that key type takes a value and does essentially
\bool_set:Nn \l_my_bool { ! (#1) } rather than doing \bool_set:Nn
\l_my_bool { ! \l_my_bool }.

Better names welcome.

We should really think hard about all of our assignment functions: many
have "set" or "gset" or "const" in their names but there are exceptions
such as \seq_reverse:N.  In particular I would find natural to change

\seq_reverse:N  =>  \seq_set_reversed:N
\tl_reverse:N   =>  \tl_set_reversed:N
\tl_reverse:n   =>  \tl_reversed:n

**Comment by blefloch** [comment]
Issue fixed by recent commit.  (My commit closing the issue happened between egreg's closing and reopening the issue.)
