### ISSUE TITLE
storing and restoring a catcode "state"

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex3#470]
With lualatex one can store the current catcode state in a table and reactivate it later. 
I was wondering if something similar would be possible/sensible/useful with pdflatex too. 

There are a number of packages with their own implementation of a partial store/restore system. E.g. hyperref (`\Hy@RestoreCatcodes`), listings `\lst@RestoreCatcodes`), biblatex (`\blx@catcodes`).

What do you think?

**Comment by josephwright** [comment]
The problem isn't so much 8-bit engines or LuaTeX, it's XeTeX: we'd have to have some form of limitation on the number of code points affected.

**Comment by u-fischer** [comment]
Ah yes. Imho "ascii" and perhaps some suitable standard subsets is quite fine.

**Comment by blefloch** [comment]
> Imho "ascii" and perhaps some suitable standard subsets is quite fine.

I agree. Probably no need for anything beyond ascii.

By the way, the implementation should likely use an intarray to store
the data.

**Comment by josephwright** [comment]
@blefloch Do you want to take this or should I?

**Comment by blefloch** [comment]
I unfortunately have no LaTeX time now (beyond reading emails and
commits once in a while), so please do it when it is convenient.

**Comment by josephwright** [comment]
Do we want a stack here or just a simply save/restore pair? Also, does this need to integrate into any future support for wider catcode tables? For example, for 8-bit engines we can presumably do our own implementation in macros. (All suggests we should look to get catcode tables in XeTeX, and go with the full range for other engines.)

**Comment by davidcarlisle** [comment]
yes I think (assuming no change in xetex engine) that using catcode tables in luatex and just 0-255 restoration via macros in everything else would be the best plan.

**Comment by josephwright** [comment]
It looks to me like this should form part of 'bringing back' catcode table support, but in an engine-neutral way. If we work on the basis that XeTeX is currently 'lacking' but might be 'fixed', we can use native table support in LuaTeX and do the 0-255 range in other engines. That means supporting multiple catcode tables and presumably constant ones. All seems doable, probably in the first instance as an experimental module before addition to the core.


Thoughts on naming? Currently catcodes are down in `\char_...`, but that's wrong here. I could go with my earlier `\cctab_...` ideas: any better suggestions?

**Comment by davidcarlisle** [comment]
cctab looks ok to me

**Comment by blefloch** [comment]
No idea for the name, but just a reminder that the data can usefully be stored as an `intarray` since we can have as many of those as we want and they are more efficient memory-wise than macros containing digits.  Well, it actually depends on whether we want to make an effort to "compress" things: for instance do we want to only store catcodes that are different from 12 since most catcodes will be 12...

**Comment by josephwright** [comment]
I've added a new `l3cctab` module: see 5c7d6c48f4f71cf2f35f3c6216f66b09d8d2ad10 for the first commit where it's useful. Probably needs some fleshing out yet ...

**Comment by josephwright** [comment]
As you'll see in https://github.com/latex3/latex3/commit/38c0c945b50d8b302d5b8fd93b4dfe597029efdc, I've added the idea of constant catcode tables to apply settings. I'm not quite sure about interfaces at the moment.  Do we need just constant tables, plus a way to swap them? What about use in say the 'set up' argument of `\tl_rescan:nn` - hard to do if you need a restore step (but then perhaps we go for `\tl_rescan:nN`, where the second argument is a category code table).

I'll probably do some more experiments to remind myself how the LuaTeX tables work: from memory, we need to use a stack approach as they otherwise change globally ...

**Comment by josephwright** [comment]
Also, what I've implemented thus-far is slightly different from the idea of 'save/restore catcodes'. One could do that without applying any *new* codes, so just
```
\catcodes_save:
...
\catcodes_restore:
```
which is I guess closer to the various LaTeX2e package solutions. However, it seems to me that saving/restoring goes with applying some know set of catcodes, so I hope that idea at least is reasonable.

**Comment by josephwright** [comment]
BTW, I think it will be easy enough to provide `\cctab_use:N` for the `\tl_rescan:nn` case ..

**Comment by u-fischer** [comment]
Looks good imho. I'm wondering if there is a sensible use for something like 

~~~~
\catcodes_save:N\l_mycatcodes_cctab
...
\catcodes_restore:N\l_mycatcodes_cctab
~~~~

it could perhaps avoid nesting problems, but I'm not sure.

**Comment by josephwright** [comment]
That would be an alternative interface, and would I think be workable. I suspect `\cctab_use:N` might be a more appropriate name as it would allow
```
\cctab_save:N \g_mycatcodes_cctab
\cctab_use:N \c_document_cctab % Or some other well-established
...
\cctab_use:N \g_mycatcodes_cctab
```
which I feel would be useful. Once you go for tables of catcodes, it seems natural to me to use them rather than manual setting of single catcodes in most cases.

**Comment by josephwright** [comment]
I could do with some thoughts on the various possible interface choices here: do we want save/restore, or begin/end, or ...

**Comment by davidcarlisle** [comment]
I think the model for catcode tables we have in ltluatex + ctablestack
works reasonably OK

basic level support just needs to allocate a new named slot then commands
to save the current catcodes in that table and to use that table so
basically just very thin wrappers to allow {..} syntax around
\savecatcodetable and  \catcodetable respectively.

If we want more the global push/pop commands from ctablestack are OK

**Comment by josephwright** [comment]
I think I'll go with the same plan as `l3benchmark`: move to the experimental tree and ask for feedback.

**Comment by josephwright** [comment]
@u-fischer Am I OK to close? The basic idea is sorted ...

**Comment by u-fischer** [comment]
@josephwright  Sure, go along.
