### ISSUE TITLE
l3doc: split into class and package

### ISSUE THREAD

**Issue by wspr** [latex3/latex3#476]
There is much in l3doc that doesn't "need" to be in a class — we've had requests, for example, to be able to load the structural parts of l3doc with a different document class such as `ltugboat.cls`.

This should be fairly easy to make a clean division...

**Comment by car222222** [comment]
Very likely this is feasible . . .
BUT due to staff shortages this train may not depart!:-)

**Comment by zauguin** [comment]
I'm also in favor of splitting `l3doc`, but I would prefer a separate name (`l3codedoc` looks good) to avoid confusion.

**Comment by FrankMittelbach** [comment]
That very much depends on what is provided: if I can take a document currently written for  the `l3doc` and can put its content into a document with a different class, say, `book` and only have to load the package `l3doc` to make it run then I think it  would be okay to use the same name instead of inventing a new one. In my opinion there shouldn't be any confusion in that casebut I'm okay with a longer name if the majority thinks differently.

**Comment by wspr** [comment]
I definitely like the idea of a split, but I think a more user-friendly package name than l3doc would be good. We have packages like l3benchmark and so on, but these are exclusively (?) programming tools. If we have a (now supported and maintained) package for users to load, I think it should have a name more like “xdoc” (but that name is already taken)...

**Comment by josephwright** [comment]
A 'reverse-dupe' of https://github.com/latex3/latex3/issues/1136
