### ISSUE TITLE
l3doc \thanks -> pdftex hyperref warning

### ISSUE THREAD

**Issue by kberry** [latex3/latex3#487]
When a dtx file contains \thanks in the \title, I get the annoying:

pdfTeX warning (dest): name{Hfootnote.1} has been referenced but does not exist, replaced by a fixed one

Maybe someday ... --thanks, karl.

[enddefbreak.zip](https://github.com/latex3/latex3/files/2474736/enddefbreak.zip)

**Comment by u-fischer** [comment]
`l3doc-TUB.cls`  redefines `\maketitle` *after* hyperref has been loaded. This means that the patch from hyperref to avoid this problem is overwritten. 

At the core is the problem that `\footnotetext` when used with an optional argument doesn't set an anchor. So `\footnotemark\footnotetext[\the\c@footnote]{text}`  has a link from the `\footnotemark` but no destination. 

~~~~
\documentclass{article}

\usepackage{hyperref}   

\begin{document}

\makeatletter
\footnotemark\footnotetext[\the\c@footnote]{text} % missing destination

\footnotemark\footnotetext[\the\c@footnote]{\hyper@anchor{\Hy@footnote@currentHref}\relax text} %ok

\end{document}
~~~~

**Comment by blefloch** [comment]
This uses `l3doc-TUB`, and replacing it by a minimally-modified `l3doc` (where `\LoadClass{article}` is replaced by `\LoadClass[final]{ltugboat}` and `\bibname` is defined as a no-op) does not lead to this warning, so I don't know what we can do there.

I vote to mark this as closed and "report-elsewhere", even though elsewhere is perhaps in Frank's inbox.

**Comment by kberry** [comment]
ok, sounds like the problem is in ltugboat, sorry for the noise.
