### ISSUE TITLE
l3doc \end{function} removes normal \parskip

### ISSUE THREAD

**Issue by kberry** [latex3/latex3#488]
I haven't tried to comprehend the code, but it seems that `\end{function}`
in l3doc-TUB removes the normal parskip. E.g., in dashundergaps,

```
%   way we get underlined gaps of the right size.
%
% \end{function}
%
% By default, \pkg{ulem} changes \cs{emph} to underline text, so
```
It appears there is no extra space between the line with "right size."
and the next line "By default ...".

In comparison to simply two consecutive paragraphs, e.g., just above:

```
% because it ensures that the fill-ins take the same amount of space as the
% gaps.
%
% Another important feature is the possibility to artificially widen the
```

which looks like the specified \parskip.

I see Frank's comment there:
```
% \end{function}  ^^A wrong place but something buggy in the class
```

Indeed ... 
(I wonder if I got the markdown syntax right for those code blocks ...)

Same files in the zip as before.
[enddefbreak.zip](https://github.com/latex3/latex3/files/2474741/enddefbreak.zip)

**Comment by u-fischer** [comment]
The parskip is there -- you can see it if you set it to a large value, e.g. 10pt. But if I understood the code the function is a box. So adding a \strut should help: `.... right size.\strut`

**Comment by FrankMittelbach** [comment]
@u-fischer doubt it to be honest. The issue is this: whatever function really does (not checked) it ends up generating an \hbox inside an \hbox and the inner one has a huge depth and thus the outer one too, eg, before we get this (with parskip=23.7 to find it easily):

```
....\glue 12.0 plus 4.0 minus 4.0
....\glue 0.0
....\glue(\parskip) 23.7
....\glue(\lineskip) 1.0
....\hbox(9.5493+139.33821)x372.0
.....\hbox(9.5493+139.33821)x372.0
```
and afterwards we have again no baselineskip but lineskip and that is the noticeable difference

```
....\penalty 0
....\glue(\parskip) 23.7
....\glue(\lineskip) 1.0
....\hbox(6.88875+0.0)x372.0, glue set 342.76001fil
.....\kern-0.38 (left margin)
.....\hbox(0.0+0.0)x0.0
.....\T1/lmr/m/n/10 X
```
So struts would only help if you manually add them in the last line of function (for the depth) and in the first line after. A real fix would be to make sure that the baseline skip gets added, ie that the box doesn't have such a depth but the depth of its last line.

**Comment by u-fischer** [comment]
@FrankMittelbach 
> So struts would only help if you manually add them in the last line of function

But this is what I suggested ;-). A strut at the begin the following text could be useful too, but as the text begins with B will probably make not so much difference. 

> A real fix would be to make sure that the baseline skip gets added, ie that the box doesn't have such a depth but the depth of its last line.

Yes, but then one has the similar problem at the top as the box has then a large height. For a real fix one would need an object that is like a box with two reference points and so both a normal height and a normal depth.

**Comment by blefloch** [comment]
For @kberry 's specific problem it is enough to set the `\prevdepth` by adding a line to `l3doc-TUB.cls`.

```latex
\cs_new_protected:Npn \__codedoc_function_typeset_stop:
  {
    \par
    \dim_set:Nn \prevdepth { \box_dp:N \l__codedoc_descr_coffin }
    \allowbreak
  }
```

**Comment by wspr** [comment]
Between this bug fix and the discussion around the same problem for galleys (https://github.com/latex3/latex3/issues/50) I wonder if we're missing something here — if putting coffins into paragraph text needs a correction to `\prevdepth`, shouldn't we either do this directly in the `\coffin_use:N` code or provide a high-level wrapper (like `\coffin_use_as_paragraph:N`) ?

**Comment by FrankMittelbach** [comment]
I think we do. And I'm not sure that the fix is actually correct in this respect. Point is a coffin that goes into a paragraph needs to set `\prevdepth` based on how it ends based on the depth in the coffin, but it also needs to set its first line correctly based on the \prevdepth of the last line before it was placed. Now the big issue seems to me that one doesn't quite know that that depth at the time the coffin is build, so perhaps it does indeed need something like `\coffin_use_as_paragraph:N` that adjusts the placement based on that depth, which is why I guess @u-fischer  suggested using struts. But struts don't quite get that right either.
