### ISSUE TITLE
Weird Argument Delimiters in l3keys Code Break \ProcessKeysOptions

### ISSUE THREAD

**Issue by tail-reversion** [latex3/latex3#493]
### Context

Some keyval options are convenient to give as a comma-separated pair (_e.g._ `paper-size = {8in, 10in}`). I wrote a general function for parsing such a pair and applying a function to the elements:

```
\cs_new:Nn \soranus_apply_comma_pair:Nn
  { \__soranus_apply_comma_pair_aux:Nw #1 \q_stop #2 \q_stop }

\cs_new:Npn \__soranus_apply_comma_pair_aux:Nw #1 \q_stop #2 , #3 \q_stop
  { #1 {#2} {#3} }
```

Then I can simply define something like

```
\keys_define:nn { soranus }
  {
    paper-size .code:n =
      { \soranus_apply_comma_pair:Nn \__soranus_set_paper_size:nn {#1} }
  }
```

### Problem

Comma pair values work perfectly, except when the keyvals are processed with `\ProcessKeysOptions`, which results in the error:

```
Runaway argument?
\tl_set:Nn \l__keys_module_tl {}\__clist_map_function:Nw \__clist_map_1:w \ETC.
! File ended while scanning use of \__soranus_apply_comma_pair_aux:Nw.
```

**Notes**
- This error is not caused by quarks. For example, the arg pattern `#1 ( #2 , #3 )` fails identically.
- This error only occurs when there is a delimiter at the end of the arg pattern. For example, the pattern `#1 \q_stop #2 , #3` does not fail.
- This error does not occur when the value is passed by a `.meta:n` key.

**Additional Information**
- This error occurs for the pdfTeX, XeTeX, and LuaTeX engines.
- TeXLive 2018
- expl3 release 2018-06-14

**Comment by josephwright** [comment]
The issue here is that the LaTeX2e kernel strips some material from package options before 'we' ever see it: the original code for options was never intended for keyvals. In particular, we loos the braces here, so what gets passed is `paper-size=8in,10in`. That of course means that the keyval system only passes `8in` as the value, and your quick comma splitter isn't set up for the 'oops, no comma' case. As such, I'm afraid this is out-of-scope here.

**Comment by josephwright** [comment]
This has been reported for the kernel at https://github.com/latex3/latex2e/issues/85.
