### ISSUE TITLE
l3keys: \keys_set_known:nnN doesn't store whole path

### ISSUE THREAD

**Issue by Vidabe** [latex3/latex3#508]
Greetings,

Using the following example 

    \documentclass{article}
    \usepackage{expl3}

    \ExplSyntaxOn
    \keys_set_known:nnN { foo } { sub/bar = true } \l_tmpa_clist
    \clist_show:N \l_tmpa_clist
    \ExplSyntaxOff
    \begin{document}
    \end{document}

I imagined from reading the manual that the variable `\l_tmpa_clist` 
would contain `sub/bar={true}`, instead it only contains `bar={true}`.
Would it be possible to include the whole path?

**Comment by josephwright** [comment]
Hmm, the fix really needs some way of showing 'absolute' key paths, as otherwise you end up with the question of whether to store `foo/sub/bar` or `sub/bar` (internally, key paths get expanded fully). 

I'll probably add support for absolute paths first, then the fix here is trivial.

**Comment by josephwright** [comment]
@wspr I have a fix for this issue ... but it breaks `fontspec`. Can you take a look at the branch I've created and let me know if a change in `fontspec` would be OK?

**Comment by josephwright** [comment]
Hmm, I  see why I might have done this .. if you store the full path, the 'stubs' are no good. Perhaps we need logic to return "full path - given module". I can sort that, no change needed to `fontspec` I think. I'll try later today.

**Comment by wspr** [comment]
Maybe I don’t understand your example but I’d expect those to be equivalent (isn’t it documented that way?)

I can happily change fontspec code if needed. (In fact I had already planned to around key groups rather than keys_set_known.) 

The way I use keys_set_known currently is to ensure certain keys get run before others. So if the user says

    key2,key3,keyA,key4,keyIV

that’s processed with something like

    keys_set_known {fontspec-roman} <the list>
    keys_set_known {fontspec-arabic} <the leftovers>
    keys_set {fontspec} <the leftovers>

Now that l3keys supports key groups, it would be better to do this differently, I just haven’t had time to re-architect.

**Comment by josephwright** [comment]
Returning a fully-qualified key name has the advantage that it's clear, but at the cost that they can'd directly be reused (so break _e.g._ `fontspec`). Stripping a known amount off the key path lets the get reused, but at the cost of some clarity. Looking at how `\keys_set_known:nnnN` is being used at present, I have the feeling that people are relying on the current behaviour: you just get the key names (plus values) and nothing else. As such, I suspect this might be a case of documenting the current behaviour rather than changing anything: it's something I didn't perhaps consider at the time we wrote the code (which was basically to support `fontspec`.

@Vidabe Would a doc change work for you? Do you also want some kind of 'returns full path' function? At this stage, it would have to have a new name, but I'm sure we can find one.

**Comment by josephwright** [comment]
@Vidabe Much the same had occurred to me: I'll look at implementing this shortly.
