### ISSUE TITLE
Confirm whether \NewDocumentCommand is intended as a replacement for \newcommand

### ISSUE THREAD

**Issue by oliviercailloux** [latex3/latex3#513]
I believe it would clarify things up if the team could comment on the discussion [here](https://tex.stackexchange.com/a/98157), where Joseph Wright writes that “\NewDocumentCommand is intended for 'package authors' to define commands, while \newcommand is rather more fluid as it is also used to create variables (macros used as storage). This makes \newcommand a better choice if what you are defining is a variable”. It contradicts the doc and makes me wonder whether \NewDocumentCommand should really be preferred. 

The xparse package documentation dated 23rd of August, 2018 states: “The xparse package provides a high-level interface for producing document-level commands. In that way, it is intended as a replacement for the LATEX 2 ε \newcommand macro.”

Please consider aligning this comment and the doc as to what the advice of the main team developing LaTeX would be here.

**Comment by tail-reversion** [comment]
I’m not part of the LaTeX team but I hope I can offer some clarification.

LaTeX2e provides variables like lengths, counters, and boxes but doesn’t have dedicated variables for, say, snippets of text or holding a set of font and color settings to be applied later. The solution in LaTeX2e for those cases is to use a macro that takes no arguments.

For example, to define the text set at the top of the table of contents, the article class includes this definition:

```
\newcommand{\contentsname}{Contents}
```

Then, if someone wants to change that text to something else, they would write

```
\renewcommand{\contentsname}{My Table of Contents}
```

LaTeX3 has dedicated variables for such uses, called token lists, which are treated differently from macros.

The previous definition, in `expl3` (the programming language of LaTeX3), would look like:

```
\tl_new:N \g_article_contents_name_tl
\tl_gset:Nn \g_article_contents_name_tl {Contents}
```

And we can change the name by setting the variable again.

However, since LaTeX3 tools are currently used on top of LaTeX2e, we sometimes need to use the `\renewcommand` approach to set variables defined by LaTeX2e code.

The `xparse` package is meant for defining high-level interfaces, so anything that document authors are meant to use should be defined using `\NewDocumentCommand` (or `\NewDocumentEnvironment`) so that there are simple commands that hide the underlying code.

For example, we could provide a command called `\setupcontents` that lets the user change provide settings, like

```
\setupcontents{
  name = My Table of Contents,
  depth = 2,
  font = \large\scshape,
  ...
}
```

and these settings would be passed along to the `expl3` code that sets the appropriate variables.

The very short version:

- Always use `\NewDocumentCommand` for defining user commands.
- Use `expl3` variables and functions in the underlying code whenever possible.
- Use LaTeX2e techniques, like `\renewcommand` to set variables, only when working with LaTeX2e code.

**Comment by pablgonz** [comment]
Mmm, I think this is clear from the latest (2020) kernel news.

**Comment by josephwright** [comment]
Covered by the move to `ltcmd`.

**Comment by Evpok** [comment]
This doesn't clarify what should be used for document-level variables. It's a bit awkward to use `\NewDocumentCommand` for commands and `\newcommand` for variables, but the only other clean approach I see (using expl3 tokens lists) also has major downsides such as having to use ~ for spaces.
