### ISSUE TITLE
Ensure all _get functions have (TF) versions

### ISSUE THREAD

**Issue by josephwright** [latex3/latex3#538]
This is true in most places but we should make sure it's universal (_e.g._ for experimental file functions). We should also ensure that the return value is the same in all cases when there is a failure: `\q_no_value`.

**Comment by josephwright** [comment]
It's a bit more complex than I thought. Two factors to consider:

- What to do where we 'get' a string, not a token list
- Do all cases 'make sense' in being able to fail

**Comment by josephwright** [comment]
For reference, the following have `TF` versions:
```latex
\sys_shell_get:nnN(TF) (non-TF returns empty not `\q_no_value`)
\clist_get:NN(TF) (TF does not return `\q_no_value`)
\file_get:nnN(TF) (non-TF returns an error if not found)
\prop_get:NnN(TF)
\seq_get:NN(TF)
\seq_get_right:NN(TF)
\seq_get_left:NN(TF)
```
whereas the following do not
```latex
\file_get_mdfive_hash:nN
\file_get_size:nN
\file_get_timestamp:nN
\file_get_full_name:nN
\ior_str_get:NN

\tl_build_get:NN
\ior_get:NN

\token_get_arg_spec:N
\token_get_replacement_spec:N
\token_get_prefix_spec:N
```
Of the latter, the first block return strings (although `\ior_str_get:NN` is listed as a tl), so can't give `\q_no_value`. I suspect both `\tl_build_get:NN` and `\ior_get:NN` have performance reasons not to have a `TF` version. The last block seem not to fit at all.

**Comment by FrankMittelbach** [comment]
I don't think there is a conceptual issue with making `\q_no_value` a possible return value in for any getter function regardless of the type that it returns in the success case. 

With `\tl_build_get:NN`  my first impression is that the whole concept is wrong, sorry. It seems to me that this is in fact a different data type and should be handled as such rather than doing work in situ. At a minimum "`get`" is probably the wrong name (but these are after midnight thoughts, and based on the fact that these function   must have been added when I was not paying attention so I wasn't areware of them until now)

With the last block I wonder if those should even be public or should be there in the first place.

**Comment by josephwright** [comment]
@FrankMittelbach The point with the functions that return strings is they are documented as of typr `str` not `tl`. So they can't be `\q_no_value` as a single token. It's a question of me changing how they are described and returning token lists. So if we are happy, that's fine.

On `\ior_get:NN`, the performance issue is mainly for `\ior_map_inline:Nn`, which can be handled by using the current definition internally and using a slower one for the public version.

On `tl_build`, this got made public when we were trying to tighten up on how much internal 'stuff' we have. Let's put that one aside for a discussion of the entire naming of that concept.

**Comment by josephwright** [comment]
OK, I'll do a first pass to tighten up the cases that are clearly 'right', then we can deal with the other ones.

**Comment by josephwright** [comment]
On the `\token_get` block, they are used in
```
latex\ctex\ctexpatch.sty
latex\l3kernel\expl3-code.tex
latex\l3packages\xparse\xparse.sty
latex\regexpatch\regexpatch.sty
latex\siunitx\siunitx.sty
latex\xpatch\xpatch.sty
xelatex\xecjk\xeCJK.sty
```
_i.e._ largely in pathcing operations. (I use them in `siunitx` to do auto-detection of token lists.)

**Comment by josephwright** [comment]
I'd appreciate it if people would check the changes thus-far. They should cover all of the 'good' cases in `l3kernel`, so we should have consistent behaviour.

**Comment by tail-reversion** [comment]
This might be the wrong place to comment…

I like the idea of having `(TF)` versions of all the `get` functions, but this has me wondering. Since the `(TF)` versions are sort of preferred practice because they’re clearer, and since they eliminate the risk of accidental quark explosion, maybe only the `(TF)` versions ought to be part of the public interface?

**Comment by josephwright** [comment]
Well we already have the non-TF versions, and depending on the use case it might make sense to collect up `\q_no_value` instead. Will depend on how people want to use them.

**Comment by wspr** [comment]
I would agree with both Kelly & Joseph that the TF are “better” but that the non-TF version still have their place...

**Comment by josephwright** [comment]
Right, this one is done ...
