### ISSUE TITLE
Date and time tools 

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#547]
We should add basic tools to manipulate dates, such as adding a certain number of months to a date.  I use a toy version of this in `l3deprecation` to compute the 6 month grace period.

There are many issues to consider:
1. Just do dates, or also times?  Down to what precision?  Of course the current time is not known very precisely but one may want to work with very precise/short times nevertheless.
2. Do we work with times or with time intervals or both?
3. What epoch to use for the day (Julian date, Gregorian date, Rata Die, …)?
4. What epoch to use for the time?  If it is far in the past, do we need big integers?
6. What about time-zones?  Daylight saving?  Leap seconds in UTC?
7. In what format do we get the current time from the system?
8. More prosaically, what do pgf's calendar support and datetime2-calc do?  What do other programming languages do?  What is useful for a typesetting system?

**Comment by wspr** [comment]
In my own work I’ve found need for date manipulation (e.g., "what date is YYYY/MM/DD + 73days?” ) and less so time manipulation. I also find it annoying in other programming languages when I just want to manipulate the date but I’m forced to give a dummy time of (say) 00:00. However, (as a use-case example) I can imagine if you wanted to typeset an agenda for an online meeting (say) you’d want to have a combined date+time object to calculate local times for each participant.

**Comment by tail-reversion** [comment]
I’ve been writing a little date+time package and have found that using tuples for dates and for times works well, but of course means that comparisons are more expensive. For a combined date+time structure, I use a pair containing the two components.

Using tuples allows flexibility because then you don’t have to subscribe to a particular epoch in the data format and can just choose whatever functions use the desired format. For times, it also avoids the issue of needing sufficiently large integers. Of course, there are probably plenty of potential problems with this format that I’ve not considered.

With respect to use cases and precision of times, there is a fair amount of variation. Something like the minutes of a meeting or the schedule for a conference will use a time resolution of minutes. For things like timing of athletic events and experiments of modest rigor (really anything where a person is “eyeballing” the time or using a stopwatch), a resolution of seconds to hundredths of seconds may be common. Rigorous experiments that use computerized timing or high-speed cameras can go anywhere from milliseconds to even nanoseconds. Anything computer related will require at least millisecond precision, and frequently nanosecond.

Since people may want to typeset tables of database and network information, time zones and leap seconds would be useful. Government documents may need daylight savings information?

For typesetting, tables and plots will get a lot of value out of date and time utilities. People may want to create timelines. The humanities frequently have plenty of dates to typeset. Locale-specific formatting is needed, which `datetime2` (and recently `babel`) provide.

There would be a lot of value in being able to parse locale-specific dates and times and turn them into an internal format for use with date+time tools. This would help authors to write in a familiar format.

Other programming languages sometimes provide a flexible format where the precision can be selected by omitting parts of the date or time, and functions on these data structures respond automatically to the different possible precisions. Implementing that requires either pattern matching or null values that mark the elided fields.

**Comment by josephwright** [comment]
I think we should start by working out what areas a _generic_ set of date/time functions should cover. From a programming support point of view, we need to be able to work out date differences to deal with the equivalent of `\@ifpackagelater`. We probably also want to handle file timestamps (as given by `\file_get_timestamp:nN`), again from a pure programming support point of view.

Beyond that, I think like many other systems, we should probably stick to Gregorian dates, which are predictable, and use the timestamp format to handle daylight saving or whatever.

**Comment by car222222** [comment]
I am unsure what @josephwright means by sticking to lGregorian dates”?  I agree that the core system needs to work with a single date type, but this need not be “Gregorian” with all of its complications when extending it backwards to BCE etc. It will be far easier to work with a system whose values are “all integers” rather than one that misses out 0.  This could have Gregorian 1900 or 2000 as Year Zero!  Does not matter provided it has a zero!  Then producing an actual date depends on the full details of the real world system to be used (similar to other aspects of locale that effect the numbers and their formatting)n maybe on,y a minimal collection of such content conversion functions need be in the kernel, but a “generic template” for producing a large variety of transformations would be useful.

SUMMARY:  We do not want to use Z\0-arithmetic internally!

**Comment by car222222** [comment]
From a business and day-to day viewpoint, the following are very useful bits of data: Week Number; Lunar Calendars, especially the ISO Chinese system, thus: Nth day of the Mth wax/waning of the moon in the Year of the Animal in the Lth cycle (approx translation).

**Comment by josephwright** [comment]
@car222222  I meant that for a 'core' set of functions, I'd favour only dealing with Gregorian dates. There are well-established extropolations before 1582 (https://en.wikipedia.org/wiki/Proleptic_Gregorian_calendar).

**Comment by eg9** [comment]
I'm not sure this is business for the kernel. If we provide tools for the Gregorian calendar, why not for the Julian calendar (still used by many people in the Orthodox world), the Islamic, Hebrew, Persian, Chinese, Japanese, Inca and whatnot?

**Comment by josephwright** [comment]
@eg9 Like I said, there is a core need for stuff which supports programming: difference in date and tiem for e.g. file tests.

**Comment by eg9** [comment]
@josephwright OK, that's fine. But for such purpose we don't need to think about covering years before 1582. Unless you find some file made by Fibonacci or Archimedes… Just provide the tool and warn about the limitations.

About the leap second, I don't think there's much to do except keeping a list and checking against it.

**Comment by car222222** [comment]
My main was that, as @tail-reversion wrote, the core functions should work on simple integers, with a 0.  Which year is chosen as year-zero does not matter, but having one is essential. Thus, as @eg9 wrote, you can use, internally, the Modern Gregorian Year (which probably is some kind of standard, maybe ISO?) internally.  Providing transformations to variants of this, such as the orthodox calendar, or BCE years, etc., etc. is a separate concern. Indeed, different use-cases may require small variants so the creation of, at least, these should be made straightforward, with one or two examples of this creation usage included in the kernel.

SUMMARY: do not try to support anything but the MGY directly.

**Comment by car222222** [comment]
A few extra notes:
The kernel may need to provide the data and functions needed for lunar calendars.  I am not an expert on these but I think there are variants due to both of these: Diffences in the “Day of the New Moon” in edge cases; The provision of “Leap Months”/13-month years or other methods of syncing the Sun and Moon cycles.

**Comment by car222222** [comment]
Add to Summary:
Provide easy tools to do lsimple conversions.

Think about larger variations such as Lunar Calendars later?

**Comment by car222222** [comment]
Greg+Year-zero even has a name:
Description: **Astronomical year numbering** is based on AD/CE year numbering, but follows normal decimal integer numbering more strictly. Thus, it has a year 0; the years before that are designated with negative numbers and the years after that are designated with positive numbers.

**Comment by jbezos** [comment]
> the Modern Gregorian Year (which probably is some kind of standard, maybe ISO?)

ISO 8601. According to it:

===
The Gregorian calendar has a reference point that assigns 20
May 1875 to the calendar day that the “Convention du Mètre”
was signed in Paris.
...
For the purposes of this International Standard the calendar
based on these rules is referred to as the Gregorian calendar.
The use of this calendar for dates preceding the introduction
of the Gregorian calendar (also called the proleptic Gregorian
calendar) should only be by agreement of the partners in
information interchange. [ie, before 15 October 1582]
===

I was working on dates for babel, but for the moment only the
string representation (ie, \today and the like). Conversions
go from trivial (eg, Thai) to impossible (Islamic, except the
so called Civil Islamic calendar). Besides date arithmetics,
I also have my doubts this is a task for the LaTeX kernel.

Javier

**Comment by car222222** [comment]
@jbezos   What is this “Civil Islamic calendar”?  Have you looked st the Jewish calendar or Chinese lunar calendars?  Are they any easier than Islamic ines?

**Comment by car222222** [comment]
Here is a summary of current “official usage” from Wikipedia, so maybe fairly accurate:

Most countries in the world use the Gregorian calendar as their sole civil calendar. Countries which do not use the Gregorian calendar are Afghanistan and Iran, which use the Solar Hijri calendar, Ethiopia (Ethiopian calendar) and Nepal (Vikram Samvat). Some countries use other calendars alongside the Gregorian calendar: Bangladesh (Bangla calendar), India (Indian national calendar) and Israel (Hebrew calendar).

Other countries use modified versions of the Gregorian calendar: Taiwan (Minguo calendar), Thailand (Thai solar calendar), North Korea (North Korean Calendar) and Japan (Japanese calendar).

**Comment by josephwright** [comment]
@jbezos I've tried to be clear that I'd not really thinking of 'all possible calenders', probably rather 'operations on timestamps or similar'. Things like difference between two times for a standard UTC time.

**Comment by jbezos** [comment]
@car222222 The Islamic calendar is based on the direct observation of the Moon (by some authority). So, the beginning of a month might depend on the weather, and even different places might have different dates. It cannot be known on beforehand. The Civil Islamic calendar is based on an algorithm. I revised a good deal of Arabic digital papers and the Gregorian calendar is the usual one. As to the rest (Hebrew, Japanese, etc.), I think the date can be computed somehow.

Note also the Julian day  is not the same as the Julian calendar:

https://en.wikipedia.org/wiki/Julian_day

A conversion from the Gregorian date (as provided by TeX itself) to the Julian day seems a good idea. The reverse conversion, to Gregorian or any other calendar, is a task for some package.

**Comment by car222222** [comment]
Aha, I did not know that the “actual viewing of the moon” was still used officially.  That could give different dates in different places.  It also makes it impossible to plan events for particular day! 

The Chinese and Jewish systems certainly do not work that way, they are now totally predictable.
One limitation of the Jewish system is that it has no way to express years before their year one!

**Comment by car222222** [comment]
@josephwright   Please nite that no-one except you has ever suggested that more than one system should be supported directly.  The important two (dustinct) things for the kernel to provide are:
an internal system for doing calculations:
tools for constructing algorithms to produce dates in any “predictable calendar”.
One non-trivial examples le of using the tools to encode an algorithm would also be useful.

**Comment by car222222** [comment]
There are also many different ways of naming the hours of the day, way beyond the am/pm that is still standard in the USA.  Also variation in the “time” when each day starts.

But these do not affect delta-times.

**Comment by blefloch** [comment]
I think even tools to help conversions should not be in the kernel but
only in a separate package.  In any case, we should start by developing
all of this (including basic delta-t and parsing file stamps) in a
separate package before adding anything to the kernel.

**Comment by car222222** [comment]
I agree with using a package, but the separation of concerns is still important, and using “normal integers” for the internal representation (especially if deltas are the most important use-case).

**Comment by car222222** [comment]
This leaves two necessary decisions: 
the level of precision to support;
what formats of input data to accept, ab initio.

**Comment by blefloch** [comment]
I agree that we need to decide on the input format and the level of
precision, but we also need to decide the range (and the epoch).  Let's
ignore leap seconds for now, which are treated differently in UTC and
Unix time.

PDF file stamps seem to have a precision of seconds, and reading a few
Wikipedia articles, it seems somewhat common for file systems to use a
signed 32-bit or 64-bit integer to store the time in seconds since 1970.
 A 32-bit integer allows a range of years from 1901 to 2038.

(Incidentally: the syntax of PDF time stamps makes sense for years
between 0000 and 9999, which means 3.2×10^11 possible seconds.  It seems
that just like Unix time they cannot represent a time stamp that
corresponds to a leap second, as for instance D:20161231225960+0100 is
not strictly speaking allowed by the PDF standard since that standard
specifies that the seconds should be between 00 and 59.)

So it seems that from the point of view of manipulating time stamps we
may want to work in units of one second.  We cannot work with TeX
integers because 32 bits is too limited: 2038 will arrive soon enough.
Either we use big integers (un-Earthing l3bigint) or we split the data
into day and seconds or perhaps years and seconds or we keep the data as
a string and implement specific functions to compute time differences etc.

**Comment by josephwright** [comment]
I think at present it's best to close here: we can revisit with concrete requirements when we have them.

**Comment by car222222** [comment]
We really need a status of something such as:

"closed but not forgotten"!
