### ISSUE TITLE
xparse \SplitList unexpectedly strips braces around single groups

### ISSUE THREAD

**Issue by tail-reversion** [latex3/latex3#550]
The `\SplitList` processor will strip braces surrounding a list item, if the item is a single group.

Processing an argument with `\SplitList{,}` has the following results (`before ==> after`):
```
a      ==> {a}
{a}    ==> {a}
{a}b   ==> {{a}b}
a,b    ==> {a}{b}
{a},b  ==> {a}{b}
a,{b}  ==> {a}{b}
a,{b}c ==> {a}{{b}c}
```

Is this intended behavior?

**Comment by blefloch** [comment]
> Is this intended behavior?

Yes, in order to allow items to themselves contain commas (or whatever
the delimiter is.  If I remember the code correctly, it first removes
spaces at both ends of the item, then if the item is a single group the
outer braces are removed.  I'm leaving the issue open for now: perhaps
the xparse documentation could be improved.

**Comment by josephwright** [comment]
This reminds me that at some point there was a query about brace-stripping inside optional arguments (_e.g._ `\foo[{bar,baz}]{bong}`). We should probably make sure that everything is both as-desired and corretly documented here.

**Comment by josephwright** [comment]
Addressed in l2b1a57d01451129a75f6dfba8ed2cfc62dec1844 (latex3/latex2e).
