### ISSUE TITLE
Clarify differences between integer expression conditionals

### ISSUE THREAD

**Issue by tail-reversion** [latex3/latex3#553]
There are two sets of functions for comparing integer expressions, `\int_compare:nNn(TF)` and `int_compare:n(TF)`, with respective predicates also defined.

In my understanding, `\int_compare:nNnTF` is a light wrapper around TeX’s `\ifnum`, augmented with `\numexpr`. On the other hand, `\int_compare:n(TF)` is an extended function that allows more relation types (`<=`, `!=`, &c.), and allows Python-style chaining of comparisons.

I’m guessing that there’s a small efficiency gain in using `\int_compare:nNn(TF)`, but I’d also guess that the difference is probably irrelevant in most cases.

I’d almost argue that `\int_compare:nNn(TF)` is redundant and ought to be deprecated, but it probably has its place. Perhaps a note could be added to help programmers in choosing between the two?

**Comment by blefloch** [comment]
Thanks.

I've added comments in the description of \int_compare:nNnTF and
\int_compare:nTF and the corresponding dim and fp comparison functions.
 For int and dim, the :nNn version is around 5 times faster than the
more flexible :n version.  For fp, the :nNn version is only slightly faster.

> I’d almost argue that |\int_compare:nNn(TF)| is redundant and ought to
> be deprecated, but it probably has its place. Perhaps a note could be
> added to help programmers in choosing between the two?

I wouldn't go so far as to deprecate it (even though in the kernel when
we really care very much about speed we end up using low-level
\if_int_compare:w ... \fi: conditionals).

If the text is clear the issue can be closed.

**Comment by FrankMittelbach** [comment]
Depends on the machine I guess:

```
\documentclass{article}

\usepackage{l3benchmark}

\begin{document}


\ExplSyntaxOn


\cs_new:Npn\compsingle:n#1{\int_compare:nNnTF{1}<{2}{}{}}
\cs_new:Npn\compmulti:n#1{\int_compare:nTF{1<2}{}{}}

\typeout{single}
\benchmark:n { \int_step_function:nN { 1000000 } \compsingle:n }

\typeout{multi}
\benchmark:n { \int_step_function:nN { 1000000 } \compmulti:n }

\ExplSyntaxOff

\end{document}
```

On the older PC I'm currently on this compares with 3 to 9.8 seconds so factor of more than 3

**Comment by tail-reversion** [comment]
The added notes look good to me. I think that takes care of it, thanks :-)

**Comment by blefloch** [comment]
Your test is not great, because the \int_step_function:nN add a large
overhead.  You end up comparing

  \int_step_function:nN plus \int_compare:nTF
  \int_step_function:nN plus \int_compare:nNnTF

so the ratio is smaller than if you had compared \int_compare:nTF with
\int_compare:nNnTF directly.  That's not easy to do correctly, which is
why the l3benchmark code was written to repeat its input and measure
that, but avoid measuring how long it takes to replicate the input.
With the following I find a factor of ×7.  Without the
\prg_replicate:nn, so presumably with the best measurement that
l3benchmark is able to give, I find a factor of ×9.  The reason I put ×5
is that when the things to compare are not just numbers but are
expressions the ratio goes down a little bit, depending on how
complicated the expression is.  I figured going in infinite detail in
the documentation was not super useful.

  \documentclass{article}
  \usepackage{l3benchmark}
  \begin{document}
  \ExplSyntaxOn
  \cs_new:Npn\compsingle:{\int_compare:nNnTF{1}<{2}{}{}}
  \cs_new:Npn\compmulti:{\int_compare:nTF{1<2}{}{}}
  \benchmark:n { \prg_replicate:nn { 1000000 } \compsingle: }
  \benchmark:n { \prg_replicate:nn { 1000000 } \compmulti: }
  \ExplSyntaxOff
  \end{document}
