### ISSUE TITLE
public conditional to test if enable-debug is active

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex3#557]
It would be imho useful if one could test the state of enable-debug. Or if there were variants of `\debug_on:n` and `\debug_off:n` which don't give errors without `enable-debug`. 

Then one could add the debug code permantly into the sources and activate more easily when working on updates.

**Comment by wspr** [comment]
I think a public \kernel_if_debug:TF function (or \debug_if_on:TF ??) makes sense, as then package authors can then add similar branches in their own code.

This reminds me I still haven’t merged in the updates to register checking that we were talking about a couple of months back...

**Comment by FrankMittelbach** [comment]
Am 02.04.19 um 01:50 schrieb Will Robertson:
> I think a public \kernel_if_debug:TF function (or \debug_if_on:TF ??) 
> makes sense, as then package authors can then add similar branches in 
> their own code.

if we make it public which is probably good we should indeed drop the 
kernel prefix I guess.

**Comment by blefloch** [comment]
Yes.  Maybe \debug_if_enabled:TF because this is not about whether
debugging is on but only if it is available.

**Comment by u-fischer** [comment]
With such a test one would have to write 

```
\debug_if_enabled:T 
 {
  \debug_on:n {check-declarations}
 }
```

which looks a bit overcrowded. Could one combine this to e.g. 
`\debug_on_if_enabled:n {check-declarations}`? or perhaps `\debug_on_nocheck:n`?

**Comment by blefloch** [comment]
Actually, I question your use case.

Why put the debug_on in the package's source rather than in test files?
I would expect to see test files like

\RequirePackage[enable-debug]{expl3}
\ExplSyntaxOn
\debug_on:n { check-declarations , deprecation }
\ExplSyntaxOff
\RequirePackage{yourpackage}

and not to have test files like

\RequirePackage[enable-debug]{expl3}
\RequirePackage{yourpackage}

with some \debug_if_enabled_on:n inside yourpackage.

**Comment by u-fischer** [comment]
@blefloch The problem is that the package loads other (foreign) packages which uses expl3 and perhaps aren't faultless (currently I have a concrete problem with lipsum). So I want to enable debug mode only for my code (instead of loading all these package earlier in testfiles). Isn't this the main point of `\debug_on:n` to allow finer control of code parts it should affect?

**Comment by blefloch** [comment]
Fine.  Although it does mean that any test of a package that requires
yours will end up "debugging" your code as well.

**Comment by u-fischer** [comment]
@blefloch  after a night sleep I realized that if everyone uses `\debug_on_if_enabled:n` I would be back on square one as lipsum would interfere again.  So I think I will need an own boolean and do something like this in a test file (if simply enabling debugging directly doesn't work for some reason):


~~~~
\RequirePackage[enable-debug]{expl3}
\ExplSyntaxOn
\bool_new:N\l__mypackage_debug_on_bool
\debug_if_enabled:T{\bool_set_true:N\l__mypackage_debug_on_bool}
\ExplSyntaxOff
~~~~

and in the package enable debugging depending on my boolean. 

This means that boolean `\debug_if_enabled:TF` you suggested is imho the best idea.

**Comment by blefloch** [comment]
Then you don't need \debug_if_enabled:TF at all in your test file since
the test file either has the "enable-debug" option or does not have it.

I'm not totally sure when to most easily declare your boolean since it
also has to be declared in your package code, for end-users.

Depending on where in your package code you treat options, you could
have a package option "debug" that turns the boolean on from inside your
package rather than explicitly doing it in the test file.

**Comment by josephwright** [comment]
What's the conclusion here?

**Comment by wspr** [comment]
Reading back over the discussion, I’m no longer convinced about the use case here.

But I’m also a bit confused in general by what strategy we can use to selectively control debugging. I almost wonder if we need finer grained control, like check-declarations only for certain prefixes (a white or black list, perhaps).

OTOH having a sledgehammer debug approach is quite good because it really puts the onus on expl3 users to write proper code.

**Comment by car222222** [comment]
@wspr “having a sledgehammer debug approach is quite good because it really puts the onus on expl3 users to write proper code.”

Heh!  Whatever happened to “give them the tools”, or is that motto/aim from before your [LaTeX) time?

**Comment by car222222** [comment]
more fried tools than just a sledgehammer would be useful: to 
issue the metaphor, debugging is more like archeology than demolition !!

**Comment by car222222** [comment]
fried ==> refined   (unless in .Scotland, where they deep fry everything, including, it is said, Mars bars).
