### ISSUE TITLE
Property list

### ISSUE THREAD

**Issue by hvoss49** [latex3/latex3#606]
I played with the `\prop_??`  and stumbled into an endless loop. With the `\prop_get:NnNTF` the not defined property {b} is catched, but not with `\prop_get:NnN`. 

```
\documentclass{minimal}
\usepackage{expl3}
\begin{document}
\ExplSyntaxOn
\prop_clear:N \l_tmpa_prop
\prop_put:Nnn \l_tmpa_prop { a } { aa }

\tl_clear:N \l_tmpa_tl

\prop_get:NnNTF \l_tmpa_prop { a } \l_tmpa_tl %%OK
  { TRUE  : ~ \l_tmpa_tl }
  { FALSE : ~ \l_tmpa_tl }
\par 
\prop_get:NnNTF \l_tmpa_prop { b } \l_tmpa_tl %%OK
{ TRUE  : ~ \l_tmpa_tl }
{ FALSE : ~ \l_tmpa_tl }
\par 
\prop_get:NnN \l_tmpa_prop { a } \l_tmpa_tl  %%OK
\l_tmpa_tl
\par 
%\prop_get:NnN \l_tmpa_prop { b } \l_tmpa_tl  %% endless loop
%\l_tmpa_tl

\end{document}
```

up-to-date TL2019, pdflatex/xelatex/lualatex 

The log with the above code:

```
[voss@shania:~$ pdflatex -interaction=nonstopmode zzz6
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./zzz6.tex
LaTeX2e <2018-12-01>
(/usr/local/texlive/2019/texmf-dist/tex/latex/base/minimal.cls
Document Class: minimal 2001/05/25 Standard LaTeX minimal class
) (/usr/local/texlive/2019/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/local/texlive/2019/texmf-dist/tex/latex/l3kernel/expl3-code.tex)
(/usr/local/texlive/2019/texmf-dist/tex/latex/l3backend/l3backend-pdfmode.def))
 (./zzz6.aux) [1{/usr/local/texlive/2019/texmf-var/fonts/map/pdftex/updmap/pdft
ex.map}] (./zzz6.aux) )</usr/local/texlive/2019/texmf-dist/fonts/type1/public/a
msfonts/cm/cmr10.pfb>
Output written on zzz6.pdf (1 page, 12100 bytes).
Transcript written on zzz6.log.](url)
```

The log with uncommented lines:

```
voss@shania:~$ pdflatex -interaction=nonstopmode zzz6
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./zzz6.tex
LaTeX2e <2018-12-01>
(/usr/local/texlive/2019/texmf-dist/tex/latex/base/minimal.cls
Document Class: minimal 2001/05/25 Standard LaTeX minimal class
) (/usr/local/texlive/2019/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/local/texlive/2019/texmf-dist/tex/latex/l3kernel/expl3-code.tex)
(/usr/local/texlive/2019/texmf-dist/tex/latex/l3backend/l3backend-pdfmode.def))
 (./zzz6.aux)
```

then it hangs.  The last lines with `\tracingall`: 

```
[...]
__prop_split_aux:NnTF #1#2#3#4->\cs_set:Npn \__prop_split_aux:w ##1\__prop_pai
r:wn #2\s__prop ##2##3\q_mark ##4##5\q_stop {##4{#3}{#4}}\exp_after:wN \__prop_
split_aux:w #1\q_mark \use_i:nn \__prop_pair:wn #2\s__prop {}\q_mark \use_ii:nn
 \q_stop 
#1<-\l_tmpa_prop 
#2<-b
#3<-\tl_set:Nn \l_tmpa_tl {##2}
#4<-\tl_set:Nn \l_tmpa_tl {\q_no_value }
\cs_set:Npn ->\tex_long:D \tex_def:D 
{\long}
{\def}
{changing \__prop_split_aux:w=\long macro:#1\__prop_pair:wn a\s__prop #2#3\ETC.
}
{into \__prop_split_aux:w=\long macro:#1\__prop_pair:wn b\s__prop #2#3\ETC.}
{\expandafter}
\l_tmpa_prop ->\s__prop \__prop_pair:wn a\s__prop {aa}
\__prop_split_aux:w #1\__prop_pair:wn b\s__prop #2#3\q_mark #4#5\q_stop ->#4{\t
l_set:Nn \l_tmpa_tl {#2}}{\tl_set:Nn \l_tmpa_tl {\q_no_value }}
#1<-\s__prop \__prop_pair:wn a\s__prop {aa}\q_mark \use_i:nn 
#2<-
#3<-
#4<-\use_ii:nn 
#5<-
\use_ii:nn #1#2->#2
#1<-\tl_set:Nn \l_tmpa_tl {}
#2<-\tl_set:Nn \l_tmpa_tl {\q_no_value }
\tl_set:Nn #1#2->\cs_set_nopar:Npx #1{\exp_not:n {#2}}
#1<-\l_tmpa_tl 
#2<-\q_no_value 
{\edef}
{changing \l_tmpa_tl=macro:->aa}
{into \l_tmpa_tl=macro:->\q_no_value }
\l_tmpa_tl ->\q_no_value 
\q_no_value ->\q_no_value 
\q_no_value ->\q_no_value 
\q_no_value ->\q_no_value 
\q_no_value ->\q_no_value 
[ ... endless loop ...]

```

**Comment by josephwright** [comment]
By-design: the original set up didn't have the `TF` versions and a missing value is returned as `\q_no_value`. Almost all of these functions now offer `TF` variants, but the older behaviour is still supported: if you don't use the conditional, either you need to know 'no value' is impossible or test before using the `tl`.

**Comment by hvoss49** [comment]
I know that I can catch the problem by myself. But I was wondering about the endless loop. A
waning, an error, or nothing in the output  would be ok. But an endless loop??

**Comment by josephwright** [comment]
It's a consequence of using a quark as the return marker: they have infinite expansion.

**Comment by blefloch** [comment]
On 8/14/19 20:59, Joseph Wright wrote:
> It's a consequence of using a quark as the return marker: they have
> infinite expansion.

Could we plausibly change that?

E.g. by changing the definition of quarks a bit and making all N-type
quark tests test for the quark itself and for a tl containing the quark.

**Comment by FrankMittelbach** [comment]
@blefloch well we could I guess, but the quarks have really been meant to be as fast as possible as they have been the core tests in the low-level data structures. Maybe we should more strongly say that the non-TF versions should only be used if you really need them and otherwise leavethings as they are.

**Comment by PhelypeOleinik** [comment]
Or perhaps, in functions like `\prop_get:NnN`, return `\c_novalue_tl` instead of `\q_no_value`...

The user can then test with `\token_if_meaning_eq:NNTF` instead of `\quark_if_no_value:NTF` (or we could provide a `\tl_if_no_value:NTF` -- there is only a `:n` variant now). I don't think it would be a huge performance hit...

There is the backwards compatibility issue, though...

**Comment by FrankMittelbach** [comment]
Am 17.08.19 um 15:45 schrieb Phelype Oleinik:
> Or perhaps, in functions like |\prop_get:NnN|, return |\c_novalue_tl|
>  instead of |\q_no_value|...

that wouldn't work because the main point of quarks is that for testing
you get the same result
if the token to test "is" the quark and when it is hidden inside a
return tl which is why it would be necessary to do 2 tests also in this
case (like suggested by Bruno)

and testing against \c_novalue_tl means testing against a def that
contains several chars so that test should be much longer for TeX than
testing a quark


> The user can then test with |\token_if_meaning_eq:NNTF| instead of 
> |\quark_if_no_value:NTF| (or we could provide a |\tl_if_no_value:NTF|
> -- there is only a |:n| variant now). I don't think it would be a
> huge performance hit...
> 
> There is the backwards compatibility issue, though...

and that would really kills it  I would say if we alter the low-level here.

as for the performance hit I guess that really depends on how often
these tests are typically done, perhaps compared to other things this is
so seldom that it doesn't matter much, in which case we could use
Bruno's suggestion. On the other hand it clearly has a performance hit
on each an every document to avoid a programming error that may happen
but if that error happens it need to be corrected anyway (even if our
coding changes) the only difference is that it then gives a nicer error
(or in some sense perhaps worse, simply prints something instead of
producing a clear issue)

**Comment by josephwright** [comment]
I'm afraid this looks like 'by design' or at least 'we can't change this now' behaviour.
