### ISSUE TITLE
\cs_generate_variant:Nn does not like functions with 9 arguments

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#636]
The following MCE (where the `\demo_cmd` function has 8 arguments) compiles like a charm:
```
\documentclass{article}
\usepackage{expl3}
\ExplSyntaxOn
\cs_new:Nn \demo_cmd:nnnnnnnn
{
}
\cs_generate_variant:Nn \demo_cmd:nnnnnnnn { nVVVVVVV }
\ExplSyntaxOff
\begin{document}
Foo.
\end{document}
```
But the compilation of the following one (where the `\demo_cmd` function just has one extra argument) fails with the error message:
>Runaway argument?
\cs_if_exist_use:cF {__cs_generate_internal_V:NN}{\__cs_generate_internal_other
:NN \ETC.
! File ended while scanning use of \__cs_generate_internal_long:w.

```
\documentclass{article}
\usepackage{expl3}
\ExplSyntaxOn
\cs_new:Nn \demo_cmd:nnnnnnnnn
{
}
\cs_generate_variant:Nn \demo_cmd:nnnnnnnnn { nVVVVVVVV }
\ExplSyntaxOff
\begin{document}
Foo.
\end{document}

```
If I'm right, this MCE used to compile nicely in the past.

**Comment by blefloch** [comment]
Ouch, I recently changed \exp_args:N... to more often be generated as
commands with arguments like

\cs_new:Npn \exp_args:Nco #1#2#3
  {
    \exp_after:wN #1
    \cs:w #2 \exp_after:wN \cs_end:
    \exp_after:wN {#3}
  }

rather than

\cs_new:Npn \exp_args:Nco { \::c \::o \::: }

as in the past.  But variants of commands with 9 args need an
\exp_args:N... with 10 args, which breaks I suppose.  I'll investigate
tonight hopefully.
