### ISSUE TITLE
l3doc: Double entries in index

### ISSUE THREAD

**Issue by e-kwsm** [latex3/latex3#637]
This issue is originally reported in josephwright/siunitx#308 and still unresolved.

My environment is:
- l3build: Release 2019-09-25
- pdfTeX: Version 3.14159265-2.6-1.40.20 (TeX Live 2019)
- makeindex: version 2.15 [TeX Live 2019]
- l3doc: e0fd5380ae04727c879a71fcf55e6517d3621cc7
- siunitx: josephwright/siunitx@40fe821ab7583c6d7985f058d67c6783a354a5c7

Index of `siunitx.pdf` generated by `l3build doc` has double entries, e.g., `\num`:

![siunitx pdf:42](https://user-images.githubusercontent.com/11627708/65962098-e92e6200-e492-11e9-8cc8-7c8c65e1c38f.png)

**Comment by PhelypeOleinik** [comment]
This is not `l3doc`'s fault _only_. As Joseph said in the linked issue, MakeIndex thinks the entries are different because `doc`'s `\DescribeMacro` writes this:
```latex
\indexentry{num=\verb!*&\num&|hdclindex{2}{usage}}{2}
```
whereas `l3doc`'s `\cs` writes this:
```latex
\indexentry{num={\verbatim@font !\verb*&!\num&}|hdclindex{2}{usage}}{2}
```
and mixing both gives you two different entries.

`l3doc` is currently designed to work with `l3doc`'s features only, so `\DescribeMacro` is technically unsupported.

The plans are to make `l3doc` a package, so I see two options regarding this issue:

 1. Provide a `\DescribeExplMacro` (the name is unimportant here) command which will be the `l3doc` replacement of `\DescribeMacro`. Everything else would have undefined behaviour.

 2. Provide a `\ExplWriteIndexEntry` function which should be inserted by the package author in whatever macro they use to `\DescribeMacro` and would do the right thing.

The first option would provide a clear interface, while the latter would provide more flexibility at the expense of the package author having to hack that function in their documentation package of choice. Both would be a valid choice as well...

**Comment by josephwright** [comment]
This is an issue in the current `siunitx` docs: I will fix at that end as part of v3 work.
