### ISSUE TITLE
Property lists alter unicode content in 8-bit engines

### ISSUE THREAD

**Issue by sergiocallegari** [latex3/latex3#639]
Please consider the following snippet:

```
\documentclass{article}
\usepackage[italian,english]{babel}
\usepackage[unicode, bookmarks=true, bookmarksnumbered=true]{hyperref}
\usepackage[utf8]{inputenc}
\usepackage[artemisia]{textgreek}
\usepackage[LGR, T1]{autofe}
\usepackage{textcomp}

\usepackage{expl3}

\begin{document}

\section{First ΔΣM}
Bookmark OK.

\ExplSyntaxOn
\prop_put:Nnn \l_tmpa_prop {DSM}{ΔΣM}
\section{Second~\prop_item:Nn \l_tmpa_prop {DSM}}
\ExplSyntaxOff
Bookmark not OK

\ExplSyntaxOn
\tl_new:N \foo
\tl_set:Nn \foo { ΔΣM }
\section{Third~\tl_use:N \foo}
\ExplSyntaxOff
Bookmark OK

\end{document}
```

Compiling it with `pdflatex` you get an incorrect PDF bookmark when the property list is employed.

**Comment by PhelypeOleinik** [comment]
This is not an issue with `l3prop`, it's a `hyperref` thing. I'm not sure how fixable this is...  
The following reproduces the problem:
```latex
\documentclass{article}
\usepackage[unicode]{hyperref}
\usepackage[LGR,T1]{autofe}
\begin{document}
\section{First ΔΣM}
Bookmark OK.

\section{First \unexpanded{ΔΣM}}
Bookmark not OK.
\end{document}
```
The issue is that when `hyperref` passes the section title through `\pdfstringdef`, it eventually does an `\xdef` which will turn `ΔΣM` into `\83\224\83\243M`. With `\unexpanded`, that expansion never happens and `ΔΣM` survives furhter in the process and then ends up mangled in the bookmarks. This happens with `\prop_item:Nn` because, as the documentation says, the result is returned in `\exp_not:n` (`\unexpanded`) to prevent further expansion.

Meanwhile you could cheat and do the `x` expansion before the string is passed to `\section`:  
```latex
\use:x { \exp_not:N \section {Second~\prop_item:Nn \l_tmpa_prop {DSM}} }
```

**Comment by callegar** [comment]
Thanks for the explanation. Unfortunately, this behavior makes the `acro` logic for dealing with bookmarks broken. To fix this, cheating *outside* of `\section` is obviously impossible. One needs a way to get the needed expansion wrapping only the `\prop_item:Nn \l_tmpa_prop {DSM}` inside the sectioning command. Would it be possible to do so? Alternatively, would it make sense to offer an alternative to `\prop_item` not blocking the expansion?

**Comment by josephwright** [comment]
The entire `expl3` set up is based around well-defined expansion of material: here, we've been very careful that one can use `\prop_item:Nn` that way. I guess the issue is that `hyperref` has never explicitly said that the section argument is _expanded_ either before or after escaping: a 'new' implementation would readily do that.

**Comment by josephwright** [comment]
We (team) have wondered a little about the use of `\exp_not:n` in these places, but it's tricky to alter now ...

**Comment by PhelypeOleinik** [comment]
`\use:x` has to be outside because it won't expand. `\use:e` will :-)
```latex
\section {Second~\use:e { \prop_item:Nn \l_tmpa_prop {DSM} } }
```

**Comment by josephwright** [comment]
Just to point out the the native `expl3` string-conversion code has no issue with `\exp_not:n`:
```latex
\ExplSyntaxOn
\prop_put:Nnn \l_tmpa_prop { DSM } { ΔΣM }
\exp_args:NNx \str_set_convert:Nnnn \l_tmpa_str 
  { \prop_item:Nn \l_tmpa_prop {DSM} } { utf8 } { utf16be/string }
\str_show:N \l_tmpa_str
```
yields `\003\224\003\243\000M`, identical to the result in the correct lines in the `.out` file.

**Comment by josephwright** [comment]
I'm going to close here as this is something that we likely don't want to move to `hyperref` either: it will get fixed 'over time' but as part of bigger plans.

**Comment by FrankMittelbach** [comment]
Given @PhelypeOleinik's last post there is already now a general solution by using `\use:e` around the return value. That should be generally applicable to all expandable code that returns the result inside `\exp_not:n`, shouldn't it? And it would also work for non-expandable returns.

**Comment by PhelypeOleinik** [comment]
I wouldn't call that a solution, but a hack. I'm not sure if this can be safely applied
generally: this is one case where expansion is wanted because `hyperref` expects
that. Another case it would be okay would be for typesetting. But in other cases
it would break (like when doing `\tl_put_right:Nx \l_tmpa_tl { <...> }`).

**Comment by FrankMittelbach** [comment]
well, our documentation claims that all our return values come wrapped in \exp_not:n{...}
So it should be always possible to use \use:e around them (in code). If we have been obeying our rule I would think. And for non-expandable commands you get the result in some tl back and you can reassign that to  itself via \tl_set:Ne or should be. Any flaw in that approach that you can see?

**Comment by PhelypeOleinik** [comment]
Yes, if you want to allow further expansion (as in the case at hand), then yes,
adding `\use:e` will do the trick. The problem that I see with adding `\use:e`
by default in the expandable functions is in situations like this:
```latex
\ExplSyntaxOn
\prop_put:Nnn \l_tmpa_prop {DSM} {ΔΣM}
\tl_set:Nx \l_tmpa_tl { \prop_item:Nn \l_tmpa_prop {DSM} }
\tl_show:N \l_tmpa_tl % Okay
\tl_set:Nx \l_tmpa_tl { \use:e { \prop_item:Nn \l_tmpa_prop {DSM} } } % Explodes
\stop
```
so it has to be used in a case-by-case basis, as far as I can tell.

**Comment by FrankMittelbach** [comment]
yes of course it does, but that always an issue if you pass stuff on into x expansion and it isn't protected. My point is that it is a generic method to use a return value and allow it to further expand later. Of course, you then need to ensure that whatever comes along this way is allowed to expand, but  that's the programmers task
