### ISSUE TITLE
\tl_upper_case:n errors with commands let to a char

### ISSUE THREAD

**Issue by u-fischer** [latex3/latex3#648]
~~~~
\documentclass{article}
\usepackage{expl3}
\begin{document}
\let\mychar!
\ExplSyntaxOn
 \tl_upper_case:n {ab\mychar}
\ExplSyntaxOff

\end{document}
~~~~

gives

~~~~

! Improper alphabetic constant.
<to be read again> 
                   \mychar 
l.241  \tl_upper_case:n {ab\mychar}
~~~~

See also https://github.com/latex3/hyperref/issues/63 and https://tex.stackexchange.com/questions/516819/how-to-capitalize-letter-using-uppercase-that-has-been-assigned-to-let-or-t

**Comment by josephwright** [comment]
Well that doesn't count as a piece of 'text', so my basic position is 'tough, this is not valid input'.

**Comment by josephwright** [comment]
I guess there should at least be a controlled error, but I can almost certainly get things working if we _really_ want

**Comment by u-fischer** [comment]
@josephwright the problem is that unicode-math uses this in a number of places. E.g. `\euro` breaks with the same error. Do you think that is a "don't do it"?

**Comment by josephwright** [comment]
@u-fischer  Well, it is a _bit_ tricky, as the `expl3` code is written for 'new' input, where we'd expect to be able to use the UTF-8 char directly ... However, I'm happy to take a look at this.

**Comment by davidcarlisle** [comment]
@josephwright  we should probably make them work or have some guidelines not to do it, the same thing comes up in several unicode-math issues eg https://github.com/wspr/unicode-math/issues/498
 `\chardef\mychar\`\!` works better in most cases but both don't (unless we adjust code elsewhere) work well in `\typeout` etc so something expandable like `\def\mychar{!}`  is going to be better, so if there is a big run time cost to catching implicit characters I think documenting this would be OK.

**Comment by josephwright** [comment]
One question: which implicit tokens do we want to cover? Picking up letters/other chars is not too bad, picking up every `\meaning` gets a bit tedious, unless there is a better plan?

**Comment by davidcarlisle** [comment]
not doing it at all is still a possibility I think but if you do support `\let\zza=a` I think you should probably support `\chardef\xxa=``\a` as well any other `\meaning` probably don't make sense in a case changing context.

But non expandable letters cause problems elsewhere not just case changing, eg pdf bookmarks, or filename handling, so explicitly not supporting them as character data everywhere might be preferable to having to support them everywhere.

Although if we had an expandable function that stepped through a token list and replaced every implicit character or chardef token by its associated character token, then it could be used in all these places, I suppose.

**Comment by u-fischer** [comment]
@josephwright  I'm still unsure if this should be fixed or if we should document it as "don't do it" (@wspr could perhaps say how much work it would mean for unicode-math to adhere to such a guideline and how useful implicit tokens are). 

As David says: imho it would be only useful to tackle this, if it is done so that one can reuse it the bookmarks/pdf code too. 

Side remark: \bgroup/\egroup fail too, but these two works in \pdfstringdef, they are handle there especially.

**Comment by josephwright** [comment]
I was thinking of `\let\mathdollar=$` or whatever: do we cover that (`$` is allowed)? `\bgroup`/`\egroup` don't really make sense in 'text' so we could skip them.

Basically, I'm trying to get a feel for how complex this needs to be: it is all doable. (Does anyone have a good trick here for picking up all implicit tokens, rather than using `\meaning`?)

**Comment by davidcarlisle** [comment]
On Mon, 18 Nov 2019 at 14:20, Joseph Wright <notifications@github.com>
wrote:

> I was thinking of \let\mathdollar=$ or whatever: do we cover that ($ is
> allowed)? \bgroup/\egroup don't really make sense in 'text' so we could
> skip them.
>
> Basically, I'm trying to get a feel for how complex this needs to be: it
> is all doable. (Does anyone have a good trick here for picking up all
> implicit tokens, rather than using \meaning?)
>

If you want to avoid `\meaning` unless you know it's a character then you
can do



\let\zzz=a

\if\relax\noexpand\zzz \show\notcharacter \else \show \character \fi

\let\zzz=\hbox

\if\relax\noexpand\zzz \show\notcharacter \else \show \character \fi

\bye

>
>

**Comment by josephwright** [comment]
@davidcarlisle  Yeah, but no, because it's wrong for e.g. `\let\mathdollar=$`: that's not a char, but the test things it is ...

**Comment by davidcarlisle** [comment]
well `\mathdollar` is an implicit character token  at which point you look
at its \meaning and find it's a math shift so it's not wrong just doesn't
filter out everything, it would be good if, after \if\relax told you it was
an implicit or explicit character token you could work out what character
it was without having to dissect \meaning, but I don't think you can.

**Comment by blefloch** [comment]
You don't have to look at the \meaning explicitly I think, only at the
\string.

    \group_begin:
    \char_set_catcode_active:n { 0 }
    \prg_new_conditional:Npnn \token_if_explicit_char:N #1 { TF }
      {
        \if_cat:w \scan_stop: \exp_not:N #1
          \prg_return_false: \exp_after:wN \use_none:nn
        \else:
          \if_cat:w \exp_not:N ^^@ \exp_not:N #1
            \prg_return_false: \exp_after:wN \use_i:nnn
          \fi:
        \fi:
        \use:n
          {
            \if_cat:w ^ \str_tail:o { \token_to_str:N #1 } ^
              \if:w \token_to_str:N #1 #1
                \prg_return_true:
              \else:
                \prg_return_false:
              \fi:
            \else:
              \prg_return_false:
            \fi:
          }
      }
    \group_end:

The code does the following tests:

1. TRUE for control sequences that are not implicit characters.

2. TRUE for active characters that are not implicit characters. So after
these tests we know we have an explicit or implicit character token, in
particular we can be sloppy with nesting of TeX conditionals since TeX's
primitive conditionals have been filtered out.

3. TRUE for explicit characters and for active characters and, if
\endlinechar is out of bounds, for single-character control sequences.
Note that \token_to_str:N is important as otherwise explicit macro
parameter characters would get doubled and give FALSE instead.

4. TRUE if the single character of the string representation coincides
with the meaning: this catches cases like \catcode`*=13\let*=X.

Untested, please check.  The code mistakenly claims we have an explicit
character if #1 is an active character (or single-letter control
sequence when \endlinechar is out of range) let equal to the same
character with a non-active catcode, like in \endlinechar-1\let\** or in
\let\star*\catcode`*13\let*\star.  This is not a problem for the
application here, since we simply want `#1 to be a valid alphabetic
constant (and have the right value).  More generally one could simply
act with \string on #1 to get the suitable non-active character token
(but with catcode other).

The test could be made to return false also in slightly more subcases
where it currently mistakenly returns true, by checking that
\tl_to_str:n {#1} is what one would expect of an explicit character.  I
won't go into details as the set of cases gets really hairy (the most
complicated one is that "\detokenize{\ }" gives two spaces after
"\endlinechar-1\catcode` 6\let\ = \catcode` 11\relax", just like an
explicit "\catcode` 6\relax" space).  We could also get slightly more
information by checking if the active char with character code equal to
#1 is let to #1, and likewise check the one-character control sequence
(if \endlinechar is out of bounds).

**Comment by davidcarlisle** [comment]
Bruno,

> You don't have to look at the \meaning explicitly I think, only at the
> \string.

Maybe I don't follow your code correctly but if after \let\zzz=a  and you
have  found that \zzz is an implicit character token, how do you use
\string rather than \meaning to find that it is  an a so you can uppercase
it?

**Comment by josephwright** [comment]
@davidcarlisle  I think the idea was that the test is generic, then to recover the meaning I'd still use `\meaning`, but only when it's required

**Comment by josephwright** [comment]
@davidcarlisle  That presumably could be documented as only for a subset of cases. Still leaves me with an issue about `\chardef`.

**Comment by davidcarlisle** [comment]
On Mon, 18 Nov 2019 at 16:57, Joseph Wright <notifications@github.com>
wrote:

> @davidcarlisle <https://github.com/davidcarlisle> I think the idea was
> that the test is generic, then to recover the meaning I'd still use
> \meaning, but only when it's required
>
>
>
er yes but that's exactly what I suggested, but Bruno quoted me and said to
use \string:-), but  OK yes I think that is agreed the best you can do.

but if you start making \chardef work as well then you can't use that
filter for implicit tokens and you have to look at \meaning always.  and
for pdfstrings (if less so for uppercasing) you probably want to do
\(U)mathchardef as well.

I think I'd be tempted to not support it by default but offer a possibly
slow function that can be used to make a best-effort attempt to turn as
many tokens as possible into character tokens.

**Comment by blefloch** [comment]
I messed up by nesting conditionals in the first part of my code.
Change the \if_cat:w \scan_stop: ... \fi: part to the following ugly
code or equivalent cleaner code.

        \if_cat:w \scan_stop: \exp_not:N #1
          \prg_return_false: \exp_after:wN \use_none:nnnn
        \fi:
        \use:n
        {
          \if_cat:w \exp_not:N ^^@ \exp_not:N #1
            \prg_return_false: \exp_after:wN \use_none:nn
          \fi:
        }

> Maybe I don't follow your code correctly but if after \let\zzz=a and you
> have found that \zzz is an implicit character token, how do you use
> \string rather than \meaning to find that it is an a so you can uppercase
> it?

Ah, right, I was too focussed on detection and not on how to extract the
correct char.  Then yes, you need to use \meaning, but only for these
implicit chars, so that's not too bad in terms of speed.

Really, the question is not to have a \token_if_char:NTF like I wrote,
but rather a \token_to_explicit:N which expands to \exp_not:N #1 if #1's
meaning is not a character, and otherwise expands to an explicit
character.  The following should correctly treat implicit chars and
\chardef'd tokens.

    \group_begin:
    \char_set_catcode_active:n { 0 }
    \cs_new:Npn \token_to_explicit:N #1
      {
        \if_cat:w \exp_not:N #1
                \if_cat:w \scan_stop: \exp_not:N #1
                  \scan_stop:
                \else:
                  \exp_not:N ^^@
                \fi:
          \exp_after:wN \@@_to_explicit_cs:N
        \else:
          \exp_after:wN \@@_to_explicit_char:N
        \fi:
        #1
      }
    \group_end:
    \cs_new:Npn \@@_to_explicit_char:N #1
      {
        \if:w
          \if_cat:w ^ \str_tail:o { \token_to_str:N #1 } ^
            \token_to_str:N #1 #1
          \else:
            AB
          \fi:
          \exp_after:wN \exp_not:n
        \else:
          \exp_after:wN \@@_to_explicit_implicit:n
        \fi:
        {#1}
      }

While the two functions above run for every character, the following
code is only needed for control sequences.

    \cs_new:Npn \@@_to_explicit_cs:N #1
      {
        \exp_after:wN \if_meaning:w \exp_not:N #1 #1
          \exp_after:wN \@@_to_explicit_cs_aux:N
        \else:
          \exp_after:wN \exp_not:N
        \fi:
        #1
      }
    \cs_new:Npn \@@_to_explicit_cs_aux:N #1
      {
        \token_if_chardef:NTF #1
          {
            \char_generate:nn {#1}
              { \char_value_catcode:n {#1} }
          } % works!
          {#1}
      }

The rest of the code is for implicit character like \bgroup, so we don't
need to optimize much.  We need to extract the character from the
meaning.  First get the catcode (1,2,3,4,6,7,8,10,11,12), then get the
character code by either removing stuff from the \meaning until
"character " (for catcode <9) or removing the first two
(space-delimited) words (for catcode >9).  When getting the catcode we
detect alignment tabs (catcode 4) by elimination to avoid needing proper
\group_align_safe_begin: /end.

    \cs_new:Npn \@@_to_explicit_implicit:n #1
      {
        \exp_after:wN \@@_to_explicit_auxii:w
        \int_value:w
          \if_cat:w \c_group_begin_token #1 1 \else:
          \if_cat:w \c_group_end_token #1 2 \else:
          \if_cat:w \c_math_toggle_token #1 3 \else:
          \if_cat:w ## #1 6 \else:
          \if_cat:w ^ #1 7 \else:
          \if_cat:w \c_math_subscript_token #1 8 \else:
          \if_cat:w \c_space_token #1 10 \else:
          \if_cat:w A #1 11 \else:
          \if_cat:w + #1 12 \else:
          4 \fi: \fi: \fi: \fi: \fi: \fi: \fi: \fi: \fi:
        \exp_after:wN ;
        \token_to_meaning:N #1 \q_stop
      }
    \cs_new:Npn \@@_to_explicit_auxii:w #1 ; #2 \q_stop
      {
        \char_generate:nn
          {
            \if_int_compare:w #1 < 9 \exp_stop_f:
              \exp_after:wN \@@_to_explicit_auxiii:w
            \else:
              \exp_after:wN \@@_to_explicit_auxiv:w
            \fi:
            #2
          } {#1}
      }
    \exp_last_unbraced:NNNNo \cs_new:Npn \@@_to_explicit_auxiii:w
      #1 { \tl_to_str:n { character ~ } } { }
    \cs_new:Npn \@@_to_explicit_auxiv:w #1 ~ #2 ~ { }

I hope I didn't miss any branch.

**Comment by josephwright** [comment]
@blefloch  Looks pretty good: I've added to the team meeting agenda for discussion. Probably we should add this: it's a general issue and if we can smoothly handle implicit chars, it would be good.

**Comment by blefloch** [comment]
Note that a function to apply this code to every token (well, every
token except explicit spaces and catcode 1,2 tokens of course) might not
be very useful, as it is useful to have an exception list a bit like for
case-changing: there are situations (like keeping math input as is for
audio processing, say) where an implicit char or a \chardef should be
left alone I suppose.

**Comment by blefloch** [comment]
Yes, which is a case where you have an N-type token and just want to
pass it (alone) to the code I wrote.  I'm just saying that an n-type
function that deals with whole token lists isn't needed for your
application, and probably more generally too.

**Comment by josephwright** [comment]
This is fixed in `l3text`: once we decide to merge, I'll close here.

**Comment by josephwright** [comment]
For reference, and to allow GitHub to link: https://github.com/latex3/latex3/pull/654

**Comment by josephwright** [comment]
PR now merged.
