### ISSUE TITLE
Overfull \vbox in Interfaces' documentation

### ISSUE THREAD

**Issue by dbitouze** [latex3/latex3#666]
Page 257 of Interfaces' documentation (2020-01-22 release) suffers from an "Overfull \vbox".

**Comment by josephwright** [comment]
Quite possibly: it's all built automatically.

**Comment by PhelypeOleinik** [comment]
I'm aware of that. `l3doc` typesets an entire `function` environment in a single `\vbox`,
then if the description happens to be rather long, that happens. I think `l3doc` could
use some heuristics to allow page breaking in a `function` environment if it's too long.
The way it is now is not okay...

**Comment by wspr** [comment]
@PhelypeOleinik The root cause of this is that the documentation uses coffins to do the layout. The logic might be able to be re-written from scratch without coffins, but the easy solution here is to just keep `function` blocks fairly short and add further explanatory paragraph text after the formal function definition.

**Comment by FrankMittelbach** [comment]
I think the coffin implementation as such is fine and the fact the syntax and core explanation is supposed to be on the same page (in a box) is fine too. The problem seems to me that there is often (alawys?) some add-on explanation that belongs to the syntax block but should/could again be in a normal galley flow and that you may want to have control over its start and its end. That is not really supported and it might need some syntax extension/change. Maybe as simple as
```
\begin{function}
...
\explanation
...
\end{function}
```
where the first `...` is the core part that is boxed with the syntax and the second is not.

**Comment by Skillmon** [comment]
> ```
> \begin{function}
> ...
> \explanation
> ...
> \end{function}
> ```

I like the idea, but would argue that `\explanation` is an ambiguous name. Maybe something like `\moreinfo` is clearer.

**Comment by josephwright** [comment]
One for https://github.com/latex3/latex3/issues/1136
