### ISSUE TITLE
\l_keys_key_tl is a string (all tokens have cat code "other")

### ISSUE THREAD

**Issue by callegar** [latex3/latex3#668]
In trying to work with l3keys2e, I have noticed that `\l_keys_key_tl` is not the original token list passed as an argument, but more of a string, with all tokens set to catcode *other*.

This means that it cannot be re-used as an argument for things like `\PassOptionsToClass` or `\PassOptionsToPackage`, because the thing being passed ends up not matching with the options expected by the Class or Package which is the same in terms of character codes, but not in terms of the category codes associated to the characters.

I don't know if this is an expected behavior or a bug.

On a side note, it looks like when using l3keys2e you can use `\CurrentOption` in the `l3keys` option handling code. This is undocumented in l3keys2e, but handy, because in `\CurrentOption` the catcodes are correct.

**Comment by josephwright** [comment]
The documented behaviour of `l3keys` is that the key name is treated as a string; this is necessary as keys are ultimately used inside a `\csname` . The current docs say

> The _name_ of the key is the part of the path after the last `/`, and thus is not unique.
In the preceding examples, both keys have name key-a despite having different paths.
This information is stored in `\l_keys_key_tl`, and will have been processed by `\tl_to_str:n`.

(Since introduction of `l3str`, this could perhaps mean that we should move to `\l_keys_key_str`: I'll raise with the team.)

There's no special handling of `\l_keys_key_tl` by `l3keys2e` beyond what the core `l3keys` code does, so this propagates.

Using `\CurrentOption` is part of the documented behaviour of LaTeX itself, which `l3keys2e` doesn't interfere with. I can document that it remains available; perhaps best?

**Comment by josephwright** [comment]
Other team members: I'd appreciate thoughts here on whether we should switch to providing `\l_keys_key_tl` as `\l_keys_key_str`.

**Comment by blefloch** [comment]
It might make sense to provide both: the tl storing the key as given by
the user, and the str storing it for other purposes (maybe only needed
by the l3keys internals?).  As long as keys are only ever compared as
strings this should be ok.

Note that a tl's string representation can change according to values of
various parameters at the time the tl is turned to a string
(\escapechar, of course, but also some \catcode values that determine
whether a space is added after one-character control sequences).

**Comment by josephwright** [comment]
@blefloch Detokenization happens pretty early in the processing: all the paths are space-trimmed and detokenized when searching. Moreover, the documented behaviour of `\l_keys_key_tl` has been this way since the first release of the code: I'm not sure we can change it now.

**Comment by blefloch** [comment]
Probably right.

Perhaps we could instead make the LaTeX2e option code insensitive to
catcodes, perhaps by changing \@process@ptions?

**Comment by josephwright** [comment]
@blefloch Same issue only more so! I suspect the best is to document in `l3keys2e` that treatments are different, so a choice of `\CurrentOption` or `\l_keys_key_tl` may be required depending on the use case.

**Comment by blefloch** [comment]
The drawback of saying "use \CurrentOption" is that this is not split at
the equal sign into key and value.  Maybe we need concrete use cases?

I think a combined change of \@process@ptions, \@declareoption and
\@use@ption may be workable, changing the \@unusedoptionlist and
\@declaredoptions token lists into strings.

The main user-visible change would be that catcodes are ignored in
options.  Now obviously the main problem is that many packages hook into
this area.

**Comment by josephwright** [comment]
@blefloch The main use case I can think of is passing and unknown key/value pair 'onward'. That just needs `\CurrentOption`. It's hard to imagine a case where you'd want to pass an unknown key but not any value it also has, whilst if the key is known, you can code the name directly so avoid the catcode business.

**Comment by blefloch** [comment]
Ah, good point that if you know the key you can just use it.  Then it's
probably just worth documenting, as you were saying.

**Comment by sergiocallegari** [comment]
After reading the discussion, my impression (in fact, my *humble* impression) is that @josephwright is probably right in saying that the reasonable use case is passing and unknown key/value pair 'onward' which is precisely my case. For this usage, just better documenting the possibility to use `\CurrentOption` is perfectly sufficient. I say this about the documentation because even if the possibility now appears obvious, it took me a good amount of time to discover it. Furthermore, for passing options onward, you generally do not need the split at the equal sign.

However, for cleanness, I think that it would be good to rename `\l_keys_key_tl` to `\l_keys_key_str` (because it is actually a string) and *alias* it to `\l_keys_key_tl` for compatibility with previous users (at least for some deprecation time), now putting `\l_keys_key_str` in the main documentation and the compatibility alias as a note. This would make it immediately clear that you cannot use it as a way to pass options to legacy packages, because the key has somehow been processed.

Incidentally, I suspect that the *value* part may also be a string.

**Comment by josephwright** [comment]
@sergiocallegari OK, I'll look to do a bit of re-arranging. 

The value isn't a string: that can contain arbitrary TeX code so is never processed other than space/brace removal.

**Comment by sergiocallegari** [comment]
OK, excellent. And as usual **thanks**! Looks to me that every time I need to report something here I also get to learn something!

**Comment by zauguin** [comment]
@josephwright Maybe it would make sense, especially for debugging output, to provide an equivalent of `\CurrentOption` in l3keys. So some token list which contains the original module, key and value without any processing applied. That could be used as a replacement for `\CurrentOption` in l3keys2e but also make similar things possible in a more generic context.

**Comment by josephwright** [comment]
@zauguin Sure, we can happily add a 'raw' version; like I've said to Bruno, probably with hindsight `\l_keys_key_tl` could have been that, but not at this stage.

**Comment by blefloch** [comment]
Even with hindsight what @zauguin suggests is not \l_keys_key_tl but
rather the whole keyval.

**Comment by FrankMittelbach** [comment]
> Other team members: I'd appreciate thoughts here on whether we should switch to providing `\l_keys_key_tl` as `\l_keys_key_str`.

with str being a formal module it would be rather consistent to do so in my opinion. Of course, there is the burden of deprecation but still ...

**Comment by FrankMittelbach** [comment]
> It might make sense to provide both: the tl storing the key as given by the user, and the str storing it for other purposes (maybe only needed by the l3keys internals?). As long as keys are only ever compared as strings this should be ok.

not sure this is a good idea: right now the tl is the str so now making it the raw version (while conceptually sound) would enable packages using it continue to use it without any immediate noticable problem until some special input hits them and then the error will be really weird most likely. Furthermore if the raw value is kept available in \CurrentOption (or elsewhere) then that would be good enough to do anything with it if someone is desparate enough. Given that the "official" process doesn't need the raw key  and we don't have much of a use case that needs the raw key only, I don't think we should provide it at this stage.

**Comment by FrankMittelbach** [comment]
>  Perhaps we could instead make the LaTeX2e option code insensitive to catcodes, perhaps by changing \@process@ptions?

even simpler changes than that have shown that you break half of LaTeX because every different keyval handler hooks into that process at different levels. There is really on solution and that is basically a single new approach that disallows all (or most) others and then bite the bullet and ensure that all other key/val handlers get updated at the same time to hook into that interface. Big job but probably doable, but nothing you can do 10 times  a) fixing spacing b) fix catcodes c) fix ...
@davidcarlisle tried with the simple zapspace fix and retracted seeing hat happened and it is (unfortunately) not surprising

**Comment by josephwright** [comment]
@FrankMittelbach OK, I'll sort the deprecation and new documentation

**Comment by lvjr** [comment]
> [blefloch]: It might make sense to provide both: the tl storing the key as given by the user, and the str storing it for other purposes (maybe only needed by the l3keys internals?). As long as keys are only ever compared as strings this should be ok. 

> [FrankMittelbach]: Given that the "official" process doesn't need the raw key and we don't have much of a use case that needs the raw key only, I don't think we should provide it at this stage.

Actually, `tabularray` package is using raw keys everywhere, and it has to use `\tl_set_rescan:Nnn` to get the raw key from `\l_keys_key_str` every time (not sure whether or not it is reliable all the time).

For example, in a tabular, column specification `b{2cm}` is mapped to `Q[b,2cm]` and needed to be treated as `Q[valign=b,wd=2cm]`. So `tabularray` has to treat the unknown key `2cm` as `wd=2cm`. We don't need `\tl_set_rescan:Nnn` in this case, but we really need `\tl_set_rescan:Nnn` for column specification `b{\linewidth}`.

**Comment by josephwright** [comment]
@lvjr But key names are always strings because they are used ultimately in `\csname ...\endcsname` (so the catcode _cannot_ be important), and something like `\linewidth` in a key _name_ is a string `\`, `l`, `i`, `n`, etc.
