### ISSUE TITLE
\file_input:n leaves an empty line when using with longtable

### ISSUE THREAD

**Issue by stone-zeng** [latex3/latex3#684]
Consider the following example:

```tex
% test.tex
\documentclass{article}
\usepackage{expl3,longtable}

\begin{document}

\makeatletter
\ExplSyntaxOn

\verb|\file_input:n|
\begin{longtable}{|ccc|}
  \hline\endfoot
  \file_input:n{data.tex}
\end{longtable}

\verb|\input|
\begin{longtable}{|ccc|}
  \hline\endfoot
  \input{data.tex}
\end{longtable}

\verb|\@@input|
\begin{longtable}{|ccc|}
  \hline\endfoot
  \@@input{data.tex}
\end{longtable}

\ExplSyntaxOff
\makeatother

\end{document}
```

```tex
% data.tex
1 & 2 & 3 \\
```

When complied with pdflatex (or other engines), it gives

![image](https://user-images.githubusercontent.com/18233088/76007579-3bdfde80-5f49-11ea-99ca-e657fdaddcd3.png)

Note that there is an empty line when using `\file_input:n`. If remove the `\\` in `data.tex`, then all three methods gives the same results, i.e. no such empty line.

Version of LaTeX3: 2020-02-25

**Comment by blefloch** [comment]
This is the usual problem with \\ followed by non-expandable material at
the end of a table.  The issue here is that \__file_input:n calls the
non-expandable \__file_input_pop: after reading the file.

Crazy idea (not completely serious): Make \g__file_stack_seq local
instead of global.  Instead of popping it, raise a flag (this can only
be done locally).  When retrieving information, take the flag into
account to know how many items to pop.  This would break
\g_file_curr_dir_str etc, but that data could still be available
expandably, just not directly as strings.

**Comment by davidcarlisle** [comment]
@josephwright  we did discuss at one point adding a `\RawInput` (`\let` to `\@@input) to give an expandable input skipping hooks and other processing. Especially now the primitive accepts `{...}` this might be useful here

**Comment by josephwright** [comment]
@davidcarlisle  So `\file_input_raw:n` or `\file_input_unhooked:n` or similar at an `expl3` level?

**Comment by davidcarlisle** [comment]
@josephwright  yes

**Comment by PhelypeOleinik** [comment]
That's issue latex3/latex2e#514

**Comment by josephwright** [comment]
> That's issue [latex3/latex2e#514](https://github.com/latex3/latex2e/issues/514)

Related but not the same: I think it's easier to argue for this at the `expl3` level in the first place, as it's where we expect people to be using a programmer's API and to have some understanding of what the API docs mean.
