### ISSUE TITLE
Feature Request: \tl_if_eq:Nn

### ISSUE THREAD

**Issue by Vidabe** [latex3/latex3#691]
I've found myself quite often trying to compare a token list with some tokens and it always suprised me that `\tl_if_eq:Nn` is not a thing. Is there are reason for that?
I know that I can just use

    \tl_set:Nn \l_tmpa_tl {<tokens>}
    \tl_if_eq:NNTF \l_token_list_tl \l_tmpa_tl ...

or 

    \cs_generate_variant:Nn \tl_if_eq:nn { V }
    \tl_if_eq:VnTF \l_token_list_tl {<tokens>} ...

But the second is just odd if you know that the arguments are then restored in tl's internally;
and the first kinda feels unnecessary complicated if `<tokens>` is just pretty much a one-time use in a code.

**Comment by tail-reversion** [comment]
In my understanding, the function `\tl_if_eq:Vn` is the appropriate choice for the use case described.

**Comment by blefloch** [comment]
On 3/27/20 2:02 PM, Kelly Smith wrote:
> In my understanding, the function |\tl_if_eq:Vn| is the appropriate
> choice for the use case described.

Well, \tl_if_eq:Vn is certainly correct conceptually, but it's quite
wasteful to expand and store back for the comparison itself.  We could
well provide \tl_if_eq:Nn IMO.

**Comment by josephwright** [comment]
Most of the time, `\str_if_eq:Vn(TF)` is what you want: do your really need to test category code?

**Comment by car222222** [comment]
But the \str_if_eq:... functions first convert both token lists into strings:
“Compares the two 〈token lists〉 on a character by character basis (namely after converting them to strings).”
Is this conversion not a big overhead?

Also, the OP write about comparing code, so maybe he is interested in the tokens rather than the characters?

**Comment by josephwright** [comment]
@car222222 The conversion is 'internal' but essentially the same as `\detokenize`, so it's obviously got a time requirement but is not particularly slow. I don't see an explicit mention of 'code' in terms of the 'test material' in the initial post, but you may be right: that's why I asked if catcodes are significant.

**Comment by josephwright** [comment]
To be clear, I've no issue with the request: this is an easy change and is well within scope. I just wonder if the choice of function takes account of the `str` module.

**Comment by Vidabe** [comment]
> To be clear, I've no issue with the request: this is an easy change and is well within scope. I just wonder if the choice of function takes account of the `str` module.

 I have to admit, I did not. I rechecked my cases and category codes don't (or shouldn't) matter. I am actually not always sure when to use strings, so I kinda forget that they exists (maybe a link to `\str_if_eq` at the documentation of `\tl_if_eq` may be useful).
