### ISSUE TITLE
l3text: Dotted capital i

### ISSUE THREAD

**Issue by moewew** [latex3/latex3#697]
I know it's a bit unfair to expect the generic (non-Turkish) case changer to do something sensible with the capital dotted İ, so feel free to ignore this.

Consider
```latex
\documentclass{article}

\usepackage{iftex}
\iftutex
\else
\usepackage[T1]{fontenc}
\fi

\usepackage{expl3}[2020/04/06]

\ExplSyntaxOn
\newcommand*{\test}{\text_titlecase:n}
\ExplSyntaxOff

\begin{document}
\test{Dotted İi and Dotless Iı}
\end{document}
```
With pdfLaTeX I get

> Dotted İi and dotless iı

but the Unicode engines give
> ![a double-dotted i](https://user-images.githubusercontent.com/6755835/78756946-f5343880-797b-11ea-97aa-620d3b3a53f2.png)

**Comment by josephwright** [comment]
I'll take a look; it's possible I missed a few cases that are workable in T1.

**Comment by moewew** [comment]
In this case I actually think the pdfLaTeX behaviour is not completely bonkers: The capital dotted İ is hard to deal with in a non-Turkish context. I'm more worried about the weird double-dot I get from the Unicode engines, though the result gets better with a different font:
```latex
\documentclass{article}

\usepackage{iftex}
\iftutex
\else
\usepackage[T1]{fontenc}
\fi
\usepackage{libertinus}

\usepackage{expl3}[2020/04/06]

\ExplSyntaxOn
\newcommand*{\test}{\text_titlecase:n}
\ExplSyntaxOff

\begin{document}
\test{Dotted İi and Dotless Iı}
\end{document}
```

**Comment by josephwright** [comment]
The double-dot is mandated by the standard Unicode settings; really it's down to the font shaper to pick this up and give the right output.

**Comment by car222222** [comment]
@josephwright   What does this mean? — please!
“The double-dot is mandated by the standard Unicode settings”  
What standard settings, and what are they settings for/of??  
And what slot is this ’double-dot’?

Please explain clearly what Unicode slots you are referring to.

**Comment by wspr** [comment]
I’m not has deep in this area as Joseph but my understanding is that if you have uppercase dotted I (İ) and lowercase it, Unicode specifies that you should end up with a lowercase (dotted) i with a combining dot accent. Your font then needs to be smart enough to know what to do with that…

**Comment by josephwright** [comment]
To be clear, what the case-charger does is follow the standard Unicode Consortium approach, which means replacing codepoints with some equivalents and taking account of certain context-dependent mappings. However, it does _not_ do NFC, which is something explicitly mentioned in the Unicode docs. Here, I'd expect the engine/font shaper to do exactly that, and so to 'see' that "i" plus dot-above is the same as just "i". Things get even more 'interesting' for Lithuanian!

**Comment by car222222** [comment]
@wspr :  Unicode specifies that you should end up with a lowercase (dotted) i with a combining dot accent. 

So it does.  But therefore I am not at all surprised that fonts do not understand how to represent it.  Using lowercase i dotted i (rather than dotted) would make even the least smart fonts do something visually reasonable whereas dotting a dotted i is at best ambiguous and seems more likely (to me) to mean a (visually pleasant) dot above the normal one, maybe a tad smaller?    OK, I understand there is not much we can do about it: we would have a better chance if we asked for an undotted emoji of some kind:-).

 I am sure that the Turkic Guys do not think of their languages as having a dotted-dotted i ??  That would be plain 'dotty', would it not:-)?

**Comment by zauguin** [comment]
@josephwright I'm not sure how NFC plays into this, but "i" plus dot-above is *not* canonically equivalent to "i", so normalizing the text wouldn't make a difference.


@car222222
> @wspr : Unicode specifies that you should end up with a lowercase (dotted) i with a combining dot accent.
> 
> So it does. But therefore I am not at all surprised that fonts do not understand how to represent it. Using lowercase i dotted i (rather than dotted) would make even the least smart fonts do something visually reasonable whereas dotting a dotted i is at best ambiguous and seems more likely (to me) to mean a (visually pleasant) dot above the normal one, maybe a tad smaller? OK, I understand there is not much we can do about it: we would have a better chance if we asked for an undotted emoji of some kind:-).

If this would only affect the "i" with dot-above I would agree, but the same general isssue appears when "i" is combined with any accent attached to the top: According to Unicode, "i" is "soft-dotted", so the dot should disappear if any diacritic is attached. Which also explains why a "i" followed by dot-above can make sense:  "i" followed by acute leads to "í", which inserting a dot-above can explicitly force a "i̇́" as it is used e.g. in some Baltic languages.

So any font which is prepared for arbitrary diacritics on "i" will handle this case gracefully and adding special logic to font shaping would modify the behavior in officially correct cases.

> 
> I am sure that the Turkic Guys do not think of their languages as having a dotted-dotted i ?? That would be plain 'dotty', would it not:-)?

That's why these case changing functions change their official behavior when use with such languages...

**Comment by josephwright** [comment]
@zauguin My main point was that the case change functions do one thing: whether or not there is further normalisation, it's out-of-scope for the case-changer. I see you've covered what the font shaper is _supposed_ to do pretty well :)
