### ISSUE TITLE
Indentation and formating the code in report.cls 

### ISSUE THREAD

**Issue by tmelorc** [latex3/latex3#700]
I'm not sure if here is right place to do this, also not sure if this is too relevant, but I observed some wrong indentation in the code of `report.cls`. Sorry if I'm wrong.

Maybe the solution could be:

```
l175: remove indentation
l207: indent to match with l176
l209-259: indent the whole block inside the \else part
```
Here is the file I checked.
[https://github.com/latex3/latex3/blob/master/texmf/tex/latex/base/report.cls](url)

Regards.

**Comment by josephwright** [comment]
That's a copy of a file from the main LaTeX2e installation: 'not our fault' here.

**Comment by tmelorc** [comment]
Hello @josephwright. Do you mean from [here](https://github.com/latex3/latex2e)?

**Comment by FrankMittelbach** [comment]
I'm not quite sure why @josephwright closed it instead of just transfered, but anyway...  While I appreciate suggestions for improvements on any level the question of fixing the indentation is really not worth reporting. All the .sty and .cls etc files are generated from other sources and often there is a lot of text between code blocks that intentations sometimes get wrong and in all honesty fixing those is a lot of effort for little gain. So if I see them while working anyway on a file I'll fix them but  finding the places you report in this way if not that easy and thus not something for which we have the bandwidth (look at the changelogs to see how many people keep LaTeX working for millions of users)
