### ISSUE TITLE
[feature request] \str_replace(_all)?:(ccn|ccc|cnc)

### ISSUE THREAD

**Issue by tillyboy** [latex3/latex3#733]
I stumbled upon the following peculiarity while writing a package:

      \str_set:cn{l_tmpb_str}{Replace~@<this>}
      \str_log:c{l_tmpb_str} % -> 'Replace @<this>'
      \str_replace_all:cnn{l_tmpb_str}{@<this>}{nothing}
      \str_log:c{l_tmpb_str} % -> 'Replace nothing'

      \str_set:cn{l_tmpb_str}{Replace~@<this>}
      \str_set:cn{l_tmpa_str}{@<this>}
      \str_log:c{l_tmpb_str} % -> 'Replace @<this>'
      \str_replace_all:ccn{l_tmpb_str}{l_tmpa_str}{nothing} % -> error
      \str_log:c{l_tmpb_str}

I know that \str_replace_all:ccn does not exist, but I am interested in a reasoning as to why using string variables as substitution pattern/replacement is not supported. Having only token lists seems quite inflexible to me. Or is there any idiomatic LaTeX3-way of doing this that I overlooked?

**Comment by blefloch** [comment]
With a recent enough expl3, when trying to generate the :cc variant of
\str_replace_all:Nnn you get the following hopefully helpful error message:

! LaTeX3 Error: Variant form 'cc' deprecated for base form
(LaTeX3)        '\str_replace_all:Nnn'. One should not change an argument
(LaTeX3)        from type 'n' to type 'c': use a 'v' variant?

Namely, you should use \str_replace_all:cvn because the v-type argument
specifier means turn what's given into a csname just like c-type, then extract
the value like V-type (in this case expanding the string once).

**Comment by tillyboy** [comment]
Aha! Nice one. Is there a variant where I can use functions as well or am I restricted to assign to a variable first and then use that in my `v`-variant?

**Comment by blefloch** [comment]
Check out the x argument specifier, so \str_replace_all:Nxn (or similar, each
argument is treated independently).  But the functions used must be expandable.
