### ISSUE TITLE
Add support for all PDF color space families

### ISSUE THREAD

**Issue by josephwright** [latex3/latex3#740]
At present, `l3color` deals with separations as a `spot` model. This is rather limited. As discussed in #736, we should support all models offered by PDF (at least). To do this, we need something of the form
```latex
\color_model_new:nnn { name } { family } { settings }
```
plus of course the underlying mechanisms. The latter may need separate issues, for example to discuss how to mix spot colors.

**Comment by car222222** [comment]
@josephwright wrote:  l3color deals with separations as a spot model

Is it not more the other at round?  It uses ‘spotcolor’ in the command to set up a Separation color space.  

It is not clear that it either should or does do anything extra in order to ‘deal with separations’.   But maybe you are including here the cases of more than one separation and of mixing them (plus mixing with process colors).

**Comment by josephwright** [comment]
@car222222 I'm re-working support for Separations: expect updates next week

**Comment by car222222** [comment]
"All PDF color spaces" done, then? 😃
