### ISSUE TITLE
expl3.sty:77: LaTeX3 Error: Mismatched LaTeX support files detected.

### ISSUE THREAD

**Issue by devon-ge** [latex3/latex3#811]
>c:/texlive/2020/texmf-dist/tex/latex/l3kernel/expl3.sty:77: LaTeX3 Error: Mismatched LaTeX support files detected.
(LaTeX3)        Loading 'expl3.sty' aborted!
(LaTeX3)
(LaTeX3)        The L3 programming layer in the LaTeX format
(LaTeX3)        is dated 2020-09-06, but in your TeX tree the files require
(LaTeX3)        at least 2020-09-24.

What does this mean? should I downgrade my installation of TeXlive?

**Comment by josephwright** [comment]
Almost certainly you've updated TeX Live but formats either did not get rebuilt or you have a 'stray' one. At the Command Prompt/Terminal what does
```
kpsewhich --all --engine=pdftex pdflatex.fmt
```
report?

**Comment by devon-ge** [comment]
> $ kpsewhich --all --engine=pdftex pdflatex.fmt

return
> c:/texlive/2020/texmf-var/web2c/pdftex/pdflatex.fmt

**Comment by FrankMittelbach** [comment]
@devon-ge did you trying running pdflatex or pdflatex-dev when you got the above error? Because in the latter case you need to search for stray -dev formats, eg

     kpsewhich --all --engine=pdftex pdflatex-dev.fmt

I had the same problem in my setup and it turned out that at some point I made a local pdflatex-dev format and forgot about it. Once I removed that everything worked fine. 

If you got the error with pdflatex then what is the date of the format in `c:/texlive/2020/texmf-var/web2c/pdftex` does it have a recent date or is it older?

**Comment by devon-ge** [comment]
@FrankMittelbach I searched for `-dev`. It's `c:/texlive/2020/texmf-var/web2c/pdftex/pdflatex-dev.fmt`. The date is Sept 14, 2020. Is it OK to remove this file or the whole folder?

**Comment by u-fischer** [comment]
better rtry to ecreate them with `fmtutil-sys --all`

**Comment by devon-ge** [comment]
@u-fischer Thank you. This command solved this issue.
