### ISSUE TITLE
The bookmarks in source3.pdf are weird

### ISSUE THREAD

**Issue by stone-zeng** [latex3/latex3#860]
All the sections after 37.5 are folded, as well as the implementation part, see the following:

<img src="https://user-images.githubusercontent.com/18233088/109262937-563b5800-783d-11eb-90b3-acf6c9760bf5.png" width="50%">

I use Adobe Acrobat Reader DC, Skim, and macOS's Preview, and they all give the same result.

Version: 2021-02-18

**Comment by stone-zeng** [comment]
Note: the problem doesn't appear in `interface3.pdf`.

**Comment by josephwright** [comment]
Also notice the issue with the section numbers themselves

**Comment by u-fischer** [comment]
The problem is that source3 redefines in the documentation part \maketitle to create chapters, but in the implementation part \maketitle is reset to empty, and as the chapter level is missing the bookmark gets confused. Something like this in source3.tex should work

~~~~
\part{Implementation}

\def\maketitle{\refstepcounter{chapter}} %step chapter

\def\toclevel@section{0}   %change levels 
\def\toclevel@subsection{1}
\def\toclevel@subsubsection{2}
\EnableImplementation
\DisableDocumentation
\DocInputAgain
...
~~~~
