### ISSUE TITLE
Provide colour export using commas

### ISSUE THREAD

**Issue by josephwright** [latex3/latex3#863]
As discussed in https://chat.stackexchange.com/transcript/message/57265351#57265351, etc., we could do with `commas-sep-rgb` and `comma-sep-cmyk` export.

**Comment by car222222** [comment]
I am not sure if multiple detailed syntaxes should be supported individually.  

Maybe better to provide general functions for converting between, for example, space-delimited lists and comma lists.

But going further with syntax details, export as a tuple would be generally useful when we implement extra arithmetical stuff such as blending.

**Comment by zauguin** [comment]
> Maybe better to provide general functions for converting between, for example, space-delimited lists and comma lists.

We already have `\clist_use:Nn` wo map from comma lists to arbitrary-delimited lists and `\seq_use:Nn` and `\seq_set_split:Nnn` to map between sequences and arbitrary-delimited lists, so I think the general function are already in place.

> I am not sure if multiple detailed syntaxes should be supported individually.

I still think that this would be useful. While we already have the space-delimited export (which makes a lot of sense since it's the one most commonly needed in the backend, so direct support allows for improved performance), comma separated export is also important since it both is a directly supported expl3 type and is the import format we expect for color specifications. IMO getting the color in the format we use for input should not require any additional conversion.

**Comment by car222222** [comment]
"getting the color in the format we use for input should not require any additional conversion"

Input to what?  I need to use tuples to do arithmetic, so I asked for those.  Why not use just one format for input and output?  

I still do not see any reason not to use conversion functions internally, then you can support any output syntax.  Why have such functions if we do not use them?

**Comment by zauguin** [comment]
> Input to what? I need to use tuples to do arithmetic, so I asked for those. Why not use just one format for input and output?

Input to `l3color`. Especially `\color_set:nnn` expects the last argument to be a comma-delimited list of axis values. Also when a comma-delimited list is provided, tuples are supported too since you can just put parens around the list. Doing the reverse would be more complicated.

**Comment by car222222** [comment]
OK, I am happy to make 'commas' the underlying standard for both output and input.
