### ISSUE TITLE
\tl_show:N does not work (?)

### ISSUE THREAD

**Issue by joulev** [latex3/latex3#879]
```tex
% arara: pdflatex
\documentclass{article}
\usepackage{expl3}
\begin{document}
Hello world
\ExplSyntaxOn
\tl_set:Nn \l_tmpa_tl {abc}
\tl_show:N \l_tmpa_tl
\ExplSyntaxOff
\end{document}
```

I don't know what I am getting wrong here, but this one gives an error. Compiled immediately after updating TL, so the `expl3` is up-to-date.

```
> \l_tmpa_tl=abc.
<recently read> }
                 
l.8 \tl_show:N \l_tmpa_tl
                         
? 
! Emergency stop.
<recently read> }
                 
l.8 \tl_show:N \l_tmpa_tl
                         
End of file on the terminal!
```

Commenting out L8 clears the error.

Log file: [test.log](https://github.com/latex3/latex3/files/6371365/test.log)

**Comment by blefloch** [comment]
This looks like perhaps a bug in arara?  I get the same error with
```
% arara: pdflatex
\show\something
\stop
```

**Comment by FrankMittelbach** [comment]
If you run this document through LaTex without using arara you get exactly the behavior that is expected.  In the TeX book `\show` is document to produce an error and stop at this point. The reason is that when TeX was developed abandom a faulty run was very costly in time so Don used the error routine to make TeX stop when he was debugging, so that he could insert some corrective input at that point (with `i ...` in reply to the error) and then continue the processing.

Now the the `\show_...` commands of `expl3` are all modeled after `\show` so you also get an error when you use them. Now of course this was meant as a method for interactive debugging; when you run with `\batchmode` then generating an error will stop your run with the line `!Emergency stop` which is what you show above.

Thus my conclusion is that `arara` invokes TeX with `\batchmode` or `\nonstopmode`. So it neither a bug in LaTeX nor really in arara (as arara is not meant for interactive debugging).

**Comment by FrankMittelbach** [comment]
Thus `\show_..` commands are of little use if you run with arara but you could `\log_...` instead.

**Comment by TheTeXnician** [comment]
It's a misunderstanding of how arara works and what it tries to do. Running this document is expected to yield whatever TeX yields. That is, TeX seems to do an emergency stop if there is no input stream available (i.e. no user input could be read anyway). When asked for non-interactive mode, arara does not provide an input stream, so if TeX does stop arara stops and results in this log file.

When run in interactive mode (aka verbose) `arara -v file.tex` you will get the usual interactive behavior. And as arara is meant  to be flexible, if you tell it you want interaction (`-v`) you will get it. Then you can use that interactive session for whatever you want, even interactive debugging. Saying arara is not meant for interactive debugging is more or less a “bug” in the answer :wink: 

To be clear, arara does *not* invoke with bachmode or nonstopmode (other tools maybe but not arara). arara does only what the user tells it to do. There is a manual describing its behavior in detail. @cereda might help out with details if needed.

**Comment by joulev** [comment]
Oh yes, I see, I used to run pdflatex directly and only switched to arara recently, so this is a problem with compilation mode, which is neither expl3’s bug nor arara’s. Thank you for your clarification!

**Comment by FrankMittelbach** [comment]
> It's a misunderstanding of how arara works and what it tries to do. Running this document is expected to yield whatever TeX yields.

well yes and no,  arara by default then abandons the run which is rather equivalent to running with \batchmode  and it is the default behavior of arara but not of TeX in that situation. But I'm happy to stay corrected that arara has a way to offer interactive TeX use (but it isn't its default operation mode) and my guess (not using arara) is that `-v` does more than that and it was not provide for interactive TeX usage (which is a side effect) but to debug what is going on in your arara script.

**Comment by TheTeXnician** [comment]
Well, that's probably simply a matter of phrasing. Whether “TeX exits because it tries from a non-existent input stream” (which is actually quite expected for many tools that try to read from stdin) or “arara abandons the run because it does not provide an input stream TeX desires” is probably not too relevant.

Concerning `-v`, the whole point is to be transparent to the process being run, i.e. TeX most of the time. This transparency includes the redirection  of input and output streams. Most users apply that option to see the output. Let me try to show the output: for `arara file.tex` for the example I get

```
  __ _ _ __ __ _ _ __ __ _
 / _` | '__/ _` | '__/ _` |
| (_| | | | (_| | | | (_| |
 \__,_|_|  \__,_|_|  \__,_|

Processing "test.tex" (size: 184 B, last modified: 04/25/2021
10:31:47), please wait.

(PDFLaTeX) PDFLaTeX engine .............................. FAILURE
Total: 0.29 seconds
```

so this is a summary of all instructions given to arara. It will prevent interaction and not redirect the system input or output. So the only way to see TeX's output is reading `file.log`. `-v` on the other hand acts like the usual terminal you are using, providing a redirection of the input and output streams. That is, arara will show the output of the TeX run and wait for interaction where necessary. `arara -v file.tex` yields

```
  __ _ _ __ __ _ _ __ __ _
 / _` | '__/ _` | '__/ _` |
| (_| | | | (_| | | | (_| |
 \__,_|_|  \__,_|_|  \__,_|

Processing "test.tex" (size: 184 B, last modified: 04/25/2021
10:31:47), please wait.

-----------------------------------------------------------------
(PDFLaTeX) PDFLaTeX engine
-----------------------------------------------------------------
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2021) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./test.tex
LaTeX2e <2020-10-01> patch level 4
L3 programming layer <2021-02-18>
(/usr/local/texlive/2021/texmf-dist/tex/latex/base/article.cls
Document Class: article 2020/04/10 v1.4m Standard LaTeX document class
(/usr/local/texlive/2021/texmf-dist/tex/latex/base/size10.clo))
(/usr/local/texlive/2021/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/local/texlive/2021/texmf-dist/tex/latex/l3backend/l3backend-pdftex.def))
(./test.aux)
> \l_tmpa_tl=abc.
<recently read> }
                 
l.8 \tl_show:N \l_tmpa_tl
                         
?
```

As shown, arara waits for the user input. The `-v` flag is intentionally provided for exactly this: Running with input and output stream redirected, i.e. interactive usage, it is not a side effect.

And it only affects the tools to be run. To “debug what is going on in your arara script” one should use arara's logging because that is the only way to see what arara is really doing. On the other hand, the typical debugging involves just reading the error message. For instance, changing `% arara: pdflatex` to `% arara: pdflate` will leave

```
  __ _ _ __ __ _ _ __ __ _
 / _` | '__/ _` | '__/ _` |
| (_| | | | (_| | | | (_| |
 \__,_|_|  \__,_|_|  \__,_|

Processing "test.tex" (size: 183 B, last modified: 04/25/2021
11:12:07), please wait.

----------------------------------------------------------- ERROR

I could not find a rule named "pdflate" in the provided rule
paths. Perhaps a misspelled word? I was looking for a file named
"pdflate.yaml" in the following paths in order of priority:
(/usr/local/texlive/2021/texmf-dist/scripts/arara/rules)

Total: 0.03 seconds
```

regardless of `-v` or not.

I hope this somehow clarifies the intention :slightly_smiling_face:
