### ISSUE TITLE
Should colors have a \color_new:n and \color_const:nn commands?

### ISSUE THREAD

**Issue by blefloch** [latex3/latex3#935]
In #925, we had a discussion of the fact that essentially all datatypes have a (type)`_new` function separate from (type)`_set`.  This is not the case of colors, for which `\color_set:nn { foo } { blue }` works fine without declaring `foo`.

I don't have strong opinions but I figure this could be good to keep consistent between types.

**Comment by josephwright** [comment]
All of the 'restricted' data types (colors, keys, messages) are non-standard, although not 100% consistent I agree.  (These are 'restricted' in that they have limited choices for the names, all living inside a small namespace.) Colors, like keys or messages have to have a value and a 'default' isn't logical, so the `new`/`set` split doesn't really work. At a user level, colors (and keys) are 'declared' in one shot, so you end up having to have some conditional if you want to allow `\declarecolor` to work with them.

With hindsight I'd probably adjust `msg` and `keys`, not `color` (which is newest and I think therefore most correct)

- I'd drop `\msg_new:nn...` and just use `\msg_set:nn...`
- I'd call current `\keys_set:nn` as `\keys_assign:nn`, as it doesn't have the same 1-1 relationship as any other `set` function

Neither of these of course address the issue here! I'm not really keen on requiring a `new`/`set` split as people don't have a 'free hand' in naming. (OK, they could do `pkg/name` for a color in the way we do for keys and messages, but I think that's pretty awkward.)

If we want to make a change here, we should tighten up the other cases too.

**Comment by wspr** [comment]
Where do you see “logical” colour names fitting into things here? E.g., would we expect to start seeing packages write \color_new:n { section-heading } ? To me that would seem to be at the wrong layer, but it kind of makes sense to me that colours should be declared within each package and clashes detected. In that case adding color_new at least would seem to be appropriate.

**Comment by josephwright** [comment]
> Where do you see “logical” colour names fitting into things here? E.g., would we expect to start seeing packages write \color_new:n { section-heading } ? To me that would seem to be at the wrong layer, but it kind of makes sense to me that colours should be declared within each package and clashes detected. In that case adding color_new at least would seem to be appropriate.

I'd hope people would do `<pkg> / <name>` if they want to do that, but based on `beamer` (which tracks colours like this), I don't know that they'd be 'real' colours, more likely token lists of colour names.
