### ISSUE TITLE
\prop_item:N{e,f,x}

### ISSUE THREAD

**Issue by bastien-roucaries** [latex3/latex3#960]
Hi,

It will be nice to implement more version of prop_item, it will simplify the code of polyglossia

**Comment by eg9** [comment]
You can do
```
\cs_generate_variant:Nn \prop_item:Nn { e,f,x}
```
and you'll be sure this won't be in conflict with other packages doing the same.

**Comment by FrankMittelbach** [comment]
Basically we don't want to pollute the core with code that may not get used a lot. What @eg9  suggested is the official interface, i.e., it can be used multiple times (in different packages) and has nearly no overhead. So if you define an "e" variant and somebody else does too, then the first time it gets defined and all the others it gets bypassed fairly fast without change.

So please use that if you are missing any variant.

**Comment by blefloch** [comment]
Note that the `x` variant won't work the way you expect: because `x` expansion cannot be done expandably, it will be a protected command, so it becomes pretty useless except for typesetting directly the value.  On the other hand the `e` expansion is almost a drop-in replacement for `x` (different handling of `#`), so that should work best nowadays.
