### ISSUE TITLE
Problem with \c_math_subscript_token in xparse argument specification 

### ISSUE THREAD

**Issue by carlostome** [latex3/latex3#985]
Using `\c_math_subscript_token` to specify an *embellishment* argument `e{\c_math_subscript_token}` causes the argument parser to parse incorrectly. 

In the MWE below, `\fone` behaves as expected, but `ftwo` does not.
```latex
\documentclass{article}
\usepackage{xparse}

\NewDocumentCommand{\fone}{e{_}o}{%
  {\mathrm{fun}}%
  \IfValueT {#1} {_{#1}}%
  \,#2%
}%

\ExplSyntaxOn
\NewDocumentCommand{\ftwo}{e{\c_math_subscript_token}o}{%
  {\mathrm{fun}}%
  \IfValueT {#1} {\c_math_subscript_token{#1}}%
  \,#2%
}%
\ExplSyntaxOff
\begin{document}

$\fone_{1}[(3,4)]$

$\ftwo_{1}[(3,4)]$
\end{document}
```
### Dependencies:
+ TeXLive 2021
+ pdflatex 3.141592653-2.6-1.40.22
+ xparse.sty    2021-01-09 L3 Experimental document command parser
+  expl3.sty    2021-02-18 L3 programming layer (loader)

**Comment by PhelypeOleinik** [comment]
This is the expected behaviour.  When you use a control sequence token as delimiter in the definition of a command, the usage requires the same control sequence token in the input stream, so the correct usage of your command would be `\ftwo\c_math_subscript_token...`.  This is documented in section 2.12 (Details about argument delimiters) of [`usrguide3.pdf`](http://mirrors.ctan.org/macros/latex/base/usrguide3.pdf).

**Comment by FrankMittelbach** [comment]
So it is @PhelypeOleinik , and on the general level I agree. However, one of the core applications of the embellishments is to get `e{^_}` and while that works perfectly in 2e context it stops working nicely if the declaration is made in L3 layer context (I assume), so I wonder if  for `:` and `_` regardless of input catcode standard catcodes should be parsed.

**Comment by car222222** [comment]
Frank's very real concern seems as if it maybe a distinct issue, with wider applications beyond specific xparse/ltcmd concerns such as e-specifications.  

And maybe there is not only : _ in L3prog (L3PL) contexts?
For example, what about e{@} in a "2eprog environment"?

The general issue is something like: 
absorbing arguments using a known adjusted/specialised catcode regime.

**Comment by PhelypeOleinik** [comment]
I don't like the idea of special-casing `_` and `:` because they have different catcodes in `expl3` code.  If we make `e{_}` parse a catcode 7 `_`, what should happen in a document that loads `underscore`?  Same for parsing `e{:}` with catcode 12:  what should it do about a document that loads `babel`?  I think either we should clearly document that using the proper (intended) token is a task for who is writing the command, or change parsing of `e` so that it works regardless of the catcode.

I'm particularly not fond of the second option either, because all other delimiters require both charcode and catcode to match, but maybe it would be fine for `e`.

Something that may be worth considering is some kind of argument modifier that makes matching work regardless of catcode, so something like `*e{^_}` would only match regardless of catcode.  Though that is not entirely possible for things like `d[]`, where the second delimiter is matched using a delimited macro (it is possible, or fast, but not both).

**Comment by josephwright** [comment]
```latex
\exp_args:NNe \NewDocumentCommand \foo { e{\char_generate:nn { `\_ } { 8 } }
```

**Comment by callegar** [comment]
That will expand all the second argument of \NewDocumentCommand though, right? If I have any optional command whose default is a macro that will be expanded...

**Comment by Skillmon** [comment]
Expansion control is your friend:

```latex
\exp_args:NNe \NewDocumentCommand \foo { e{\char_generate:nn { `\_ } { 8 } O{ \exp_not:N \bar } }
```

**Comment by callegar** [comment]
Sorry, I messed the syntax above.

Now what if I need the ~ as a "t" type argument? In general, I am getting the feeling that any "active" char is problematic...

I have tried

```
\exp_args:NNe \NewDocumentCommand \Sig
  { s t { \char_generate:nn { `\~ } { 13 } }
    m e { \char_generate:nn { `\^ } { 7 } \char_generate:nn { `\_ } { 8 } } }
```

but it works in some (simple) documents and it breaks in others (more realistic)...

**Comment by josephwright** [comment]
@callegar You can always arrange to use a 'generator' function to pass arbitrary tokens to a command - here you would simply pass on a list of what you want. This is not really linked to the original query - if you need general assistance, please consider starting a thread at TeX-sx or TopAnswers or Reddit, etc.

**Comment by callegar** [comment]
You are right, and I have already solved my own issue. Sorry for the noise...
